In [1]:
import os
import time
import math
import random
import pickle
import numpy as np
import tensorflow as tf
import multiprocess as mp
from libs.TicTacToe import TicTacToe
from libs.model import create_az_model
from libs.MCTS import MCTS
from libs.Trainer import Trainer

In [2]:
n_cores = mp.cpu_count()
print(f"[Number of cores]: {n_cores}")

[Number of cores]: 16


## Tic-Tac-Toe engine

In [3]:
state = np.array([0., 0., -1., -1., 1., -1., 1., 1., 0.])
TicTacToe().get_available_actions(state)

array([1., 1., 0., 0., 0., 0., 0., 0., 1.])

In [4]:
ttt = TicTacToe()

while ttt.status=="Ongoing":

    valid_moves = ttt.next_moves()
    new_board = random.choice(valid_moves)
    ttt.play(new_board)
    print(np.reshape(ttt.board, (3,3)),"\n")
    if len(valid_moves)==0:
        break

print("[Winner]:",ttt.winner)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]] 

[[ 0.  0.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]] 

[[ 0.  0.  0.]
 [-1.  0.  1.]
 [ 0.  0.  1.]] 

[[ 0.  0.  0.]
 [-1.  0.  1.]
 [ 0. -1.  1.]] 

[[ 1.  0.  0.]
 [-1.  0.  1.]
 [ 0. -1.  1.]] 

[[ 1.  0. -1.]
 [-1.  0.  1.]
 [ 0. -1.  1.]] 

[[ 1.  0. -1.]
 [-1.  0.  1.]
 [ 1. -1.  1.]] 

[[ 1.  0. -1.]
 [-1. -1.  1.]
 [ 1. -1.  1.]] 

[[ 1.  1. -1.]
 [-1. -1.  1.]
 [ 1. -1.  1.]] 

[Winner]: 0


## Create policy and probability model

In [5]:
model = create_az_model()

In [6]:
model.summary()

Model: "tictactoe_model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 9)]                  0         []                            
                                                                                                  
 tf.__operators__.add (TFOp  (None, 9)                    0         ['input_1[0][0]']             
 Lambda)                                                                                          
                                                                                                  
 tf.cast (TFOpLambda)        (None, 9)                    0         ['tf.__operators__.add[0][0]']
                                                                                                  
 tf.one_hot (TFOpLambda)     (None, 9, 3)                 0         ['tf.cast[0][0]'

In [7]:
tf.keras.utils.plot_model(model, show_shapes=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


# Monte Carlo Tree Search

In [8]:
mcts = MCTS(game=TicTacToe(), n_simulations=100)

In [9]:
state = np.array([0., 0., -1., -1., 1., -1., 1., 1., 0.])

In [10]:
root = mcts.run(model=model, state=state, player=1)

1/1 [==============================] - 0s 16ms/step


In [11]:
root

State:
[ 0.  0. -1. -1.  1. -1.  1.  1.  0.]
Player:1
Value:0.96
Leaf:False
Visits:100
Children:
 -0: prior=0.3333333333333333
 -1: prior=0.3333333333333333
 -8: prior=0.3333333333333333

# Generating the first dataset

In [12]:
STARTING_TEMPERATURE = 10.0

In [13]:
# speed test on 100 games
start_time = time.time()
trainer = Trainer(game = TicTacToe, mcts = MCTS, model=None)
dataset = trainer.create_dataset(number_of_games=100, temperature=starting_temperature)
print("Running time: %s seconds" % (time.time() - start_time))

Running time: 15.1300208568573 seconds


In [14]:
def parallel_fn(n):
    from libs.Trainer import Trainer
    from libs.TicTacToe import TicTacToe
    from libs.MCTS import MCTS
    N_GAMES_PER_JOB = 25
    starting_temperature = 10.0
    trainer = Trainer(game = TicTacToe, mcts = MCTS, model=None)
    game_batch = trainer.create_dataset(number_of_games=N_GAMES_PER_JOB, temperature=STARTING_TEMPERATURE)
    return game_batch

In [15]:
start_time = time.time()
ctx = mp.get_context("spawn")
pool = ctx.Pool(n_cores)
dataset = pool.map(parallel_fn, range(n_cores))
print("Running time: %s seconds" % (time.time() - start_time))

Running time: 17.62233281135559 seconds


In [16]:
N_GAMES_PER_JOB = 25
filename = str(N_GAMES_PER_JOB*n_cores)+"_tictactoe_temperature_"+str(starting_temperature)+".pickle"

flatten_dataset = []
for batch in dataset:
    flatten_dataset += batch
    
with open(filename, "wb") as fp:
    pickle.dump(flatten_dataset, fp, protocol=pickle.HIGHEST_PROTOCOL)

# 1st training

In [17]:
trainer = Trainer(game = TicTacToe, mcts = MCTS, model=create_az_model())

with open(filename, 'rb') as handle:
    dataset = pickle.load(handle)

In [18]:
fit_history = trainer.train(flatten_dataset, n_epochs=1000, batch_size=30, learning_rate=1e-2)

Epoch 1/1000


90/90 [==============================] - 2s 7ms/step - loss: 3.5886 - policy_loss: 1.8836 - value_loss: 1.6082 - val_loss: 3.0477 - val_policy_loss: 2.1091 - val_value_loss: 0.8242 - lr: 0.0100
Epoch 2/1000
90/90 [==============================] - 0s 5ms/step - loss: 2.6339 - policy_loss: 1.6385 - value_loss: 0.8821 - val_loss: 3.0722 - val_policy_loss: 2.1497 - val_value_loss: 0.8138 - lr: 0.0100
Epoch 3/1000
90/90 [==============================] - 0s 5ms/step - loss: 2.4557 - policy_loss: 1.5156 - value_loss: 0.8340 - val_loss: 2.5625 - val_policy_loss: 1.6481 - val_value_loss: 0.8123 - lr: 0.0100
Epoch 4/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.4074 - policy_loss: 1.4710 - value_loss: 0.8350 - val_loss: 2.4468 - val_policy_loss: 1.5361 - val_value_loss: 0.8123 - lr: 0.0100
Epoch 5/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.3708 - policy_loss: 1.4393 - value_loss: 0.8336 - val_loss: 2.3364 - val_policy_loss: 1.4290 -

90/90 [==============================] - 0s 4ms/step - loss: 2.1754 - policy_loss: 1.2720 - value_loss: 0.8324 - val_loss: 2.1686 - val_policy_loss: 1.2854 - val_value_loss: 0.8123 - lr: 2.2823e-04
Epoch 39/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1776 - policy_loss: 1.2744 - value_loss: 0.8324 - val_loss: 2.1678 - val_policy_loss: 1.2848 - val_value_loss: 0.8123 - lr: 1.7249e-04
Epoch 40/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1761 - policy_loss: 1.2732 - value_loss: 0.8324 - val_loss: 2.1679 - val_policy_loss: 1.2851 - val_value_loss: 0.8123 - lr: 1.2907e-04
Epoch 41/1000
90/90 [==============================] - 0s 5ms/step - loss: 2.1758 - policy_loss: 1.2730 - value_loss: 0.8324 - val_loss: 2.1681 - val_policy_loss: 1.2854 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 42/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1735 - policy_loss: 1.2708 - value_loss: 0.8324 - val_loss: 2.1679 - val_policy_loss: 1.2

Epoch 77/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1643 - policy_loss: 1.2672 - value_loss: 0.8324 - val_loss: 2.1634 - val_policy_loss: 1.2865 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 78/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1641 - policy_loss: 1.2672 - value_loss: 0.8324 - val_loss: 2.1632 - val_policy_loss: 1.2864 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 79/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1654 - policy_loss: 1.2686 - value_loss: 0.8324 - val_loss: 2.1631 - val_policy_loss: 1.2865 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 80/1000
90/90 [==============================] - 0s 5ms/step - loss: 2.1619 - policy_loss: 1.2652 - value_loss: 0.8324 - val_loss: 2.1630 - val_policy_loss: 1.2865 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 81/1000
90/90 [==============================] - 0s 5ms/step - loss: 2.1611 - policy_loss: 1.2646 - value_loss: 0.8324 - val_loss: 2.1622 - val_po

Epoch 116/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1533 - policy_loss: 1.2621 - value_loss: 0.8324 - val_loss: 2.1571 - val_policy_loss: 1.2861 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 117/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1554 - policy_loss: 1.2643 - value_loss: 0.8324 - val_loss: 2.1572 - val_policy_loss: 1.2863 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 118/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1538 - policy_loss: 1.2629 - value_loss: 0.8324 - val_loss: 2.1567 - val_policy_loss: 1.2859 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 119/1000
90/90 [==============================] - 0s 5ms/step - loss: 2.1541 - policy_loss: 1.2634 - value_loss: 0.8324 - val_loss: 2.1570 - val_policy_loss: 1.2864 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 120/1000
90/90 [==============================] - 0s 5ms/step - loss: 2.1547 - policy_loss: 1.2641 - value_loss: 0.8324 - val_loss: 2.1570 - v

90/90 [==============================] - 0s 5ms/step - loss: 2.1461 - policy_loss: 1.2600 - value_loss: 0.8324 - val_loss: 2.1528 - val_policy_loss: 1.2868 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 155/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1470 - policy_loss: 1.2609 - value_loss: 0.8324 - val_loss: 2.1524 - val_policy_loss: 1.2865 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 156/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1466 - policy_loss: 1.2607 - value_loss: 0.8324 - val_loss: 2.1521 - val_policy_loss: 1.2863 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 157/1000
90/90 [==============================] - 0s 4ms/step - loss: 2.1492 - policy_loss: 1.2634 - value_loss: 0.8324 - val_loss: 2.1523 - val_policy_loss: 1.2866 - val_value_loss: 0.8123 - lr: 1.0000e-04
Epoch 158/1000
90/90 [==============================] - 0s 5ms/step - loss: 2.1476 - policy_loss: 1.2619 - value_loss: 0.8324 - val_loss: 2.1522 - val_policy_loss:

In [19]:
trainer.model.predict(np.array([[0., 0., -1., -1., 1., -1., 1., 1., 0.]]))

1/1 [==============================] - 0s 129ms/step


(array([[1.5292804e-02, 3.7834185e-01, 6.2949868e-04, 2.4268795e-05,
         1.5596172e-04, 8.0116923e-05, 1.5714881e-04, 6.8897156e-05,
         6.0524940e-01]], dtype=float32),
 array([[0.07633218]], dtype=float32))

In [20]:
trainer.model.predict(np.array([[0., 0., 0., 0., -1., 1., -1., 0., 0.]]))

1/1 [==============================] - 0s 24ms/step


(array([[7.0850857e-02, 8.1257693e-02, 5.1002884e-01, 1.2070657e-01,
         2.4216896e-04, 4.6085939e-04, 1.1106054e-03, 9.6659914e-02,
         1.1868248e-01]], dtype=float32),
 array([[0.07633218]], dtype=float32))

In [21]:
trainer.save_model('saved_model/tmp_model')

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


# Generating the self-playing dataset (2nd)

loaded_model = tf.keras.models.load_model("saved_model/alpha_zero_model_first_training_validation/")

# speed test on 10 games
start_time = time.time()
trainer = Trainer(game = TicTacToe, mcts = MCTS, model=loaded_model)
dataset = trainer.create_dataset(number_of_games=10, temperature=1)
print("Running time: %s seconds" % (time.time() - start_time))

In [ ]:
# 1175s -> ~30m for 100
# 25*0.5 ~ 12hs

In [ ]:
model = create_az_model()

In [22]:
N_ROUNDS = 40
N_GAMES_PER_JOB = 25

In [23]:
def parallel_fn(job_n, n):
    
    from libs.Trainer import Trainer
    from libs.TicTacToe import TicTacToe
    from libs.MCTS import MCTS
    import tensorflow as tf
    N_GAMES_PER_JOB = 25
    STARTING_TEMPERATURE = 10.0
    
    model = tf.keras.models.load_model("saved_model/tmp_model")
    
    trainer = Trainer(game = TicTacToe, mcts = MCTS, model=model)
    
    game_batch = trainer.create_dataset(number_of_games=N_GAMES_PER_JOB, temperature=STARTING_TEMPERATURE/n)
    
    return game_batch

#stored previous self-plays
filename_data = "4000_tictactoe_temperature_1_2nd_round.pickle"
if os.path.isfile(filename_data):
    with open(filename_data, 'rb') as handle:
        self_play_dataset = pickle.load(handle)
    print(f"Reusing {filename_data}")
else:
    self_play_dataset = []
    print(f"Starting from empty self-play data")

model_tmp_filename = "saved_model/tmp_model"
if os.path.isdir(model_tmp_filename):
    model = tf.keras.models.load_model(model_tmp_filename)
    print(f"Starting with {model_tmp_filename}")
else:
    model = tf.keras.models.load_model("saved_model/alpha_zero_model_first_training_validation/")
    print(f"Starting with saved_model/alpha_zero_model_first_training_validation/")

model.save(model_tmp_filename)

In [ ]:
self_play_dataset = flatten_dataset

for n in range(N_ROUNDS):
    
    start_time = time.time()
    
    ctx = mp.get_context("spawn")
    
    pool = ctx.Pool(n_cores)
    
    args = list(zip(range(n_cores),[n+1]*n_cores))
    
    round_dataset = pool.starmap(parallel_fn, args)
    print(f"Running time {n+1}-th round: {time.time() - start_time} seconds")
    
    flatten_round_dataset = []
    for batch in round_dataset:
        flatten_round_dataset += batch
    self_play_dataset += flatten_round_dataset
    
    trainer = Trainer(game = TicTacToe, mcts = MCTS, model=model)
    fit_history = trainer.train(self_play_dataset, n_epochs=50, batch_size=50, learning_rate=1e-2)
    
    trainer.model.save("saved_model/tmp_model")
    
    with open("selfplay_data.pickle", "wb") as fp:
        pickle.dump(self_play_dataset, fp, protocol=pickle.HIGHEST_PROTOCOL)
    

Running time 1-th round: 784.0851500034332 seconds
Epoch 1/50
99/99 [==============================] - 2s 7ms/step - loss: 3.4331 - policy_loss: 1.8701 - value_loss: 1.4685 - val_loss: 2.8795 - val_policy_loss: 1.8861 - val_value_loss: 0.8879 - lr: 0.0100
Epoch 2/50
99/99 [==============================] - 1s 5ms/step - loss: 2.5445 - policy_loss: 1.5845 - value_loss: 0.8573 - val_loss: 2.7668 - val_policy_loss: 1.7774 - val_value_loss: 0.8885 - lr: 0.0100
Epoch 3/50
99/99 [==============================] - 0s 5ms/step - loss: 2.4404 - policy_loss: 1.4814 - value_loss: 0.8578 - val_loss: 2.4676 - val_policy_loss: 1.4782 - val_value_loss: 0.8879 - lr: 0.0100
Epoch 4/50
99/99 [==============================] - 0s 5ms/step - loss: 2.3856 - policy_loss: 1.4258 - value_loss: 0.8581 - val_loss: 2.4274 - val_policy_loss: 1.4353 - val_value_loss: 0.8896 - lr: 0.0100
Epoch 5/50
99/99 [==============================] - 0s 5ms/step - loss: 2.3574 - policy_loss: 1.3974 - value_loss: 0.8575 - val_l

99/99 [==============================] - 0s 5ms/step - loss: 2.1413 - policy_loss: 1.2390 - value_loss: 0.8565 - val_loss: 2.1768 - val_policy_loss: 1.2427 - val_value_loss: 0.8885 - lr: 1.2907e-04
Epoch 41/50
99/99 [==============================] - 1s 5ms/step - loss: 2.1403 - policy_loss: 1.2383 - value_loss: 0.8565 - val_loss: 2.1765 - val_policy_loss: 1.2426 - val_value_loss: 0.8885 - lr: 1.0000e-04
Epoch 42/50
99/99 [==============================] - 0s 5ms/step - loss: 2.1408 - policy_loss: 1.2389 - value_loss: 0.8565 - val_loss: 2.1767 - val_policy_loss: 1.2430 - val_value_loss: 0.8884 - lr: 1.0000e-04
Epoch 43/50
99/99 [==============================] - 1s 6ms/step - loss: 2.1406 - policy_loss: 1.2389 - value_loss: 0.8565 - val_loss: 2.1770 - val_policy_loss: 1.2435 - val_value_loss: 0.8884 - lr: 1.0000e-04
Epoch 44/50
99/99 [==============================] - 0s 5ms/step - loss: 2.1407 - policy_loss: 1.2392 - value_loss: 0.8565 - val_loss: 2.1760 - val_policy_loss: 1.2427 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 2-th round: 699.984493970871 seconds
Epoch 1/50
144/144 [==============================] - 2s 6ms/step - loss: 2.3448 - policy_loss: 1.4013 - value_loss: 0.8670 - val_loss: 2.3434 - val_policy_loss: 1.3293 - val_value_loss: 0.9194 - lr: 0.0100
Epoch 2/50
144/144 [==============================] - 1s 5ms/step - loss: 2.3313 - policy_loss: 1.3598 - value_loss: 0.8680 - val_loss: 2.3308 - val_policy_loss: 1.3047 - val_value_loss: 0.9188 - lr: 0.0100
Epoch 3/50
144/144 [==============================] - 1s 5ms/step - loss: 2.3259 - policy_loss: 1.3467 - value_loss: 0.8681 - val_loss: 2.3273 - val_policy_loss: 1.2967 - val_value_loss: 0.9191 - lr: 0.0100
Epoch 4/50
144/144 [==============================] - 1s 5ms/step - loss: 2.3148 - policy_loss: 1.3349 - value_loss: 0.8686 - val_loss: 2.3572 - val_policy_loss: 1.3267 - val_value_loss: 0.9202 - lr: 0.0100
Epoch 5/50
144/144 [==============================] - 1s 5ms/step - loss: 2.3227 - policy_loss: 1.3388 - value_loss: 0.867

144/144 [==============================] - 1s 5ms/step - loss: 2.1372 - policy_loss: 1.2250 - value_loss: 0.8671 - val_loss: 2.1308 - val_policy_loss: 1.1666 - val_value_loss: 0.9191 - lr: 1.2907e-04
Epoch 41/50
144/144 [==============================] - 1s 5ms/step - loss: 2.1362 - policy_loss: 1.2241 - value_loss: 0.8671 - val_loss: 2.1302 - val_policy_loss: 1.1662 - val_value_loss: 0.9191 - lr: 1.0000e-04
Epoch 42/50
144/144 [==============================] - 1s 5ms/step - loss: 2.1367 - policy_loss: 1.2248 - value_loss: 0.8671 - val_loss: 2.1301 - val_policy_loss: 1.1662 - val_value_loss: 0.9191 - lr: 1.0000e-04
Epoch 43/50
144/144 [==============================] - 1s 5ms/step - loss: 2.1363 - policy_loss: 1.2246 - value_loss: 0.8671 - val_loss: 2.1286 - val_policy_loss: 1.1649 - val_value_loss: 0.9191 - lr: 1.0000e-04
Epoch 44/50
144/144 [==============================] - 1s 5ms/step - loss: 2.1366 - policy_loss: 1.2250 - value_loss: 0.8671 - val_loss: 2.1290 - val_policy_loss: 1

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 3-th round: 651.7305974960327 seconds
Epoch 1/50
187/187 [==============================] - 2s 6ms/step - loss: 2.2667 - policy_loss: 1.3297 - value_loss: 0.8730 - val_loss: 2.2512 - val_policy_loss: 1.2460 - val_value_loss: 0.9315 - lr: 0.0100
Epoch 2/50
187/187 [==============================] - 1s 5ms/step - loss: 2.2534 - policy_loss: 1.3042 - value_loss: 0.8723 - val_loss: 2.2781 - val_policy_loss: 1.2674 - val_value_loss: 0.9305 - lr: 0.0100
Epoch 3/50
187/187 [==============================] - 1s 5ms/step - loss: 2.2594 - policy_loss: 1.3050 - value_loss: 0.8722 - val_loss: 2.3810 - val_policy_loss: 1.3651 - val_value_loss: 0.9314 - lr: 0.0100
Epoch 4/50
187/187 [==============================] - 1s 5ms/step - loss: 2.2543 - policy_loss: 1.2986 - value_loss: 0.8721 - val_loss: 2.2599 - val_policy_loss: 1.2438 - val_value_loss: 0.9312 - lr: 0.0100
Epoch 5/50
187/187 [==============================] - 1s 5ms/step - loss: 2.2593 - policy_loss: 1.3011 - value_loss: 0.87

187/187 [==============================] - 1s 5ms/step - loss: 2.1174 - policy_loss: 1.2101 - value_loss: 0.8716 - val_loss: 2.1097 - val_policy_loss: 1.1429 - val_value_loss: 0.9312 - lr: 1.2907e-04
Epoch 41/50
187/187 [==============================] - 1s 5ms/step - loss: 2.1150 - policy_loss: 1.2080 - value_loss: 0.8716 - val_loss: 2.1090 - val_policy_loss: 1.1423 - val_value_loss: 0.9313 - lr: 1.0000e-04
Epoch 42/50
187/187 [==============================] - 1s 5ms/step - loss: 2.1144 - policy_loss: 1.2075 - value_loss: 0.8716 - val_loss: 2.1089 - val_policy_loss: 1.1423 - val_value_loss: 0.9313 - lr: 1.0000e-04
Epoch 43/50
187/187 [==============================] - 1s 5ms/step - loss: 2.1143 - policy_loss: 1.2075 - value_loss: 0.8716 - val_loss: 2.1081 - val_policy_loss: 1.1416 - val_value_loss: 0.9312 - lr: 1.0000e-04
Epoch 44/50
187/187 [==============================] - 1s 5ms/step - loss: 2.1153 - policy_loss: 1.2086 - value_loss: 0.8716 - val_loss: 2.1081 - val_policy_loss: 1

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 4-th round: 645.3469252586365 seconds
Epoch 1/50
232/232 [==============================] - 3s 6ms/step - loss: 2.2150 - policy_loss: 1.2969 - value_loss: 0.8689 - val_loss: 2.0786 - val_policy_loss: 1.1835 - val_value_loss: 0.8379 - lr: 0.0100
Epoch 2/50
232/232 [==============================] - 1s 5ms/step - loss: 2.2167 - policy_loss: 1.2854 - value_loss: 0.8690 - val_loss: 2.1294 - val_policy_loss: 1.2313 - val_value_loss: 0.8324 - lr: 0.0100
Epoch 3/50
232/232 [==============================] - 1s 5ms/step - loss: 2.2178 - policy_loss: 1.2808 - value_loss: 0.8688 - val_loss: 2.1134 - val_policy_loss: 1.2111 - val_value_loss: 0.8323 - lr: 0.0100
Epoch 4/50
232/232 [==============================] - 1s 5ms/step - loss: 2.2104 - policy_loss: 1.2711 - value_loss: 0.8689 - val_loss: 2.1105 - val_policy_loss: 1.2057 - val_value_loss: 0.8334 - lr: 0.0100
Epoch 5/50
232/232 [==============================] - 1s 5ms/step - loss: 2.2156 - policy_loss: 1.2749 - value_loss: 0.86

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 5-th round: 643.0260248184204 seconds
Epoch 1/50
279/279 [==============================] - 3s 6ms/step - loss: 2.2070 - policy_loss: 1.2833 - value_loss: 0.8565 - val_loss: 1.9432 - val_policy_loss: 1.1503 - val_value_loss: 0.7202 - lr: 0.0100
Epoch 2/50
279/279 [==============================] - 1s 5ms/step - loss: 2.1981 - policy_loss: 1.2671 - value_loss: 0.8565 - val_loss: 1.9975 - val_policy_loss: 1.2003 - val_value_loss: 0.7208 - lr: 0.0100
Epoch 3/50
279/279 [==============================] - 1s 5ms/step - loss: 2.1948 - policy_loss: 1.2615 - value_loss: 0.8567 - val_loss: 1.9479 - val_policy_loss: 1.1504 - val_value_loss: 0.7204 - lr: 0.0100
Epoch 4/50
279/279 [==============================] - 1s 5ms/step - loss: 2.1952 - policy_loss: 1.2605 - value_loss: 0.8571 - val_loss: 1.9164 - val_policy_loss: 1.1188 - val_value_loss: 0.7204 - lr: 0.0100
Epoch 5/50
279/279 [==============================] - 1s 5ms/step - loss: 2.1948 - policy_loss: 1.2604 - value_loss: 0.85

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 6-th round: 665.7591693401337 seconds
Epoch 1/50
327/327 [==============================] - 3s 6ms/step - loss: 2.1698 - policy_loss: 1.2529 - value_loss: 0.8373 - val_loss: 1.9685 - val_policy_loss: 1.1553 - val_value_loss: 0.7313 - lr: 0.0100
Epoch 2/50
327/327 [==============================] - 2s 5ms/step - loss: 2.1645 - policy_loss: 1.2449 - value_loss: 0.8373 - val_loss: 1.9553 - val_policy_loss: 1.1432 - val_value_loss: 0.7315 - lr: 0.0100
Epoch 3/50
327/327 [==============================] - 2s 5ms/step - loss: 2.1584 - policy_loss: 1.2406 - value_loss: 0.8376 - val_loss: 2.0136 - val_policy_loss: 1.2026 - val_value_loss: 0.7313 - lr: 0.0100
Epoch 4/50
327/327 [==============================] - 2s 5ms/step - loss: 2.1653 - policy_loss: 1.2460 - value_loss: 0.8375 - val_loss: 2.2653 - val_policy_loss: 1.4546 - val_value_loss: 0.7308 - lr: 0.0100
Epoch 5/50
327/327 [==============================] - 2s 5ms/step - loss: 2.1552 - policy_loss: 1.2386 - value_loss: 0.83

327/327 [==============================] - 2s 5ms/step - loss: 2.0283 - policy_loss: 1.1615 - value_loss: 0.8367 - val_loss: 1.8103 - val_policy_loss: 1.0494 - val_value_loss: 0.7309 - lr: 1.2907e-04
Epoch 41/50
327/327 [==============================] - 2s 5ms/step - loss: 2.0265 - policy_loss: 1.1598 - value_loss: 0.8367 - val_loss: 1.8107 - val_policy_loss: 1.0499 - val_value_loss: 0.7309 - lr: 1.0000e-04
Epoch 42/50
327/327 [==============================] - 2s 5ms/step - loss: 2.0263 - policy_loss: 1.1597 - value_loss: 0.8367 - val_loss: 1.8106 - val_policy_loss: 1.0499 - val_value_loss: 0.7309 - lr: 1.0000e-04
Epoch 43/50
327/327 [==============================] - 2s 5ms/step - loss: 2.0261 - policy_loss: 1.1597 - value_loss: 0.8367 - val_loss: 1.8110 - val_policy_loss: 1.0504 - val_value_loss: 0.7309 - lr: 1.0000e-04
Epoch 44/50
327/327 [==============================] - 2s 5ms/step - loss: 2.0264 - policy_loss: 1.1600 - value_loss: 0.8367 - val_loss: 1.8102 - val_policy_loss: 1

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 7-th round: 645.1003878116608 seconds
Epoch 1/50
378/378 [==============================] - 3s 5ms/step - loss: 2.0946 - policy_loss: 1.2355 - value_loss: 0.8164 - val_loss: 1.6840 - val_policy_loss: 1.0851 - val_value_loss: 0.5483 - lr: 0.0100
Epoch 2/50
378/378 [==============================] - 2s 5ms/step - loss: 2.0848 - policy_loss: 1.2151 - value_loss: 0.8163 - val_loss: 1.7017 - val_policy_loss: 1.0972 - val_value_loss: 0.5486 - lr: 0.0100
Epoch 3/50
378/378 [==============================] - 2s 5ms/step - loss: 2.0928 - policy_loss: 1.2180 - value_loss: 0.8161 - val_loss: 1.8374 - val_policy_loss: 1.2283 - val_value_loss: 0.5481 - lr: 0.0100
Epoch 4/50
378/378 [==============================] - 2s 5ms/step - loss: 2.0985 - policy_loss: 1.2189 - value_loss: 0.8163 - val_loss: 1.7249 - val_policy_loss: 1.1127 - val_value_loss: 0.5481 - lr: 0.0100
Epoch 5/50
378/378 [==============================] - 2s 5ms/step - loss: 2.0919 - policy_loss: 1.2112 - value_loss: 0.81

378/378 [==============================] - 2s 5ms/step - loss: 1.9862 - policy_loss: 1.1441 - value_loss: 0.8158 - val_loss: 1.5692 - val_policy_loss: 0.9940 - val_value_loss: 0.5489 - lr: 1.2907e-04
Epoch 41/50
378/378 [==============================] - 2s 5ms/step - loss: 1.9848 - policy_loss: 1.1428 - value_loss: 0.8158 - val_loss: 1.5694 - val_policy_loss: 0.9944 - val_value_loss: 0.5488 - lr: 1.0000e-04
Epoch 42/50
378/378 [==============================] - 2s 5ms/step - loss: 1.9852 - policy_loss: 1.1433 - value_loss: 0.8158 - val_loss: 1.5695 - val_policy_loss: 0.9945 - val_value_loss: 0.5488 - lr: 1.0000e-04
Epoch 43/50
378/378 [==============================] - 2s 5ms/step - loss: 1.9853 - policy_loss: 1.1435 - value_loss: 0.8158 - val_loss: 1.5695 - val_policy_loss: 0.9946 - val_value_loss: 0.5489 - lr: 1.0000e-04
Epoch 44/50
378/378 [==============================] - 2s 5ms/step - loss: 1.9853 - policy_loss: 1.1435 - value_loss: 0.8158 - val_loss: 1.5683 - val_policy_loss: 0

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 8-th round: 630.6430208683014 seconds
Epoch 1/50
430/430 [==============================] - 4s 5ms/step - loss: 2.0330 - policy_loss: 1.2119 - value_loss: 0.7830 - val_loss: 1.6210 - val_policy_loss: 1.0590 - val_value_loss: 0.5164 - lr: 0.0100
Epoch 2/50
430/430 [==============================] - 2s 5ms/step - loss: 2.0307 - policy_loss: 1.1986 - value_loss: 0.7829 - val_loss: 1.6067 - val_policy_loss: 1.0386 - val_value_loss: 0.5158 - lr: 0.0100
Epoch 3/50
430/430 [==============================] - 2s 5ms/step - loss: 2.0329 - policy_loss: 1.1955 - value_loss: 0.7829 - val_loss: 1.5893 - val_policy_loss: 1.0179 - val_value_loss: 0.5152 - lr: 0.0100
Epoch 4/50
430/430 [==============================] - 2s 5ms/step - loss: 2.0295 - policy_loss: 1.1902 - value_loss: 0.7828 - val_loss: 1.6494 - val_policy_loss: 1.0739 - val_value_loss: 0.5166 - lr: 0.0100
Epoch 5/50
430/430 [==============================] - 2s 5ms/step - loss: 2.0387 - policy_loss: 1.1958 - value_loss: 0.78

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 9-th round: 620.5076069831848 seconds
Epoch 1/50
485/485 [==============================] - 4s 6ms/step - loss: 1.9939 - policy_loss: 1.1827 - value_loss: 0.7522 - val_loss: 1.5351 - val_policy_loss: 1.0463 - val_value_loss: 0.4277 - lr: 0.0100
Epoch 2/50
485/485 [==============================] - 3s 5ms/step - loss: 1.9956 - policy_loss: 1.1805 - value_loss: 0.7523 - val_loss: 1.4590 - val_policy_loss: 0.9671 - val_value_loss: 0.4286 - lr: 0.0100
Epoch 3/50
485/485 [==============================] - 3s 6ms/step - loss: 1.9911 - policy_loss: 1.1761 - value_loss: 0.7524 - val_loss: 1.4672 - val_policy_loss: 0.9793 - val_value_loss: 0.4243 - lr: 0.0100
Epoch 4/50
485/485 [==============================] - 3s 6ms/step - loss: 1.9923 - policy_loss: 1.1768 - value_loss: 0.7522 - val_loss: 1.4612 - val_policy_loss: 0.9687 - val_value_loss: 0.4290 - lr: 0.0100
Epoch 5/50
485/485 [==============================] - 3s 5ms/step - loss: 1.9945 - policy_loss: 1.1784 - value_loss: 0.75

485/485 [==============================] - 3s 5ms/step - loss: 1.8855 - policy_loss: 1.1100 - value_loss: 0.7516 - val_loss: 1.3759 - val_policy_loss: 0.9265 - val_value_loss: 0.4257 - lr: 1.2907e-04
Epoch 41/50
485/485 [==============================] - 3s 5ms/step - loss: 1.8855 - policy_loss: 1.1101 - value_loss: 0.7516 - val_loss: 1.3757 - val_policy_loss: 0.9263 - val_value_loss: 0.4256 - lr: 1.0000e-04
Epoch 42/50
485/485 [==============================] - 3s 5ms/step - loss: 1.8855 - policy_loss: 1.1103 - value_loss: 0.7516 - val_loss: 1.3763 - val_policy_loss: 0.9271 - val_value_loss: 0.4256 - lr: 1.0000e-04
Epoch 43/50
485/485 [==============================] - 3s 5ms/step - loss: 1.8853 - policy_loss: 1.1101 - value_loss: 0.7516 - val_loss: 1.3752 - val_policy_loss: 0.9262 - val_value_loss: 0.4256 - lr: 1.0000e-04
Epoch 44/50
485/485 [==============================] - 3s 6ms/step - loss: 1.8851 - policy_loss: 1.1101 - value_loss: 0.7516 - val_loss: 1.3754 - val_policy_loss: 0

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 10-th round: 670.926602602005 seconds
Epoch 1/50
540/540 [==============================] - 4s 6ms/step - loss: 1.9277 - policy_loss: 1.1739 - value_loss: 0.7189 - val_loss: 1.6057 - val_policy_loss: 1.1815 - val_value_loss: 0.3822 - lr: 0.0100
Epoch 2/50
540/540 [==============================] - 3s 5ms/step - loss: 1.9266 - policy_loss: 1.1615 - value_loss: 0.7189 - val_loss: 1.4032 - val_policy_loss: 0.9700 - val_value_loss: 0.3841 - lr: 0.0100
Epoch 3/50
540/540 [==============================] - 3s 5ms/step - loss: 1.9237 - policy_loss: 1.1540 - value_loss: 0.7190 - val_loss: 1.4116 - val_policy_loss: 0.9797 - val_value_loss: 0.3799 - lr: 0.0100
Epoch 4/50
540/540 [==============================] - 3s 5ms/step - loss: 1.9294 - policy_loss: 1.1566 - value_loss: 0.7192 - val_loss: 1.4448 - val_policy_loss: 1.0056 - val_value_loss: 0.3836 - lr: 0.0100
Epoch 5/50
540/540 [==============================] - 3s 5ms/step - loss: 1.9321 - policy_loss: 1.1565 - value_loss: 0.71

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 11-th round: 598.0088579654694 seconds
Epoch 1/50
598/598 [==============================] - 5s 6ms/step - loss: 1.8878 - policy_loss: 1.1486 - value_loss: 0.6862 - val_loss: 1.2413 - val_policy_loss: 0.9055 - val_value_loss: 0.2799 - lr: 0.0100
Epoch 2/50
598/598 [==============================] - 3s 5ms/step - loss: 1.8908 - policy_loss: 1.1470 - value_loss: 0.6857 - val_loss: 1.2604 - val_policy_loss: 0.9169 - val_value_loss: 0.2844 - lr: 0.0100
Epoch 3/50
598/598 [==============================] - 3s 5ms/step - loss: 1.8872 - policy_loss: 1.1419 - value_loss: 0.6862 - val_loss: 1.2560 - val_policy_loss: 0.9132 - val_value_loss: 0.2833 - lr: 0.0100
Epoch 4/50
598/598 [==============================] - 3s 5ms/step - loss: 1.8843 - policy_loss: 1.1395 - value_loss: 0.6860 - val_loss: 1.3301 - val_policy_loss: 0.9890 - val_value_loss: 0.2816 - lr: 0.0100
Epoch 5/50
598/598 [==============================] - 3s 5ms/step - loss: 1.8862 - policy_loss: 1.1407 - value_loss: 0.6

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 12-th round: 618.6106300354004 seconds
Epoch 1/50
656/656 [==============================] - 5s 6ms/step - loss: 1.8383 - policy_loss: 1.1302 - value_loss: 0.6504 - val_loss: 1.3436 - val_policy_loss: 0.9919 - val_value_loss: 0.2937 - lr: 0.0100
Epoch 2/50
656/656 [==============================] - 4s 6ms/step - loss: 1.8421 - policy_loss: 1.1302 - value_loss: 0.6502 - val_loss: 1.3401 - val_policy_loss: 0.9859 - val_value_loss: 0.2941 - lr: 0.0100
Epoch 3/50
656/656 [==============================] - 4s 6ms/step - loss: 1.8533 - policy_loss: 1.1363 - value_loss: 0.6503 - val_loss: 1.3309 - val_policy_loss: 0.9731 - val_value_loss: 0.2945 - lr: 0.0100
Epoch 4/50
656/656 [==============================] - 4s 6ms/step - loss: 1.8426 - policy_loss: 1.1282 - value_loss: 0.6502 - val_loss: 1.3720 - val_policy_loss: 1.0106 - val_value_loss: 0.2997 - lr: 0.0100
Epoch 5/50
656/656 [==============================] - 4s 6ms/step - loss: 1.8469 - policy_loss: 1.1316 - value_loss: 0.6

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 13-th round: 613.355751991272 seconds
Epoch 1/50
715/715 [==============================] - 6s 6ms/step - loss: 1.7960 - policy_loss: 1.1149 - value_loss: 0.6201 - val_loss: 1.2495 - val_policy_loss: 0.9392 - val_value_loss: 0.2501 - lr: 0.0100
Epoch 2/50
715/715 [==============================] - 4s 6ms/step - loss: 1.7957 - policy_loss: 1.1142 - value_loss: 0.6203 - val_loss: 1.2335 - val_policy_loss: 0.9213 - val_value_loss: 0.2502 - lr: 0.0100
Epoch 3/50
715/715 [==============================] - 4s 6ms/step - loss: 1.7950 - policy_loss: 1.1131 - value_loss: 0.6203 - val_loss: 1.3011 - val_policy_loss: 0.9820 - val_value_loss: 0.2582 - lr: 0.0100
Epoch 4/50
715/715 [==============================] - 4s 6ms/step - loss: 1.7914 - policy_loss: 1.1109 - value_loss: 0.6203 - val_loss: 1.3608 - val_policy_loss: 1.0491 - val_value_loss: 0.2519 - lr: 0.0100
Epoch 5/50
715/715 [==============================] - 4s 6ms/step - loss: 1.7941 - policy_loss: 1.1136 - value_loss: 0.62

715/715 [==============================] - 4s 6ms/step - loss: 1.6893 - policy_loss: 1.0490 - value_loss: 0.6196 - val_loss: 1.1639 - val_policy_loss: 0.8911 - val_value_loss: 0.2521 - lr: 1.2907e-04
Epoch 41/50
715/715 [==============================] - 4s 6ms/step - loss: 1.6887 - policy_loss: 1.0485 - value_loss: 0.6196 - val_loss: 1.1623 - val_policy_loss: 0.8897 - val_value_loss: 0.2521 - lr: 1.0000e-04
Epoch 42/50
715/715 [==============================] - 4s 6ms/step - loss: 1.6883 - policy_loss: 1.0482 - value_loss: 0.6196 - val_loss: 1.1605 - val_policy_loss: 0.8880 - val_value_loss: 0.2521 - lr: 1.0000e-04
Epoch 43/50
715/715 [==============================] - 4s 6ms/step - loss: 1.6879 - policy_loss: 1.0479 - value_loss: 0.6196 - val_loss: 1.1614 - val_policy_loss: 0.8889 - val_value_loss: 0.2521 - lr: 1.0000e-04
Epoch 44/50
715/715 [==============================] - 4s 6ms/step - loss: 1.6884 - policy_loss: 1.0486 - value_loss: 0.6196 - val_loss: 1.1608 - val_policy_loss: 0

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 14-th round: 638.3561487197876 seconds
Epoch 1/50
775/775 [==============================] - 6s 6ms/step - loss: 1.7406 - policy_loss: 1.1145 - value_loss: 0.5923 - val_loss: 1.1625 - val_policy_loss: 0.9207 - val_value_loss: 0.2008 - lr: 0.0100
Epoch 2/50
775/775 [==============================] - 5s 6ms/step - loss: 1.7358 - policy_loss: 1.0991 - value_loss: 0.5921 - val_loss: 1.1546 - val_policy_loss: 0.9108 - val_value_loss: 0.1950 - lr: 0.0100
Epoch 3/50
775/775 [==============================] - 5s 6ms/step - loss: 1.7367 - policy_loss: 1.0946 - value_loss: 0.5925 - val_loss: 1.1932 - val_policy_loss: 0.9444 - val_value_loss: 0.1974 - lr: 0.0100
Epoch 4/50
775/775 [==============================] - 4s 6ms/step - loss: 1.7386 - policy_loss: 1.0940 - value_loss: 0.5925 - val_loss: 1.1971 - val_policy_loss: 0.9463 - val_value_loss: 0.1977 - lr: 0.0100
Epoch 5/50
775/775 [==============================] - 5s 6ms/step - loss: 1.7435 - policy_loss: 1.0968 - value_loss: 0.5

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 15-th round: 648.5324561595917 seconds
Epoch 1/50
836/836 [==============================] - 6s 6ms/step - loss: 1.7065 - policy_loss: 1.0865 - value_loss: 0.5636 - val_loss: 1.1327 - val_policy_loss: 0.8927 - val_value_loss: 0.1828 - lr: 0.0100
Epoch 2/50
836/836 [==============================] - 5s 6ms/step - loss: 1.7040 - policy_loss: 1.0838 - value_loss: 0.5637 - val_loss: 1.1288 - val_policy_loss: 0.8931 - val_value_loss: 0.1796 - lr: 0.0100
Epoch 3/50
836/836 [==============================] - 5s 6ms/step - loss: 1.7060 - policy_loss: 1.0854 - value_loss: 0.5635 - val_loss: 1.1362 - val_policy_loss: 0.9006 - val_value_loss: 0.1782 - lr: 0.0100
Epoch 4/50
836/836 [==============================] - 5s 6ms/step - loss: 1.7066 - policy_loss: 1.0857 - value_loss: 0.5633 - val_loss: 1.1728 - val_policy_loss: 0.9384 - val_value_loss: 0.1768 - lr: 0.0100
Epoch 5/50
836/836 [==============================] - 5s 6ms/step - loss: 1.7057 - policy_loss: 1.0851 - value_loss: 0.5

836/836 [==============================] - 5s 6ms/step - loss: 1.6072 - policy_loss: 1.0252 - value_loss: 0.5630 - val_loss: 1.0535 - val_policy_loss: 0.8564 - val_value_loss: 0.1783 - lr: 1.2907e-04
Epoch 41/50
836/836 [==============================] - 5s 6ms/step - loss: 1.6070 - policy_loss: 1.0252 - value_loss: 0.5630 - val_loss: 1.0537 - val_policy_loss: 0.8566 - val_value_loss: 0.1783 - lr: 1.0000e-04
Epoch 42/50
836/836 [==============================] - 5s 6ms/step - loss: 1.6065 - policy_loss: 1.0247 - value_loss: 0.5630 - val_loss: 1.0532 - val_policy_loss: 0.8561 - val_value_loss: 0.1784 - lr: 1.0000e-04
Epoch 43/50
836/836 [==============================] - 5s 6ms/step - loss: 1.6064 - policy_loss: 1.0247 - value_loss: 0.5630 - val_loss: 1.0525 - val_policy_loss: 0.8556 - val_value_loss: 0.1784 - lr: 1.0000e-04
Epoch 44/50
836/836 [==============================] - 5s 6ms/step - loss: 1.6067 - policy_loss: 1.0252 - value_loss: 0.5630 - val_loss: 1.0539 - val_policy_loss: 0

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 16-th round: 651.0239140987396 seconds
Epoch 1/50
898/898 [==============================] - 7s 6ms/step - loss: 1.6636 - policy_loss: 1.0938 - value_loss: 0.5373 - val_loss: 1.0996 - val_policy_loss: 0.9126 - val_value_loss: 0.1476 - lr: 0.0100
Epoch 2/50
898/898 [==============================] - 5s 6ms/step - loss: 1.6525 - policy_loss: 1.0719 - value_loss: 0.5376 - val_loss: 1.0629 - val_policy_loss: 0.8672 - val_value_loss: 0.1502 - lr: 0.0100
Epoch 3/50
898/898 [==============================] - 6s 6ms/step - loss: 1.6570 - policy_loss: 1.0720 - value_loss: 0.5374 - val_loss: 1.0806 - val_policy_loss: 0.8786 - val_value_loss: 0.1522 - lr: 0.0100
Epoch 4/50
898/898 [==============================] - 6s 6ms/step - loss: 1.6597 - policy_loss: 1.0715 - value_loss: 0.5373 - val_loss: 1.1084 - val_policy_loss: 0.9085 - val_value_loss: 0.1475 - lr: 0.0100
Epoch 5/50
898/898 [==============================] - 6s 7ms/step - loss: 1.6621 - policy_loss: 1.0718 - value_loss: 0.5

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 17-th round: 666.3576037883759 seconds
Epoch 1/50
960/960 [==============================] - 8s 7ms/step - loss: 1.6282 - policy_loss: 1.0661 - value_loss: 0.5125 - val_loss: 1.0689 - val_policy_loss: 0.8944 - val_value_loss: 0.1222 - lr: 0.0100
Epoch 2/50
960/960 [==============================] - 6s 6ms/step - loss: 1.6261 - policy_loss: 1.0613 - value_loss: 0.5124 - val_loss: 1.0336 - val_policy_loss: 0.8601 - val_value_loss: 0.1211 - lr: 0.0100
Epoch 3/50
960/960 [==============================] - 6s 6ms/step - loss: 1.6283 - policy_loss: 1.0624 - value_loss: 0.5123 - val_loss: 1.0252 - val_policy_loss: 0.8478 - val_value_loss: 0.1236 - lr: 0.0100
Epoch 4/50
960/960 [==============================] - 6s 6ms/step - loss: 1.6276 - policy_loss: 1.0614 - value_loss: 0.5124 - val_loss: 1.0493 - val_policy_loss: 0.8641 - val_value_loss: 0.1304 - lr: 0.0100
Epoch 5/50
960/960 [==============================] - 6s 6ms/step - loss: 1.6311 - policy_loss: 1.0635 - value_loss: 0.5

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 18-th round: 711.2861940860748 seconds
Epoch 1/50
1023/1023 [==============================] - 9s 7ms/step - loss: 1.5951 - policy_loss: 1.0526 - value_loss: 0.4889 - val_loss: 1.0133 - val_policy_loss: 0.8515 - val_value_loss: 0.1082 - lr: 0.0100
Epoch 2/50
1023/1023 [==============================] - 7s 7ms/step - loss: 1.5929 - policy_loss: 1.0501 - value_loss: 0.4891 - val_loss: 1.0161 - val_policy_loss: 0.8533 - val_value_loss: 0.1090 - lr: 0.0100
Epoch 3/50
1023/1023 [==============================] - 7s 7ms/step - loss: 1.5956 - policy_loss: 1.0521 - value_loss: 0.4889 - val_loss: 1.0297 - val_policy_loss: 0.8627 - val_value_loss: 0.1121 - lr: 0.0100
Epoch 4/50
1023/1023 [==============================] - 7s 7ms/step - loss: 1.5951 - policy_loss: 1.0513 - value_loss: 0.4890 - val_loss: 1.0261 - val_policy_loss: 0.8569 - val_value_loss: 0.1134 - lr: 0.0100
Epoch 5/50
1023/1023 [==============================] - 7s 7ms/step - loss: 1.5948 - policy_loss: 1.0509 - value

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 19-th round: 666.9678149223328 seconds
Epoch 1/50
1086/1086 [==============================] - 8s 6ms/step - loss: 1.5631 - policy_loss: 1.0428 - value_loss: 0.4665 - val_loss: 1.0079 - val_policy_loss: 0.8472 - val_value_loss: 0.1049 - lr: 0.0100
Epoch 2/50
1086/1086 [==============================] - 7s 6ms/step - loss: 1.5617 - policy_loss: 1.0404 - value_loss: 0.4667 - val_loss: 1.0130 - val_policy_loss: 0.8563 - val_value_loss: 0.1017 - lr: 0.0100
Epoch 3/50
1086/1086 [==============================] - 6s 6ms/step - loss: 1.5628 - policy_loss: 1.0415 - value_loss: 0.4664 - val_loss: 1.0175 - val_policy_loss: 0.8616 - val_value_loss: 0.1005 - lr: 0.0100
Epoch 4/50
1086/1086 [==============================] - 6s 6ms/step - loss: 1.5610 - policy_loss: 1.0399 - value_loss: 0.4666 - val_loss: 1.0107 - val_policy_loss: 0.8566 - val_value_loss: 0.1002 - lr: 0.0100
Epoch 5/50
1086/1086 [==============================] - 6s 6ms/step - loss: 1.5644 - policy_loss: 1.0431 - value

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 20-th round: 609.1898717880249 seconds
Epoch 1/50
1149/1149 [==============================] - 9s 6ms/step - loss: 1.5333 - policy_loss: 1.0326 - value_loss: 0.4470 - val_loss: 0.9936 - val_policy_loss: 0.8567 - val_value_loss: 0.0819 - lr: 0.0100
Epoch 2/50
1149/1149 [==============================] - 7s 6ms/step - loss: 1.5341 - policy_loss: 1.0326 - value_loss: 0.4469 - val_loss: 1.1519 - val_policy_loss: 1.0140 - val_value_loss: 0.0829 - lr: 0.0100
Epoch 3/50
1149/1149 [==============================] - 7s 6ms/step - loss: 1.5325 - policy_loss: 1.0311 - value_loss: 0.4470 - val_loss: 1.0290 - val_policy_loss: 0.8871 - val_value_loss: 0.0882 - lr: 0.0100
Epoch 4/50
1149/1149 [==============================] - 7s 6ms/step - loss: 1.5333 - policy_loss: 1.0323 - value_loss: 0.4469 - val_loss: 1.0208 - val_policy_loss: 0.8794 - val_value_loss: 0.0870 - lr: 0.0100
Epoch 5/50
1149/1149 [==============================] - 7s 6ms/step - loss: 1.5332 - policy_loss: 1.0321 - value

Epoch 40/50
1149/1149 [==============================] - 7s 6ms/step - loss: 1.4376 - policy_loss: 0.9751 - value_loss: 0.4466 - val_loss: 0.9056 - val_policy_loss: 0.8066 - val_value_loss: 0.0832 - lr: 1.2907e-04
Epoch 41/50
1149/1149 [==============================] - 7s 6ms/step - loss: 1.4370 - policy_loss: 0.9746 - value_loss: 0.4466 - val_loss: 0.9059 - val_policy_loss: 0.8071 - val_value_loss: 0.0832 - lr: 1.0000e-04
Epoch 42/50
1149/1149 [==============================] - 7s 6ms/step - loss: 1.4371 - policy_loss: 0.9748 - value_loss: 0.4466 - val_loss: 0.9058 - val_policy_loss: 0.8071 - val_value_loss: 0.0832 - lr: 1.0000e-04
Epoch 43/50
1149/1149 [==============================] - 7s 6ms/step - loss: 1.4372 - policy_loss: 0.9751 - value_loss: 0.4466 - val_loss: 0.9053 - val_policy_loss: 0.8067 - val_value_loss: 0.0832 - lr: 1.0000e-04
Epoch 44/50
1149/1149 [==============================] - 7s 6ms/step - loss: 1.4365 - policy_loss: 0.9744 - value_loss: 0.4466 - val_loss: 0.905

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 21-th round: 636.2205131053925 seconds
Epoch 1/50
1213/1213 [==============================] - 9s 6ms/step - loss: 1.4986 - policy_loss: 1.0395 - value_loss: 0.4285 - val_loss: 1.0730 - val_policy_loss: 0.9597 - val_value_loss: 0.0750 - lr: 0.0100
Epoch 2/50
1213/1213 [==============================] - 7s 6ms/step - loss: 1.4930 - policy_loss: 1.0224 - value_loss: 0.4284 - val_loss: 0.9591 - val_policy_loss: 0.8408 - val_value_loss: 0.0729 - lr: 0.0100
Epoch 3/50
1213/1213 [==============================] - 7s 6ms/step - loss: 1.4976 - policy_loss: 1.0221 - value_loss: 0.4283 - val_loss: 0.9535 - val_policy_loss: 0.8316 - val_value_loss: 0.0738 - lr: 0.0100
Epoch 4/50
1213/1213 [==============================] - 7s 6ms/step - loss: 1.5022 - policy_loss: 1.0242 - value_loss: 0.4284 - val_loss: 0.9591 - val_policy_loss: 0.8338 - val_value_loss: 0.0739 - lr: 0.0100
Epoch 5/50
1213/1213 [==============================] - 7s 6ms/step - loss: 1.5047 - policy_loss: 1.0238 - value

Epoch 40/50
1213/1213 [==============================] - 7s 6ms/step - loss: 1.4128 - policy_loss: 0.9692 - value_loss: 0.4280 - val_loss: 0.8826 - val_policy_loss: 0.7951 - val_value_loss: 0.0720 - lr: 1.2907e-04
Epoch 41/50
1213/1213 [==============================] - 7s 6ms/step - loss: 1.4119 - policy_loss: 0.9685 - value_loss: 0.4279 - val_loss: 0.8818 - val_policy_loss: 0.7944 - val_value_loss: 0.0718 - lr: 1.0000e-04
Epoch 42/50
1213/1213 [==============================] - 7s 6ms/step - loss: 1.4118 - policy_loss: 0.9684 - value_loss: 0.4280 - val_loss: 0.8814 - val_policy_loss: 0.7942 - val_value_loss: 0.0719 - lr: 1.0000e-04
Epoch 43/50
1213/1213 [==============================] - 7s 6ms/step - loss: 1.4115 - policy_loss: 0.9682 - value_loss: 0.4280 - val_loss: 0.8821 - val_policy_loss: 0.7949 - val_value_loss: 0.0720 - lr: 1.0000e-04
Epoch 44/50
1213/1213 [==============================] - 7s 6ms/step - loss: 1.4114 - policy_loss: 0.9682 - value_loss: 0.4280 - val_loss: 0.881

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 22-th round: 622.4139795303345 seconds
Epoch 1/50
1276/1276 [==============================] - 9s 6ms/step - loss: 1.4678 - policy_loss: 1.0284 - value_loss: 0.4109 - val_loss: 0.9609 - val_policy_loss: 0.8630 - val_value_loss: 0.0619 - lr: 0.0100
Epoch 2/50
1276/1276 [==============================] - 8s 6ms/step - loss: 1.4652 - policy_loss: 1.0143 - value_loss: 0.4108 - val_loss: 0.9875 - val_policy_loss: 0.8824 - val_value_loss: 0.0623 - lr: 0.0100
Epoch 3/50
1276/1276 [==============================] - 8s 6ms/step - loss: 1.4705 - policy_loss: 1.0145 - value_loss: 0.4107 - val_loss: 0.9255 - val_policy_loss: 0.8179 - val_value_loss: 0.0605 - lr: 0.0100
Epoch 4/50
1276/1276 [==============================] - 8s 6ms/step - loss: 1.4732 - policy_loss: 1.0147 - value_loss: 0.4107 - val_loss: 0.9341 - val_policy_loss: 0.8236 - val_value_loss: 0.0616 - lr: 0.0100
Epoch 5/50
1276/1276 [==============================] - 8s 6ms/step - loss: 1.4745 - policy_loss: 1.0152 - value

Epoch 40/50
1276/1276 [==============================] - 8s 6ms/step - loss: 1.3869 - policy_loss: 0.9616 - value_loss: 0.4104 - val_loss: 0.8677 - val_policy_loss: 0.7926 - val_value_loss: 0.0602 - lr: 1.2907e-04
Epoch 41/50
1276/1276 [==============================] - 8s 6ms/step - loss: 1.3871 - policy_loss: 0.9619 - value_loss: 0.4104 - val_loss: 0.8676 - val_policy_loss: 0.7926 - val_value_loss: 0.0602 - lr: 1.0000e-04
Epoch 42/50
1276/1276 [==============================] - 8s 6ms/step - loss: 1.3867 - policy_loss: 0.9616 - value_loss: 0.4104 - val_loss: 0.8669 - val_policy_loss: 0.7920 - val_value_loss: 0.0602 - lr: 1.0000e-04
Epoch 43/50
1276/1276 [==============================] - 8s 6ms/step - loss: 1.3867 - policy_loss: 0.9617 - value_loss: 0.4104 - val_loss: 0.8670 - val_policy_loss: 0.7924 - val_value_loss: 0.0601 - lr: 1.0000e-04
Epoch 44/50
1276/1276 [==============================] - 8s 6ms/step - loss: 1.3860 - policy_loss: 0.9611 - value_loss: 0.4104 - val_loss: 0.866

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 23-th round: 616.5221478939056 seconds
Epoch 1/50
1340/1340 [==============================] - 10s 7ms/step - loss: 1.4438 - policy_loss: 1.0212 - value_loss: 0.3948 - val_loss: 0.9475 - val_policy_loss: 0.8515 - val_value_loss: 0.0607 - lr: 0.0100
Epoch 2/50
1340/1340 [==============================] - 9s 6ms/step - loss: 1.4416 - policy_loss: 1.0078 - value_loss: 0.3947 - val_loss: 0.9479 - val_policy_loss: 0.8435 - val_value_loss: 0.0622 - lr: 0.0100
Epoch 3/50
1340/1340 [==============================] - 9s 6ms/step - loss: 1.4440 - policy_loss: 1.0052 - value_loss: 0.3948 - val_loss: 0.9563 - val_policy_loss: 0.8430 - val_value_loss: 0.0683 - lr: 0.0100
Epoch 4/50
1340/1340 [==============================] - 9s 6ms/step - loss: 1.4461 - policy_loss: 1.0059 - value_loss: 0.3947 - val_loss: 0.9366 - val_policy_loss: 0.8272 - val_value_loss: 0.0634 - lr: 0.0100
Epoch 5/50
1340/1340 [==============================] - 9s 6ms/step - loss: 1.4498 - policy_loss: 1.0076 - valu

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 24-th round: 575.603353023529 seconds
Epoch 1/50
1404/1404 [==============================] - 10s 6ms/step - loss: 1.4262 - policy_loss: 0.9999 - value_loss: 0.3789 - val_loss: 0.9484 - val_policy_loss: 0.8437 - val_value_loss: 0.0570 - lr: 0.0100
Epoch 2/50
1404/1404 [==============================] - 9s 6ms/step - loss: 1.4268 - policy_loss: 0.9993 - value_loss: 0.3791 - val_loss: 0.9328 - val_policy_loss: 0.8267 - val_value_loss: 0.0577 - lr: 0.0100
Epoch 3/50
1404/1404 [==============================] - 8s 6ms/step - loss: 1.4258 - policy_loss: 0.9985 - value_loss: 0.3790 - val_loss: 0.9121 - val_policy_loss: 0.8040 - val_value_loss: 0.0607 - lr: 0.0100
Epoch 4/50
1404/1404 [==============================] - 9s 6ms/step - loss: 1.4280 - policy_loss: 1.0008 - value_loss: 0.3791 - val_loss: 0.9628 - val_policy_loss: 0.8546 - val_value_loss: 0.0601 - lr: 0.0100
Epoch 5/50
1404/1404 [==============================] - 8s 6ms/step - loss: 1.4266 - policy_loss: 0.9992 - value

Epoch 40/50
1404/1404 [==============================] - 8s 6ms/step - loss: 1.3405 - policy_loss: 0.9477 - value_loss: 0.3786 - val_loss: 0.8475 - val_policy_loss: 0.7752 - val_value_loss: 0.0583 - lr: 1.2907e-04
Epoch 41/50
1404/1404 [==============================] - 8s 6ms/step - loss: 1.3400 - policy_loss: 0.9474 - value_loss: 0.3786 - val_loss: 0.8472 - val_policy_loss: 0.7749 - val_value_loss: 0.0583 - lr: 1.0000e-04
Epoch 42/50
1404/1404 [==============================] - 8s 6ms/step - loss: 1.3398 - policy_loss: 0.9472 - value_loss: 0.3786 - val_loss: 0.8464 - val_policy_loss: 0.7741 - val_value_loss: 0.0584 - lr: 1.0000e-04
Epoch 43/50
1404/1404 [==============================] - 9s 6ms/step - loss: 1.3397 - policy_loss: 0.9472 - value_loss: 0.3786 - val_loss: 0.8463 - val_policy_loss: 0.7741 - val_value_loss: 0.0584 - lr: 1.0000e-04
Epoch 44/50
1404/1404 [==============================] - 8s 6ms/step - loss: 1.3399 - policy_loss: 0.9475 - value_loss: 0.3786 - val_loss: 0.846

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 25-th round: 622.489828824997 seconds
Epoch 1/50
1468/1468 [==============================] - 11s 7ms/step - loss: 1.3986 - policy_loss: 1.0060 - value_loss: 0.3657 - val_loss: 0.9107 - val_policy_loss: 0.8258 - val_value_loss: 0.0514 - lr: 0.0100
Epoch 2/50
1468/1468 [==============================] - 10s 7ms/step - loss: 1.3971 - policy_loss: 0.9931 - value_loss: 0.3656 - val_loss: 0.8752 - val_policy_loss: 0.7846 - val_value_loss: 0.0496 - lr: 0.0100
Epoch 3/50
1468/1468 [==============================] - 10s 7ms/step - loss: 1.4010 - policy_loss: 0.9927 - value_loss: 0.3655 - val_loss: 0.8931 - val_policy_loss: 0.8009 - val_value_loss: 0.0462 - lr: 0.0100
Epoch 4/50
1468/1468 [==============================] - 10s 7ms/step - loss: 1.4049 - policy_loss: 0.9929 - value_loss: 0.3656 - val_loss: 0.8938 - val_policy_loss: 0.7999 - val_value_loss: 0.0470 - lr: 0.0100
Epoch 5/50
1468/1468 [==============================] - 10s 7ms/step - loss: 1.4066 - policy_loss: 0.9938 - v

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 26-th round: 606.2489750385284 seconds
Epoch 1/50
1532/1532 [==============================] - 11s 6ms/step - loss: 1.3854 - policy_loss: 0.9888 - value_loss: 0.3528 - val_loss: 0.8923 - val_policy_loss: 0.8118 - val_value_loss: 0.0354 - lr: 0.0100
Epoch 2/50
1532/1532 [==============================] - 10s 6ms/step - loss: 1.3860 - policy_loss: 0.9866 - value_loss: 0.3529 - val_loss: 0.9259 - val_policy_loss: 0.8460 - val_value_loss: 0.0337 - lr: 0.0100
Epoch 3/50
1532/1532 [==============================] - 9s 6ms/step - loss: 1.3850 - policy_loss: 0.9850 - value_loss: 0.3529 - val_loss: 0.8820 - val_policy_loss: 0.7994 - val_value_loss: 0.0356 - lr: 0.0100
Epoch 4/50
1532/1532 [==============================] - 9s 6ms/step - loss: 1.3842 - policy_loss: 0.9842 - value_loss: 0.3529 - val_loss: 0.8816 - val_policy_loss: 0.7986 - val_value_loss: 0.0360 - lr: 0.0100
Epoch 5/50
1532/1532 [==============================] - 9s 6ms/step - loss: 1.3855 - policy_loss: 0.9850 - val

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 27-th round: 620.0862600803375 seconds
Epoch 1/50
1597/1597 [==============================] - 12s 7ms/step - loss: 1.3638 - policy_loss: 0.9779 - value_loss: 0.3399 - val_loss: 0.8884 - val_policy_loss: 0.8107 - val_value_loss: 0.0303 - lr: 0.0100
Epoch 2/50
1597/1597 [==============================] - 10s 6ms/step - loss: 1.3679 - policy_loss: 0.9797 - value_loss: 0.3400 - val_loss: 0.9051 - val_policy_loss: 0.8278 - val_value_loss: 0.0300 - lr: 0.0100
Epoch 3/50
1597/1597 [==============================] - 10s 6ms/step - loss: 1.3660 - policy_loss: 0.9785 - value_loss: 0.3401 - val_loss: 0.8922 - val_policy_loss: 0.8147 - val_value_loss: 0.0296 - lr: 0.0100
Epoch 4/50
1597/1597 [==============================] - 10s 6ms/step - loss: 1.3677 - policy_loss: 0.9791 - value_loss: 0.3400 - val_loss: 0.9967 - val_policy_loss: 0.9190 - val_value_loss: 0.0299 - lr: 0.0100
Epoch 5/50
1597/1597 [==============================] - 1077s 675ms/step - loss: 1.3650 - policy_loss: 0.977

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 28-th round: 596.5085966587067 seconds
Epoch 1/50
1661/1661 [==============================] - 12s 7ms/step - loss: 1.3466 - policy_loss: 0.9722 - value_loss: 0.3282 - val_loss: 0.8794 - val_policy_loss: 0.8012 - val_value_loss: 0.0312 - lr: 0.0100
Epoch 2/50
1661/1661 [==============================] - 11s 6ms/step - loss: 1.3486 - policy_loss: 0.9736 - value_loss: 0.3281 - val_loss: 0.8761 - val_policy_loss: 0.7979 - val_value_loss: 0.0303 - lr: 0.0100
Epoch 3/50
1661/1661 [==============================] - 10s 6ms/step - loss: 1.3471 - policy_loss: 0.9722 - value_loss: 0.3281 - val_loss: 0.8846 - val_policy_loss: 0.8074 - val_value_loss: 0.0307 - lr: 0.0100
Epoch 4/50
1661/1661 [==============================] - 10s 6ms/step - loss: 1.3486 - policy_loss: 0.9739 - value_loss: 0.3281 - val_loss: 0.9219 - val_policy_loss: 0.8402 - val_value_loss: 0.0347 - lr: 0.0100
Epoch 5/50
1661/1661 [==============================] - 10s 6ms/step - loss: 1.3493 - policy_loss: 0.9737 - 

1661/1661 [==============================] - 11s 6ms/step - loss: 1.2645 - policy_loss: 0.9238 - value_loss: 0.3277 - val_loss: 0.8167 - val_policy_loss: 0.7718 - val_value_loss: 0.0321 - lr: 1.7249e-04
Epoch 40/50
1661/1661 [==============================] - 11s 6ms/step - loss: 1.2639 - policy_loss: 0.9234 - value_loss: 0.3277 - val_loss: 0.8167 - val_policy_loss: 0.7722 - val_value_loss: 0.0318 - lr: 1.2907e-04
Epoch 41/50
1661/1661 [==============================] - 11s 6ms/step - loss: 1.2636 - policy_loss: 0.9232 - value_loss: 0.3277 - val_loss: 0.8157 - val_policy_loss: 0.7713 - val_value_loss: 0.0318 - lr: 1.0000e-04
Epoch 42/50
1661/1661 [==============================] - 11s 6ms/step - loss: 1.2630 - policy_loss: 0.9227 - value_loss: 0.3277 - val_loss: 0.8162 - val_policy_loss: 0.7718 - val_value_loss: 0.0318 - lr: 1.0000e-04
Epoch 43/50
1661/1661 [==============================] - 10s 6ms/step - loss: 1.2629 - policy_loss: 0.9227 - value_loss: 0.3277 - val_loss: 0.8154 - val

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 29-th round: 612.3500888347626 seconds
Epoch 1/50
1725/1725 [==============================] - 13s 7ms/step - loss: 1.3298 - policy_loss: 0.9859 - value_loss: 0.3172 - val_loss: 0.8500 - val_policy_loss: 0.7900 - val_value_loss: 0.0260 - lr: 0.0100
Epoch 2/50
1725/1725 [==============================] - 12s 7ms/step - loss: 1.3226 - policy_loss: 0.9678 - value_loss: 0.3173 - val_loss: 0.8971 - val_policy_loss: 0.8281 - val_value_loss: 0.0294 - lr: 0.0100
Epoch 3/50
1725/1725 [==============================] - 11s 7ms/step - loss: 1.3264 - policy_loss: 0.9674 - value_loss: 0.3173 - val_loss: 0.8871 - val_policy_loss: 0.8124 - val_value_loss: 0.0317 - lr: 0.0100
Epoch 4/50
1725/1725 [==============================] - 11s 7ms/step - loss: 1.3291 - policy_loss: 0.9678 - value_loss: 0.3173 - val_loss: 0.8500 - val_policy_loss: 0.7802 - val_value_loss: 0.0257 - lr: 0.0100
Epoch 5/50
1725/1725 [==============================] - 11s 7ms/step - loss: 1.3306 - policy_loss: 0.9686 - 

1725/1725 [==============================] - 12s 7ms/step - loss: 1.2503 - policy_loss: 0.9207 - value_loss: 0.3169 - val_loss: 0.7993 - val_policy_loss: 0.7606 - val_value_loss: 0.0261 - lr: 1.7249e-04
Epoch 40/50
1725/1725 [==============================] - 12s 7ms/step - loss: 1.2495 - policy_loss: 0.9200 - value_loss: 0.3169 - val_loss: 0.8001 - val_policy_loss: 0.7615 - val_value_loss: 0.0262 - lr: 1.2907e-04
Epoch 41/50
1725/1725 [==============================] - 12s 7ms/step - loss: 1.2490 - policy_loss: 0.9197 - value_loss: 0.3169 - val_loss: 0.7998 - val_policy_loss: 0.7612 - val_value_loss: 0.0262 - lr: 1.0000e-04
Epoch 42/50
1725/1725 [==============================] - 12s 7ms/step - loss: 1.2489 - policy_loss: 0.9197 - value_loss: 0.3169 - val_loss: 0.7998 - val_policy_loss: 0.7614 - val_value_loss: 0.0261 - lr: 1.0000e-04
Epoch 43/50
1725/1725 [==============================] - 12s 7ms/step - loss: 1.2491 - policy_loss: 0.9199 - value_loss: 0.3169 - val_loss: 0.7989 - val

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 30-th round: 618.0647797584534 seconds
Epoch 1/50
1790/1790 [==============================] - 14s 7ms/step - loss: 1.3086 - policy_loss: 0.9758 - value_loss: 0.3069 - val_loss: 0.9147 - val_policy_loss: 0.8570 - val_value_loss: 0.0245 - lr: 0.0100
Epoch 2/50
1790/1790 [==============================] - 12s 7ms/step - loss: 1.3142 - policy_loss: 0.9681 - value_loss: 0.3068 - val_loss: 0.9288 - val_policy_loss: 0.8587 - val_value_loss: 0.0302 - lr: 0.0100
Epoch 3/50
1790/1790 [==============================] - 12s 7ms/step - loss: 1.3146 - policy_loss: 0.9654 - value_loss: 0.3068 - val_loss: 0.8778 - val_policy_loss: 0.8071 - val_value_loss: 0.0282 - lr: 0.0100
Epoch 4/50
1790/1790 [==============================] - 12s 7ms/step - loss: 1.3142 - policy_loss: 0.9638 - value_loss: 0.3068 - val_loss: 0.9482 - val_policy_loss: 0.8791 - val_value_loss: 0.0259 - lr: 0.0100
Epoch 5/50
1790/1790 [==============================] - 12s 7ms/step - loss: 1.3197 - policy_loss: 0.9672 - 

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 31-th round: 608.1484541893005 seconds
Epoch 1/50
1854/1854 [==============================] - 14s 7ms/step - loss: 1.3006 - policy_loss: 0.9588 - value_loss: 0.2974 - val_loss: 0.9860 - val_policy_loss: 0.9231 - val_value_loss: 0.0191 - lr: 0.0100
Epoch 2/50
1854/1854 [==============================] - 12s 7ms/step - loss: 1.2995 - policy_loss: 0.9578 - value_loss: 0.2974 - val_loss: 0.8503 - val_policy_loss: 0.7876 - val_value_loss: 0.0184 - lr: 0.0100
Epoch 3/50
1854/1854 [==============================] - 12s 7ms/step - loss: 1.3007 - policy_loss: 0.9584 - value_loss: 0.2973 - val_loss: 0.8425 - val_policy_loss: 0.7785 - val_value_loss: 0.0193 - lr: 0.0100
Epoch 4/50
1854/1854 [==============================] - 12s 7ms/step - loss: 1.3004 - policy_loss: 0.9580 - value_loss: 0.2974 - val_loss: 0.8445 - val_policy_loss: 0.7808 - val_value_loss: 0.0181 - lr: 0.0100
Epoch 5/50
1854/1854 [==============================] - 12s 6ms/step - loss: 1.3016 - policy_loss: 0.9594 - 

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


Running time 32-th round: 653.1218447685242 seconds
Epoch 1/50
1919/1919 [==============================] - 15s 7ms/step - loss: 1.2843 - policy_loss: 0.9526 - value_loss: 0.2880 - val_loss: 1.1257 - val_policy_loss: 1.0655 - val_value_loss: 0.0161 - lr: 0.0100
Epoch 2/50
1919/1919 [==============================] - 13s 7ms/step - loss: 1.2870 - policy_loss: 0.9542 - value_loss: 0.2881 - val_loss: 0.8762 - val_policy_loss: 0.8162 - val_value_loss: 0.0146 - lr: 0.0100
Epoch 3/50
1919/1919 [==============================] - 13s 7ms/step - loss: 1.2864 - policy_loss: 0.9536 - value_loss: 0.2881 - val_loss: 0.8451 - val_policy_loss: 0.7862 - val_value_loss: 0.0146 - lr: 0.0100
Epoch 4/50
1919/1919 [==============================] - 13s 7ms/step - loss: 1.2875 - policy_loss: 0.9546 - value_loss: 0.2881 - val_loss: 0.9917 - val_policy_loss: 0.9285 - val_value_loss: 0.0180 - lr: 0.0100
Epoch 5/50
1919/1919 [==============================] - 13s 7ms/step - loss: 1.2873 - policy_loss: 0.9543 - 

1919/1919 [==============================] - 13s 7ms/step - loss: 1.2052 - policy_loss: 0.9055 - value_loss: 0.2877 - val_loss: 0.7955 - val_policy_loss: 0.7679 - val_value_loss: 0.0157 - lr: 1.7249e-04
Epoch 40/50
1919/1919 [==============================] - 13s 7ms/step - loss: 1.2045 - policy_loss: 0.9050 - value_loss: 0.2877 - val_loss: 0.7952 - val_policy_loss: 0.7678 - val_value_loss: 0.0156 - lr: 1.2907e-04
Epoch 41/50
1919/1919 [==============================] - 12s 6ms/step - loss: 1.2047 - policy_loss: 0.9052 - value_loss: 0.2877 - val_loss: 0.7954 - val_policy_loss: 0.7681 - val_value_loss: 0.0157 - lr: 1.0000e-04
Epoch 42/50
1919/1919 [==============================] - 13s 7ms/step - loss: 1.2045 - policy_loss: 0.9052 - value_loss: 0.2877 - val_loss: 0.7952 - val_policy_loss: 0.7679 - val_value_loss: 0.0158 - lr: 1.0000e-04
Epoch 43/50
1919/1919 [==============================] - 13s 7ms/step - loss: 1.2038 - policy_loss: 0.9046 - value_loss: 0.2877 - val_loss: 0.7952 - val