In [1]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '1'
import hashlib
import time
import math
import random
import pickle
import numpy as np
import tensorflow as tf
import multiprocess as mp
from multiprocess.managers import BaseManager, SyncManager
from libs.TicTacToe import TicTacToe
from libs.model import create_az_model, CachedModel
from libs.MCTS import MCTS
from libs.Trainer import Trainer

In [2]:
__name__

'__main__'

In [3]:
n_cores = mp.cpu_count()
print(f"[Number of cores]: {n_cores}")

[Number of cores]: 16


## Tic-Tac-Toe engine

In [4]:
state = np.array([0., 0., -1., -1., 1., -1., 1., 1., 0.])
TicTacToe().get_available_actions(state)

array([1., 1., 0., 0., 0., 0., 0., 0., 1.])

In [5]:
ttt = TicTacToe()

while ttt.status=="Ongoing":

    valid_moves = ttt.next_moves()
    new_board = random.choice(valid_moves)
    ttt.play(new_board)
    print(np.reshape(ttt.board, (3,3)),"\n")
    if len(valid_moves)==0:
        break

print("[Winner]:",ttt.winner)

[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[ 0.  1.  0.]
 [ 0.  0.  0.]
 [-1.  0.  0.]] 

[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [-1.  0.  0.]] 

[[ 0.  1. -1.]
 [ 1.  0.  0.]
 [-1.  0.  0.]] 

[[ 1.  1. -1.]
 [ 1.  0.  0.]
 [-1.  0.  0.]] 

[[ 1.  1. -1.]
 [ 1.  0. -1.]
 [-1.  0.  0.]] 

[[ 1.  1. -1.]
 [ 1.  0. -1.]
 [-1.  0.  1.]] 

[[ 1.  1. -1.]
 [ 1.  0. -1.]
 [-1. -1.  1.]] 

[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]] 

[Winner]: 1


## Create policy and probability model

In [6]:
model = create_az_model()

In [7]:
model.summary()

Model: "tictactoe_model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 9)]                  0         []                            
                                                                                                  
 tf.__operators__.add (TFOp  (None, 9)                    0         ['input_1[0][0]']             
 Lambda)                                                                                          
                                                                                                  
 tf.cast (TFOpLambda)        (None, 9)                    0         ['tf.__operators__.add[0][0]']
                                                                                                  
 tf.one_hot (TFOpLambda)     (None, 9, 3)                 0         ['tf.cast[0][0]'

In [8]:
tf.keras.utils.plot_model(model, show_shapes=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


# Monte Carlo Tree Search

In [9]:
model = create_az_model()

In [10]:
model = CachedModel(model=model)

In [11]:
mcts = MCTS(game=TicTacToe(), n_simulations=100)

In [12]:
state = np.array([0., 0., -1., -1., 1., -1., 1., 1., 0.])

In [13]:
root = mcts.run(model=model, state=state, player=1)

1/1 [==============================] - 0s 25ms/step


In [14]:
root

State:
[ 0.  0. -1. -1.  1. -1.  1.  1.  0.]
Player:1
Value:0.9
Leaf:False
Visits:100
Children:
 -0: prior=0.36958505129133085
 -1: prior=0.27528774453589777
 -8: prior=0.3551272041727714

# Generating the first dataset

In [15]:
STARTING_TEMPERATURE = 1

In [16]:
# speed test on 100 games
start_time = time.time()
trainer = Trainer(game = TicTacToe, mcts = MCTS, model=None)
dataset = trainer.create_dataset(number_of_games=100, temperature=STARTING_TEMPERATURE)
print("Running time: %s seconds" % (time.time() - start_time))

Running time: 14.186429500579834 seconds


In [17]:
def parallel_fn(n):
    from libs.Trainer import Trainer
    from libs.TicTacToe import TicTacToe
    from libs.MCTS import MCTS
    N_GAMES_PER_JOB = 25
    STARTING_TEMPERATURE = 1.0
    trainer = Trainer(game = TicTacToe, mcts = MCTS, model=None)
    game_batch = trainer.create_dataset(number_of_games=N_GAMES_PER_JOB, temperature=STARTING_TEMPERATURE)
    return game_batch

In [18]:
start_time = time.time()
ctx = mp.get_context("spawn")
pool = ctx.Pool(n_cores)
dataset = pool.map(parallel_fn, range(n_cores))
print("Running time: %s seconds" % (time.time() - start_time))

Running time: 18.777746438980103 seconds


In [19]:
flatten_dataset = []
for batch in dataset:
    flatten_dataset += batch

In [20]:
flatten_dataset

[(array([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0.11, 0.11, 0.11, 0.12, 0.11, 0.11, 0.11, 0.11, 0.11]),
  0),
 (array([-1., -0., -0., -0., -0., -0., -0., -0., -0.]),
  array([0.        , 0.11818182, 0.12727273, 0.11818182, 0.12727273,
         0.12727273, 0.12727273, 0.12727273, 0.12727273]),
  0),
 (array([ 1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.]),
  array([0.        , 0.09734513, 0.        , 0.30973451, 0.09734513,
         0.09734513, 0.09734513, 0.09734513, 0.20353982]),
  0),
 (array([-1., -0.,  1., -0., -0., -1., -0., -0., -0.]),
  array([0.        , 0.14545455, 0.        , 0.13636364, 0.28181818,
         0.        , 0.14545455, 0.14545455, 0.14545455]),
  0),
 (array([ 1.,  0., -1.,  0., -1.,  1.,  0.,  0.,  0.]),
  array([0.        , 0.06153846, 0.        , 0.06153846, 0.        ,
         0.        , 0.75384615, 0.06153846, 0.06153846]),
  0),
 (array([-1., -0.,  1., -0.,  1., -1., -1., -0., -0.]),
  array([0.        , 0.09137056, 0.        , 0.74111675, 0.       

In [21]:
def compute_average_dataset(dataset):
    board_dict = dict()
    policy_dict = dict()
    value_dict = dict()

    for board, policy, value in dataset:
        key = hashlib.sha1(board.view(np.uint8)).hexdigest()

        if key not in board_dict:
            board_dict[key] = board

        if key in policy_dict:
            policy_dict[key].append(policy)
        else:
            policy_dict[key] = [policy]

        if key in value_dict:
            value_dict[key].append(value)
        else:
            value_dict[key] = [value]

    average = []
    for key, board in board_dict.items():
        policies = policy_dict[key]
        values = value_dict[key]
        average.append( (board, sum(policies)/len(policies), sum(values)/len(values)) )

    return average

In [22]:
def windowing_dataset(dataset, length):
    if len(dataset)<=length:
        return dataset
    else:
        return dataset[-length:]

In [23]:
compute_average_dataset(flatten_dataset)

[(array([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0.11105 , 0.111175, 0.111425, 0.1111  , 0.1112  , 0.110975,
         0.1114  , 0.1109  , 0.110775]),
  0.3),
 (array([-1., -0., -0., -0., -0., -0., -0., -0., -0.]),
  array([0.        , 0.12493968, 0.12493747, 0.12346327, 0.12493968,
         0.12542887, 0.12592027, 0.12493968, 0.12543108]),
  -0.4594594594594595),
 (array([ 1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.]),
  array([0.        , 0.1039823 , 0.        , 0.17699115, 0.15265487,
         0.1039823 , 0.19247788, 0.1039823 , 0.1659292 ]),
  0.25),
 (array([-1., -0.,  1., -0., -0., -1., -0., -0., -0.]),
  array([0.        , 0.14352373, 0.        , 0.13897828, 0.242679  ,
         0.        , 0.18777152, 0.14352373, 0.14352373]),
  -0.5),
 (array([ 1.,  0., -1.,  0., -1.,  1.,  0.,  0.,  0.]),
  array([0.        , 0.06153846, 0.        , 0.06153846, 0.        ,
         0.        , 0.75384615, 0.06153846, 0.06153846]),
  0.0),
 (array([-1., -0.,  1., -0.,  1., -1., -1., -0., 

# 1st training

In [24]:
trainer = Trainer(game = TicTacToe, mcts = MCTS, model=CachedModel( create_az_model()) )

In [25]:
training_dataset = compute_average_dataset(flatten_dataset)

In [26]:
fit_history = trainer.train(training_dataset, n_epochs=1000, batch_size=30, learning_rate=1e-2)

Epoch 1/1000


38/38 [==============================] - 2s 11ms/step - loss: 3.2098 - policy_loss: 1.7784 - value_loss: 1.3492 - val_loss: 2.7460 - val_policy_loss: 1.9849 - val_value_loss: 0.6610 - lr: 0.0100
Epoch 2/1000
38/38 [==============================] - 0s 5ms/step - loss: 2.1630 - policy_loss: 1.4182 - value_loss: 0.6420 - val_loss: 2.6576 - val_policy_loss: 1.8965 - val_value_loss: 0.6586 - lr: 0.0100
Epoch 3/1000
38/38 [==============================] - 0s 5ms/step - loss: 1.9893 - policy_loss: 1.3013 - value_loss: 0.5874 - val_loss: 2.5240 - val_policy_loss: 1.7611 - val_value_loss: 0.6645 - lr: 0.0100
Epoch 4/1000
38/38 [==============================] - 0s 6ms/step - loss: 1.9119 - policy_loss: 1.2262 - value_loss: 0.5894 - val_loss: 2.6036 - val_policy_loss: 1.8447 - val_value_loss: 0.6646 - lr: 0.0100
Epoch 5/1000
38/38 [==============================] - 0s 5ms/step - loss: 1.8754 - policy_loss: 1.1946 - value_loss: 0.5883 - val_loss: 2.5501 - val_policy_loss: 1.7960 

38/38 [==============================] - 0s 5ms/step - loss: 1.6283 - policy_loss: 0.9945 - value_loss: 0.5871 - val_loss: 1.7374 - val_policy_loss: 1.0298 - val_value_loss: 0.6610 - lr: 2.2823e-04
Epoch 39/1000
38/38 [==============================] - 0s 5ms/step - loss: 1.6281 - policy_loss: 0.9945 - value_loss: 0.5870 - val_loss: 1.7371 - val_policy_loss: 1.0295 - val_value_loss: 0.6611 - lr: 1.7249e-04
Epoch 40/1000
38/38 [==============================] - 0s 5ms/step - loss: 1.6254 - policy_loss: 0.9919 - value_loss: 0.5870 - val_loss: 1.7361 - val_policy_loss: 1.0286 - val_value_loss: 0.6609 - lr: 1.2907e-04
Epoch 41/1000
38/38 [==============================] - 0s 5ms/step - loss: 1.6228 - policy_loss: 0.9893 - value_loss: 0.5870 - val_loss: 1.7354 - val_policy_loss: 1.0280 - val_value_loss: 0.6609 - lr: 1.0000e-04
Epoch 42/1000
38/38 [==============================] - 0s 5ms/step - loss: 1.6253 - policy_loss: 0.9919 - value_loss: 0.5870 - val_loss: 1.7357 - val_policy_loss: 1.0

In [27]:
trainer.model.predict(np.array([[0., 0., -1., -1., 1., -1., 1., 1., 0.]]))

(array([[0.11427562, 0.08511891, 0.09632012, 0.12382594, 0.13353354,
         0.10815345, 0.07497605, 0.15399107, 0.10980526]], dtype=float32),
 array([[0.34428087]], dtype=float32))

In [28]:
trainer.model.predict(np.array([[0., 0., 0., 0., -1., 1., -1., 0., 0.]]))

1/1 [==============================] - 0s 107ms/step


(array([[9.4403282e-02, 9.6316755e-02, 4.3302292e-01, 1.0936800e-01,
         1.6434684e-04, 5.6660181e-04, 1.0533913e-03, 1.1892079e-01,
         1.4618383e-01]], dtype=float32),
 array([[0.13375469]], dtype=float32))

In [29]:
trainer.save_model('saved_model/tmp_model')

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


# Generating the self-playing dataset (2nd) with caching across processes

In [30]:
N_ROUNDS = 40

In [31]:
def parallel_fn(job_n, cache, n):
    
    from libs.Trainer import Trainer
    from libs.TicTacToe import TicTacToe
    from libs.model import CachedModel
    from libs.MCTS import MCTS
    import tensorflow as tf
    N_GAMES_PER_JOB = 25
    STARTING_TEMPERATURE = 10.0
    
    model = tf.keras.models.load_model("saved_model/tmp_model")
    trainer = Trainer(game = TicTacToe, mcts = MCTS, model=CachedModel(model, cache) )
    
    game_batch = trainer.create_dataset(number_of_games=N_GAMES_PER_JOB, temperature=STARTING_TEMPERATURE/n)
    
    return game_batch

In [32]:
if __name__ == '__main__':

    self_play_dataset = flatten_dataset
    
    model = create_az_model()

    for n in range(N_ROUNDS):

        start_time = time.time()
        ctx = mp.get_context("spawn")

        with SyncManager() as manager:

            shared_cache = manager.dict()
            print(f"shared_cache type: {type(shared_cache)}")
            args = [(job_n, shared_cache, n+1) for job_n in range(n_cores)]
            print(f"Number of args: {len(args)}")
            print(args)

            with ctx.Pool(n_cores) as pool:

                round_dataset = pool.starmap(parallel_fn, args)

        print(f"Running time {n+1}-th round: {time.time() - start_time} seconds")

        flatten_round_dataset = []
        for batch in round_dataset:
            flatten_round_dataset += batch
        self_play_dataset += flatten_round_dataset
        training_dataset = compute_average_dataset(self_play_dataset)
        print(f"Dataset size: {len(self_play_dataset)}")

        trainer = Trainer(game = TicTacToe, mcts = MCTS, model=model)
        fit_history = trainer.train(training_dataset, n_epochs=50, batch_size=50, learning_rate=1e-2)

        trainer.model.save("saved_model/tmp_model")
        trainer.model.save("saved_model/model_round_"+str(n))



shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (1, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (2, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (3, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (4, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (5, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (6, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (7, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (8, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (9, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (10, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (11, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (12, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (13, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (14, <DictProxy object, typeid 'dict' at 0x2b8bd8050d0>, 1), (15, <DictProx

38/38 [==============================] - 0s 6ms/step - loss: 0.9895 - policy_loss: 0.8383 - value_loss: 0.0376 - val_loss: 1.3308 - val_policy_loss: 0.6348 - val_value_loss: 0.5826 - lr: 4.9787e-04
Epoch 36/50
38/38 [==============================] - 0s 6ms/step - loss: 0.9825 - policy_loss: 0.8365 - value_loss: 0.0328 - val_loss: 1.3320 - val_policy_loss: 0.6360 - val_value_loss: 0.5830 - lr: 3.8774e-04
INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_0\assets


INFO:tensorflow:Assets written to: saved_model/model_round_0\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (1, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (2, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (3, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (4, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (5, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (6, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (7, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (8, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (9, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (10, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (11, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (12, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (13, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (14, <DictProxy object, typeid 'dict' at 0x2b8b4d055b0>, 2), (15, <DictProx

47/47 [==============================] - 0s 5ms/step - loss: 0.9273 - policy_loss: 0.7541 - value_loss: 0.0390 - val_loss: 1.1995 - val_policy_loss: 0.6297 - val_value_loss: 0.4360 - lr: 4.9787e-04
Epoch 36/50
47/47 [==============================] - 0s 5ms/step - loss: 0.9269 - policy_loss: 0.7555 - value_loss: 0.0380 - val_loss: 1.2049 - val_policy_loss: 0.6322 - val_value_loss: 0.4395 - lr: 3.8774e-04
Epoch 37/50
47/47 [==============================] - 0s 5ms/step - loss: 0.9250 - policy_loss: 0.7544 - value_loss: 0.0376 - val_loss: 1.1993 - val_policy_loss: 0.6272 - val_value_loss: 0.4394 - lr: 2.9897e-04
Epoch 38/50
47/47 [==============================] - 0s 5ms/step - loss: 0.9194 - policy_loss: 0.7525 - value_loss: 0.0343 - val_loss: 1.1988 - val_policy_loss: 0.6250 - val_value_loss: 0.4414 - lr: 2.2823e-04
Epoch 39/50
47/47 [==============================] - 0s 5ms/step - loss: 0.9179 - policy_loss: 0.7515 - value_loss: 0.0342 - val_loss: 1.2018 - val_policy_loss: 0.6273 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_1\assets


INFO:tensorflow:Assets written to: saved_model/model_round_1\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (1, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (2, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (3, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (4, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (5, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (6, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (7, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (8, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (9, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (10, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (11, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (12, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (13, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (14, <DictProxy object, typeid 'dict' at 0x2b8b620fe50>, 3), (15, <DictProx

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_2\assets


INFO:tensorflow:Assets written to: saved_model/model_round_2\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (1, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (2, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (3, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (4, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (5, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (6, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (7, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (8, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (9, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (10, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (11, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (12, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (13, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (14, <DictProxy object, typeid 'dict' at 0x2b8b9b2d100>, 4), (15, <DictProx

56/56 [==============================] - 0s 5ms/step - loss: 0.9163 - policy_loss: 0.6887 - value_loss: 0.0568 - val_loss: 0.9463 - val_policy_loss: 0.4777 - val_value_loss: 0.2983 - lr: 4.9787e-04
Epoch 36/50
56/56 [==============================] - 0s 5ms/step - loss: 0.9129 - policy_loss: 0.6887 - value_loss: 0.0541 - val_loss: 0.9479 - val_policy_loss: 0.4802 - val_value_loss: 0.2979 - lr: 3.8774e-04
Epoch 37/50
56/56 [==============================] - 0s 5ms/step - loss: 0.9110 - policy_loss: 0.6886 - value_loss: 0.0527 - val_loss: 0.9433 - val_policy_loss: 0.4789 - val_value_loss: 0.2950 - lr: 2.9897e-04
Epoch 38/50
56/56 [==============================] - 0s 5ms/step - loss: 0.9099 - policy_loss: 0.6879 - value_loss: 0.0527 - val_loss: 0.9493 - val_policy_loss: 0.4782 - val_value_loss: 0.3020 - lr: 2.2823e-04
Epoch 39/50
56/56 [==============================] - 0s 5ms/step - loss: 0.9039 - policy_loss: 0.6871 - value_loss: 0.0479 - val_loss: 0.9504 - val_policy_loss: 0.4792 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_3\assets


INFO:tensorflow:Assets written to: saved_model/model_round_3\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (1, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (2, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (3, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (4, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (5, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (6, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (7, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (8, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (9, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (10, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (11, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (12, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (13, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (14, <DictProxy object, typeid 'dict' at 0x2b8bdae8ac0>, 5), (15, <DictProx

58/58 [==============================] - 0s 5ms/step - loss: 0.8079 - policy_loss: 0.6517 - value_loss: 0.0368 - val_loss: 0.9227 - val_policy_loss: 0.4798 - val_value_loss: 0.3238 - lr: 4.9787e-04
Epoch 36/50
58/58 [==============================] - 0s 6ms/step - loss: 0.8032 - policy_loss: 0.6487 - value_loss: 0.0357 - val_loss: 0.9169 - val_policy_loss: 0.4795 - val_value_loss: 0.3188 - lr: 3.8774e-04
Epoch 37/50
58/58 [==============================] - 0s 6ms/step - loss: 0.8048 - policy_loss: 0.6494 - value_loss: 0.0370 - val_loss: 0.9150 - val_policy_loss: 0.4795 - val_value_loss: 0.3173 - lr: 2.9897e-04
Epoch 38/50
58/58 [==============================] - 0s 6ms/step - loss: 0.8017 - policy_loss: 0.6473 - value_loss: 0.0364 - val_loss: 0.9105 - val_policy_loss: 0.4780 - val_value_loss: 0.3146 - lr: 2.2823e-04
Epoch 39/50
58/58 [==============================] - 0s 5ms/step - loss: 0.7968 - policy_loss: 0.6437 - value_loss: 0.0352 - val_loss: 0.9134 - val_policy_loss: 0.4788 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_4\assets


INFO:tensorflow:Assets written to: saved_model/model_round_4\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (1, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (2, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (3, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (4, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (5, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (6, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (7, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (8, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (9, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (10, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (11, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (12, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (13, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (14, <DictProxy object, typeid 'dict' at 0x2b8b60e0f40>, 6), (15, <DictProx

60/60 [==============================] - 0s 5ms/step - loss: 0.7994 - policy_loss: 0.6375 - value_loss: 0.0397 - val_loss: 0.8205 - val_policy_loss: 0.4384 - val_value_loss: 0.2600 - lr: 4.9787e-04
Epoch 36/50
60/60 [==============================] - 0s 5ms/step - loss: 0.7989 - policy_loss: 0.6381 - value_loss: 0.0390 - val_loss: 0.8208 - val_policy_loss: 0.4377 - val_value_loss: 0.2614 - lr: 3.8774e-04
Epoch 37/50
60/60 [==============================] - 0s 5ms/step - loss: 0.7973 - policy_loss: 0.6389 - value_loss: 0.0369 - val_loss: 0.8131 - val_policy_loss: 0.4377 - val_value_loss: 0.2541 - lr: 2.9897e-04
Epoch 38/50
60/60 [==============================] - 0s 5ms/step - loss: 0.8028 - policy_loss: 0.6385 - value_loss: 0.0431 - val_loss: 0.8150 - val_policy_loss: 0.4389 - val_value_loss: 0.2550 - lr: 2.2823e-04
Epoch 39/50
60/60 [==============================] - 0s 5ms/step - loss: 0.8010 - policy_loss: 0.6402 - value_loss: 0.0398 - val_loss: 0.8141 - val_policy_loss: 0.4385 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_5\assets


INFO:tensorflow:Assets written to: saved_model/model_round_5\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (1, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (2, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (3, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (4, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (5, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (6, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (7, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (8, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (9, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (10, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (11, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (12, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (13, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (14, <DictProxy object, typeid 'dict' at 0x2b8bd9fe970>, 7), (15, <DictProx

61/61 [==============================] - 0s 5ms/step - loss: 0.8394 - policy_loss: 0.6413 - value_loss: 0.0524 - val_loss: 0.8177 - val_policy_loss: 0.4436 - val_value_loss: 0.2287 - lr: 4.9787e-04
Epoch 36/50
61/61 [==============================] - 0s 5ms/step - loss: 0.8368 - policy_loss: 0.6419 - value_loss: 0.0496 - val_loss: 0.8221 - val_policy_loss: 0.4431 - val_value_loss: 0.2339 - lr: 3.8774e-04
Epoch 37/50
61/61 [==============================] - 0s 5ms/step - loss: 0.8360 - policy_loss: 0.6405 - value_loss: 0.0506 - val_loss: 0.8271 - val_policy_loss: 0.4464 - val_value_loss: 0.2359 - lr: 2.9897e-04
Epoch 38/50
61/61 [==============================] - 0s 5ms/step - loss: 0.8382 - policy_loss: 0.6417 - value_loss: 0.0517 - val_loss: 0.8220 - val_policy_loss: 0.4442 - val_value_loss: 0.2332 - lr: 2.2823e-04
Epoch 39/50
61/61 [==============================] - 0s 5ms/step - loss: 0.8308 - policy_loss: 0.6404 - value_loss: 0.0459 - val_loss: 0.8233 - val_policy_loss: 0.4445 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_6\assets


INFO:tensorflow:Assets written to: saved_model/model_round_6\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (1, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (2, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (3, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (4, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (5, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (6, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (7, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (8, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (9, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (10, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (11, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (12, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (13, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (14, <DictProxy object, typeid 'dict' at 0x2b8b60cb5e0>, 8), (15, <DictProx

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_7\assets


INFO:tensorflow:Assets written to: saved_model/model_round_7\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (1, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (2, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (3, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (4, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (5, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (6, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (7, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (8, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (9, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (10, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (11, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (12, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (13, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (14, <DictProxy object, typeid 'dict' at 0x2b8b5e28a60>, 9), (15, <DictProx

62/62 [==============================] - 0s 5ms/step - loss: 0.7828 - policy_loss: 0.6144 - value_loss: 0.0480 - val_loss: 0.7043 - val_policy_loss: 0.4276 - val_value_loss: 0.1566 - lr: 4.9787e-04
Epoch 36/50
62/62 [==============================] - 0s 5ms/step - loss: 0.7831 - policy_loss: 0.6194 - value_loss: 0.0437 - val_loss: 0.7026 - val_policy_loss: 0.4260 - val_value_loss: 0.1568 - lr: 3.8774e-04
Epoch 37/50
62/62 [==============================] - 0s 6ms/step - loss: 0.7732 - policy_loss: 0.6117 - value_loss: 0.0419 - val_loss: 0.7027 - val_policy_loss: 0.4265 - val_value_loss: 0.1567 - lr: 2.9897e-04
Epoch 38/50
62/62 [==============================] - 0s 5ms/step - loss: 0.7757 - policy_loss: 0.6118 - value_loss: 0.0446 - val_loss: 0.7024 - val_policy_loss: 0.4270 - val_value_loss: 0.1561 - lr: 2.2823e-04
Epoch 39/50
62/62 [==============================] - 0s 6ms/step - loss: 0.7764 - policy_loss: 0.6164 - value_loss: 0.0408 - val_loss: 0.7022 - val_policy_loss: 0.4277 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_8\assets


INFO:tensorflow:Assets written to: saved_model/model_round_8\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (1, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (2, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (3, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (4, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (5, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (6, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (7, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (8, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (9, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (10, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (11, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (12, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (13, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10), (14, <DictProxy object, typeid 'dict' at 0x2b8b626f910>, 10),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_9\assets


INFO:tensorflow:Assets written to: saved_model/model_round_9\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (1, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (2, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (3, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (4, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (5, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (6, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (7, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (8, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (9, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (10, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (11, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (12, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (13, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11), (14, <DictProxy object, typeid 'dict' at 0x2b8bb7b7460>, 11),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_10\assets


INFO:tensorflow:Assets written to: saved_model/model_round_10\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (1, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (2, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (3, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (4, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (5, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (6, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (7, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (8, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (9, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (10, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (11, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (12, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (13, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12), (14, <DictProxy object, typeid 'dict' at 0x2b8b9a8a5b0>, 12),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_11\assets


INFO:tensorflow:Assets written to: saved_model/model_round_11\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (1, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (2, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (3, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (4, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (5, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (6, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (7, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (8, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (9, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (10, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (11, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (12, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (13, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13), (14, <DictProxy object, typeid 'dict' at 0x2b8bb5eeeb0>, 13),

63/63 [==============================] - 0s 6ms/step - loss: 0.7592 - policy_loss: 0.6018 - value_loss: 0.0444 - val_loss: 0.6835 - val_policy_loss: 0.4203 - val_value_loss: 0.1503 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 6ms/step - loss: 0.7636 - policy_loss: 0.6055 - value_loss: 0.0454 - val_loss: 0.6806 - val_policy_loss: 0.4193 - val_value_loss: 0.1486 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 6ms/step - loss: 0.7654 - policy_loss: 0.6045 - value_loss: 0.0485 - val_loss: 0.6766 - val_policy_loss: 0.4184 - val_value_loss: 0.1459 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 6ms/step - loss: 0.7569 - policy_loss: 0.6019 - value_loss: 0.0427 - val_loss: 0.6766 - val_policy_loss: 0.4182 - val_value_loss: 0.1462 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7577 - policy_loss: 0.6031 - value_loss: 0.0424 - val_loss: 0.6769 - val_policy_loss: 0.4185 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_12\assets


INFO:tensorflow:Assets written to: saved_model/model_round_12\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (1, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (2, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (3, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (4, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (5, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (6, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (7, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (8, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (9, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (10, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (11, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (12, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (13, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14), (14, <DictProxy object, typeid 'dict' at 0x2b8dcf1a5e0>, 14),

63/63 [==============================] - 0s 6ms/step - loss: 0.7374 - policy_loss: 0.5977 - value_loss: 0.0379 - val_loss: 0.6558 - val_policy_loss: 0.4099 - val_value_loss: 0.1442 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 6ms/step - loss: 0.7390 - policy_loss: 0.5986 - value_loss: 0.0389 - val_loss: 0.6595 - val_policy_loss: 0.4111 - val_value_loss: 0.1471 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7433 - policy_loss: 0.6009 - value_loss: 0.0411 - val_loss: 0.6603 - val_policy_loss: 0.4108 - val_value_loss: 0.1483 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7341 - policy_loss: 0.5952 - value_loss: 0.0378 - val_loss: 0.6553 - val_policy_loss: 0.4113 - val_value_loss: 0.1430 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7303 - policy_loss: 0.5942 - value_loss: 0.0352 - val_loss: 0.6545 - val_policy_loss: 0.4110 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_13\assets


INFO:tensorflow:Assets written to: saved_model/model_round_13\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (1, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (2, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (3, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (4, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (5, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (6, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (7, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (8, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (9, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (10, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (11, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (12, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (13, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15), (14, <DictProxy object, typeid 'dict' at 0x2b8f31b1640>, 15),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_14\assets


INFO:tensorflow:Assets written to: saved_model/model_round_14\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (1, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (2, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (3, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (4, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (5, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (6, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (7, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (8, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (9, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (10, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (11, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (12, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (13, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16), (14, <DictProxy object, typeid 'dict' at 0x2b8b9a99340>, 16),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_15\assets


INFO:tensorflow:Assets written to: saved_model/model_round_15\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (1, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (2, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (3, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (4, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (5, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (6, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (7, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (8, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (9, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (10, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (11, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (12, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (13, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17), (14, <DictProxy object, typeid 'dict' at 0x2b8d05bc610>, 17),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_16\assets


INFO:tensorflow:Assets written to: saved_model/model_round_16\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (1, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (2, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (3, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (4, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (5, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (6, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (7, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (8, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (9, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (10, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (11, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (12, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (13, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18), (14, <DictProxy object, typeid 'dict' at 0x2b8efa25760>, 18),

63/63 [==============================] - 0s 5ms/step - loss: 0.7342 - policy_loss: 0.5965 - value_loss: 0.0392 - val_loss: 0.6383 - val_policy_loss: 0.4104 - val_value_loss: 0.1295 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7305 - policy_loss: 0.5945 - value_loss: 0.0378 - val_loss: 0.6395 - val_policy_loss: 0.4099 - val_value_loss: 0.1315 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7321 - policy_loss: 0.5937 - value_loss: 0.0405 - val_loss: 0.6365 - val_policy_loss: 0.4096 - val_value_loss: 0.1290 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7312 - policy_loss: 0.5944 - value_loss: 0.0390 - val_loss: 0.6378 - val_policy_loss: 0.4099 - val_value_loss: 0.1302 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7290 - policy_loss: 0.5939 - value_loss: 0.0375 - val_loss: 0.6370 - val_policy_loss: 0.4095 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_17\assets


INFO:tensorflow:Assets written to: saved_model/model_round_17\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (1, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (2, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (3, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (4, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (5, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (6, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (7, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (8, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (9, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (10, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (11, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (12, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (13, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19), (14, <DictProxy object, typeid 'dict' at 0x2b8e68f8ac0>, 19),

63/63 [==============================] - 0s 5ms/step - loss: 0.7280 - policy_loss: 0.5954 - value_loss: 0.0377 - val_loss: 0.6343 - val_policy_loss: 0.4143 - val_value_loss: 0.1253 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7277 - policy_loss: 0.5950 - value_loss: 0.0381 - val_loss: 0.6339 - val_policy_loss: 0.4152 - val_value_loss: 0.1243 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7234 - policy_loss: 0.5927 - value_loss: 0.0363 - val_loss: 0.6360 - val_policy_loss: 0.4152 - val_value_loss: 0.1265 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7258 - policy_loss: 0.5939 - value_loss: 0.0376 - val_loss: 0.6347 - val_policy_loss: 0.4143 - val_value_loss: 0.1262 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7207 - policy_loss: 0.5926 - value_loss: 0.0340 - val_loss: 0.6322 - val_policy_loss: 0.4140 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_18\assets


INFO:tensorflow:Assets written to: saved_model/model_round_18\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (1, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (2, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (3, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (4, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (5, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (6, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (7, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (8, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (9, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (10, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (11, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (12, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (13, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20), (14, <DictProxy object, typeid 'dict' at 0x2b909477dc0>, 20),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_19\assets


INFO:tensorflow:Assets written to: saved_model/model_round_19\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (1, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (2, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (3, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (4, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (5, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (6, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (7, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (8, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (9, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (10, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (11, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (12, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (13, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21), (14, <DictProxy object, typeid 'dict' at 0x2b9133f8f70>, 21),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_20\assets


INFO:tensorflow:Assets written to: saved_model/model_round_20\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (1, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (2, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (3, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (4, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (5, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (6, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (7, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (8, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (9, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (10, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (11, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (12, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (13, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22), (14, <DictProxy object, typeid 'dict' at 0x2b8e7a22d60>, 22),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_21\assets


INFO:tensorflow:Assets written to: saved_model/model_round_21\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (1, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (2, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (3, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (4, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (5, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (6, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (7, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (8, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (9, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (10, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (11, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (12, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (13, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23), (14, <DictProxy object, typeid 'dict' at 0x2b912383280>, 23),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_22\assets


INFO:tensorflow:Assets written to: saved_model/model_round_22\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (1, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (2, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (3, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (4, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (5, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (6, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (7, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (8, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (9, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (10, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (11, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (12, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (13, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24), (14, <DictProxy object, typeid 'dict' at 0x2b902042880>, 24),

63/63 [==============================] - 0s 5ms/step - loss: 0.7226 - policy_loss: 0.5944 - value_loss: 0.0356 - val_loss: 0.6275 - val_policy_loss: 0.4190 - val_value_loss: 0.1161 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7212 - policy_loss: 0.5919 - value_loss: 0.0370 - val_loss: 0.6265 - val_policy_loss: 0.4175 - val_value_loss: 0.1169 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7218 - policy_loss: 0.5909 - value_loss: 0.0389 - val_loss: 0.6253 - val_policy_loss: 0.4187 - val_value_loss: 0.1147 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7185 - policy_loss: 0.5917 - value_loss: 0.0349 - val_loss: 0.6272 - val_policy_loss: 0.4188 - val_value_loss: 0.1166 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7199 - policy_loss: 0.5928 - value_loss: 0.0354 - val_loss: 0.6285 - val_policy_loss: 0.4181 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_23\assets


INFO:tensorflow:Assets written to: saved_model/model_round_23\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (1, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (2, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (3, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (4, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (5, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (6, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (7, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (8, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (9, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (10, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (11, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (12, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (13, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25), (14, <DictProxy object, typeid 'dict' at 0x2b91ea7dbe0>, 25),

63/63 [==============================] - 0s 5ms/step - loss: 0.7139 - policy_loss: 0.5909 - value_loss: 0.0340 - val_loss: 0.6286 - val_policy_loss: 0.4173 - val_value_loss: 0.1225 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7163 - policy_loss: 0.5929 - value_loss: 0.0347 - val_loss: 0.6252 - val_policy_loss: 0.4163 - val_value_loss: 0.1204 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7156 - policy_loss: 0.5926 - value_loss: 0.0345 - val_loss: 0.6253 - val_policy_loss: 0.4173 - val_value_loss: 0.1195 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7117 - policy_loss: 0.5897 - value_loss: 0.0337 - val_loss: 0.6260 - val_policy_loss: 0.4165 - val_value_loss: 0.1212 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7133 - policy_loss: 0.5883 - value_loss: 0.0367 - val_loss: 0.6245 - val_policy_loss: 0.4170 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_24\assets


INFO:tensorflow:Assets written to: saved_model/model_round_24\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (1, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (2, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (3, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (4, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (5, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (6, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (7, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (8, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (9, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (10, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (11, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (12, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (13, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26), (14, <DictProxy object, typeid 'dict' at 0x2b8d9722be0>, 26),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_25\assets


INFO:tensorflow:Assets written to: saved_model/model_round_25\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (1, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (2, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (3, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (4, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (5, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (6, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (7, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (8, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (9, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (10, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (11, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (12, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (13, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27), (14, <DictProxy object, typeid 'dict' at 0x2b903265400>, 27),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_26\assets


INFO:tensorflow:Assets written to: saved_model/model_round_26\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (1, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (2, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (3, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (4, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (5, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (6, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (7, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (8, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (9, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (10, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (11, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (12, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (13, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28), (14, <DictProxy object, typeid 'dict' at 0x2b9226afe80>, 28),

63/63 [==============================] - 0s 5ms/step - loss: 0.7188 - policy_loss: 0.5921 - value_loss: 0.0360 - val_loss: 0.6315 - val_policy_loss: 0.4201 - val_value_loss: 0.1207 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7265 - policy_loss: 0.5968 - value_loss: 0.0392 - val_loss: 0.6283 - val_policy_loss: 0.4206 - val_value_loss: 0.1172 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 6ms/step - loss: 0.7183 - policy_loss: 0.5920 - value_loss: 0.0360 - val_loss: 0.6247 - val_policy_loss: 0.4211 - val_value_loss: 0.1134 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7215 - policy_loss: 0.5938 - value_loss: 0.0376 - val_loss: 0.6266 - val_policy_loss: 0.4206 - val_value_loss: 0.1159 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7164 - policy_loss: 0.5930 - value_loss: 0.0334 - val_loss: 0.6256 - val_policy_loss: 0.4201 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_27\assets


INFO:tensorflow:Assets written to: saved_model/model_round_27\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (1, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (2, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (3, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (4, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (5, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (6, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (7, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (8, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (9, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (10, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (11, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (12, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (13, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29), (14, <DictProxy object, typeid 'dict' at 0x2b928c29490>, 29),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_28\assets


INFO:tensorflow:Assets written to: saved_model/model_round_28\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (1, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (2, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (3, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (4, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (5, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (6, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (7, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (8, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (9, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (10, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (11, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (12, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (13, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30), (14, <DictProxy object, typeid 'dict' at 0x2b91e8e2ca0>, 30),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_29\assets


INFO:tensorflow:Assets written to: saved_model/model_round_29\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (1, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (2, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (3, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (4, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (5, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (6, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (7, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (8, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (9, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (10, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (11, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (12, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (13, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31), (14, <DictProxy object, typeid 'dict' at 0x2b9226af520>, 31),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_30\assets


INFO:tensorflow:Assets written to: saved_model/model_round_30\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (1, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (2, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (3, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (4, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (5, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (6, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (7, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (8, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (9, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (10, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (11, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (12, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (13, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32), (14, <DictProxy object, typeid 'dict' at 0x2b8ef9b5730>, 32),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_31\assets


INFO:tensorflow:Assets written to: saved_model/model_round_31\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (1, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (2, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (3, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (4, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (5, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (6, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (7, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (8, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (9, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (10, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (11, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (12, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (13, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33), (14, <DictProxy object, typeid 'dict' at 0x2b928b9d790>, 33),

63/63 [==============================] - 0s 5ms/step - loss: 0.7237 - policy_loss: 0.5937 - value_loss: 0.0401 - val_loss: 0.6417 - val_policy_loss: 0.4228 - val_value_loss: 0.1291 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7210 - policy_loss: 0.5930 - value_loss: 0.0383 - val_loss: 0.6461 - val_policy_loss: 0.4231 - val_value_loss: 0.1334 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7233 - policy_loss: 0.5939 - value_loss: 0.0399 - val_loss: 0.6435 - val_policy_loss: 0.4218 - val_value_loss: 0.1323 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7168 - policy_loss: 0.5919 - value_loss: 0.0356 - val_loss: 0.6407 - val_policy_loss: 0.4217 - val_value_loss: 0.1297 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7246 - policy_loss: 0.5938 - value_loss: 0.0415 - val_loss: 0.6415 - val_policy_loss: 0.4216 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_32\assets


INFO:tensorflow:Assets written to: saved_model/model_round_32\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (1, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (2, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (3, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (4, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (5, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (6, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (7, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (8, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (9, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (10, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (11, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (12, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (13, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34), (14, <DictProxy object, typeid 'dict' at 0x2b9031c3820>, 34),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_33\assets


INFO:tensorflow:Assets written to: saved_model/model_round_33\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (1, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (2, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (3, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (4, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (5, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (6, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (7, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (8, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (9, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (10, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (11, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (12, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (13, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35), (14, <DictProxy object, typeid 'dict' at 0x2b934b478e0>, 35),

63/63 [==============================] - 0s 5ms/step - loss: 0.7180 - policy_loss: 0.5913 - value_loss: 0.0374 - val_loss: 0.6167 - val_policy_loss: 0.4149 - val_value_loss: 0.1128 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7144 - policy_loss: 0.5897 - value_loss: 0.0357 - val_loss: 0.6135 - val_policy_loss: 0.4136 - val_value_loss: 0.1111 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7181 - policy_loss: 0.5934 - value_loss: 0.0359 - val_loss: 0.6121 - val_policy_loss: 0.4139 - val_value_loss: 0.1095 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7134 - policy_loss: 0.5912 - value_loss: 0.0336 - val_loss: 0.6123 - val_policy_loss: 0.4133 - val_value_loss: 0.1104 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7183 - policy_loss: 0.5925 - value_loss: 0.0373 - val_loss: 0.6120 - val_policy_loss: 0.4142 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_34\assets


INFO:tensorflow:Assets written to: saved_model/model_round_34\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (1, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (2, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (3, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (4, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (5, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (6, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (7, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (8, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (9, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (10, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (11, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (12, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (13, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36), (14, <DictProxy object, typeid 'dict' at 0x2b91e624d00>, 36),

63/63 [==============================] - 0s 6ms/step - loss: 0.7149 - policy_loss: 0.5920 - value_loss: 0.0369 - val_loss: 0.6082 - val_policy_loss: 0.4177 - val_value_loss: 0.1045 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7163 - policy_loss: 0.5949 - value_loss: 0.0356 - val_loss: 0.6073 - val_policy_loss: 0.4162 - val_value_loss: 0.1054 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7181 - policy_loss: 0.5933 - value_loss: 0.0391 - val_loss: 0.6064 - val_policy_loss: 0.4163 - val_value_loss: 0.1045 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7094 - policy_loss: 0.5888 - value_loss: 0.0351 - val_loss: 0.6076 - val_policy_loss: 0.4172 - val_value_loss: 0.1050 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7156 - policy_loss: 0.5921 - value_loss: 0.0380 - val_loss: 0.6091 - val_policy_loss: 0.4178 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_35\assets


INFO:tensorflow:Assets written to: saved_model/model_round_35\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (1, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (2, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (3, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (4, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (5, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (6, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (7, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (8, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (9, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (10, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (11, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (12, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (13, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37), (14, <DictProxy object, typeid 'dict' at 0x2b934b474c0>, 37),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_36\assets


INFO:tensorflow:Assets written to: saved_model/model_round_36\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (1, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (2, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (3, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (4, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (5, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (6, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (7, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (8, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (9, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (10, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (11, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (12, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (13, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38), (14, <DictProxy object, typeid 'dict' at 0x2b8fc3c3be0>, 38),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_37\assets


INFO:tensorflow:Assets written to: saved_model/model_round_37\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (1, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (2, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (3, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (4, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (5, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (6, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (7, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (8, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (9, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (10, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (11, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (12, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (13, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39), (14, <DictProxy object, typeid 'dict' at 0x2b9349a5790>, 39),

63/63 [==============================] - 0s 5ms/step - loss: 0.7194 - policy_loss: 0.5938 - value_loss: 0.0380 - val_loss: 0.6228 - val_policy_loss: 0.4167 - val_value_loss: 0.1185 - lr: 4.9787e-04
Epoch 36/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7222 - policy_loss: 0.5965 - value_loss: 0.0383 - val_loss: 0.6207 - val_policy_loss: 0.4162 - val_value_loss: 0.1173 - lr: 3.8774e-04
Epoch 37/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7201 - policy_loss: 0.5943 - value_loss: 0.0385 - val_loss: 0.6191 - val_policy_loss: 0.4147 - val_value_loss: 0.1172 - lr: 2.9897e-04
Epoch 38/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7188 - policy_loss: 0.5937 - value_loss: 0.0380 - val_loss: 0.6203 - val_policy_loss: 0.4153 - val_value_loss: 0.1180 - lr: 2.2823e-04
Epoch 39/50
63/63 [==============================] - 0s 5ms/step - loss: 0.7163 - policy_loss: 0.5899 - value_loss: 0.0394 - val_loss: 0.6193 - val_policy_loss: 0.4147 - va

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_38\assets


INFO:tensorflow:Assets written to: saved_model/model_round_38\assets


shared_cache type: <class 'multiprocess.managers.DictProxy'>
Number of args: 16
[(0, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (1, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (2, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (3, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (4, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (5, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (6, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (7, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (8, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (9, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (10, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (11, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (12, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (13, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40), (14, <DictProxy object, typeid 'dict' at 0x2b8e183a880>, 40),

INFO:tensorflow:Assets written to: saved_model/tmp_model\assets


INFO:tensorflow:Assets written to: saved_model/model_round_39\assets


INFO:tensorflow:Assets written to: saved_model/model_round_39\assets
