In [43]:
import random
import numpy as np
import tensorflow as tf

## Tetris engine

In [237]:
class Tetris():
    
    def __init__(self, width, height):
        
        self.width = width
        self.height = height
        self.grid = np.append(np.zeros(width*height), -np.ones(width))
        self.score = 0
        
        self.current_tetromino = None
        self.current_position = None
        self.current_rotation = None
        
        lTetromino = [
                [1,width+1,width*2+1,2],
                [width, width+1,width+2,width*2+2],
                [1,width+1,width*2+1,width*2],
                [0,width, width+1,width+2]
            ]
    
        zTetromino = [
                [1,2,width,width+1],
                [0,width,width+1,width*2+1],
                [1,2,width,width+1],
                [0,width,width+1,width*2+1]
            ]

        tTetromino = [
                [1,width,width+1,width+2],
                [1,width+1,width+2,width*2+1],
                [width,width+1,width+2,width*2+1],
                [1,width,width+1,width*2+1]
            ]

        oTetromino = [
                [0,1,width,width+1],
                [0,1,width,width+1],
                [0,1,width,width+1],
                [0,1,width,width+1]
            ]

        iTetromino = [
                [1,width+1,width*2+1,width*3+1],
                [width,width+1,width+2,width+3],
                [1,width+1,width*2+1,width*3+1],
                [width,width+1,width+2,width+3]
            ]

        self.theTetrominoes = [lTetromino, zTetromino, tTetromino, oTetromino,iTetromino]
        
        self.theTetrominoSizes = np.max(np.array(self.theTetrominoes) % self.width, axis=(1,2))+1
        
        self.status = "ONGOING"
        
    
    def start_new_tetromino(self):
        
        self.current_tetromino = np.random.choice(range(len(self.theTetrominoes)))
        self.current_position = 4
        self.current_rotation = 0
        
        #self.print_game()
    
    
    def print_game(self):
        
        grid = self.grid.copy()
        
        print( self.current_game(grid, self.current_tetromino, self.current_position, self.current_rotation).reshape(game.height+1, game.width) )
        
    
    def current_game(self, grid, tetromino_idx, position, rotation):
        
        grid = self.grid.copy()        
        tetromino = self.theTetrominoes[tetromino_idx][rotation]
        for pos in tetromino:
            grid[pos + position] = 2
        
        return grid
        
        
    def move(self, action):
        
        reward = 0
        
        if self.check_tetromino_and_stop():
            self.start_new_tetromino()
            
        if action==0:
            # do nothing
            pass
        elif action==1:
            # rotate
            #print("rotate")
            self.current_rotation, reward = self.rotate()
        elif action==2:
            # go left
            #print("left")
            self.current_position, reward = self.move_left()
        elif action==3:
            # go right
            #print("right")
            self.current_position, reward = self.move_right()
        elif action==4:
            # go down
            #print("down")
            self.current_position += self.width
        else:
            print("Invalid action")
        
        if self.check_tetromino_and_stop():
            self.start_new_tetromino()
        else:
            self.current_position += self.width
            if self.check_tetromino_and_stop():
                self.start_new_tetromino()

        self.grid, last_reward = self.check_lines_and_update_score(self.grid)
        reward += last_reward
        #print(f"Reward: {reward}")
        return reward
    
    
    def nextGrids(self):
        
        
        grids = []
            
        for m in range(5):
            
            grid = self.grid.copy()
            tetromino = self.current_tetromino
            position = self.current_position
            rotation = self.current_rotation
            
            if m==0:
                # do nothing
                pass
            elif m==1:
                # rotate
                rotation, reward = self.rotate()
            elif m==2:
                # go left
                position, reward = self.move_left()
            elif m==3:
                # go right
                position, reward = self.move_right()
            elif m==4:
                # go down
                position += self.width
            else:
                print("Invalid action")
            
            grid, tetromino, position, rotation = self.check_tetromino(grid, tetromino, position, rotation)
            position += self.width
            grid, tetromino, position, rotation = self.check_tetromino(grid, tetromino, position, rotation)
            grid = self.current_game(grid, tetromino, position, rotation)
            
            grids.append(grid)
            
        return grids
    

    def rotate(self):
        
        #tetromino = self.theTetrominoes[self.current_tetromino][self.current_rotation]
        rotation = (self.current_rotation + 1) %4
        rotated_tetromino = self.theTetrominoes[self.current_tetromino][rotation]
        width = self.width
        
        tetromino_size = self.theTetrominoSizes[self.current_tetromino]
        
        for pos in rotated_tetromino:
            if self.grid[pos+self.current_position] in [-1,1]:
                return self.current_rotation, 0
        
        if tetromino_size==3:
            if (self.current_position+1-1) % width==0 or (self.current_position+1+1) % width==0:
                return self.current_rotation, 0
        if tetromino_size==4 and self.current_rotation in [0,2]:
            if (self.current_position+1-1) % width==0 or (self.current_position+2+1) % width==0:
                return self.current_rotation, 0
        
        return rotation, 0
        
        
    def move_left(self):
        
        tetromino = self.theTetrominoes[self.current_tetromino][self.current_rotation]
        position = self.current_position - 1
        width = self.width
        
        for pos in tetromino:
            if (pos+self.current_position)//width!=(pos+position)//width or self.grid[pos+position]==1:
                #print(self.current_position, position, pos)
                #self.print_game()
                return self.current_position, 0
        
        return position, 0
    
    
    def move_right(self):
        
        tetromino = self.theTetrominoes[self.current_tetromino][self.current_rotation]
        position = self.current_position + 1
        width = self.width
        
        for pos in tetromino:
            if (pos+self.current_position)//width!=(pos+position)//width or self.grid[pos+position]==1:
                #print(self.current_position, position, pos)
                #self.print_game()
                return self.current_position, 0
        
        return position, 0
    
    
    def check_tetromino_and_stop(self):
        
        tetromino = self.theTetrominoes[self.current_tetromino][self.current_rotation]
        for pos in tetromino:
            if self.grid[pos + self.current_position + self.width] in [-1, 1]:
                for final_pos in tetromino:
                    self.grid[final_pos + self.current_position] = 1
                return True
        
        return False
    
    
    def check_tetromino(self, grid, tetromino_idx, position, rotation):
        
        tetromino = self.theTetrominoes[tetromino_idx][rotation]
        for pos in tetromino:
            if grid[pos + position + self.width] in [-1, 1]:
                for final_pos in tetromino:
                    grid[final_pos + position] = 1
                tetromino_idx = np.random.choice(range(len(self.theTetrominoes)))
                position = 4
                rotation = 0
                return grid, tetromino_idx, position, rotation
        
        return grid, tetromino_idx, position, rotation
    
    
    def check_lines_and_update_score(self, grid):
        
        score = 0
        
        for h in range(self.height):
            
            if (grid[h*self.width:(h+1)*self.width]==1).all():
                grid = np.delete(grid, range(h*self.width,(h+1)*self.width))
                self.score += 1
                grid = np.insert(grid, 0, np.zeros(self.width))
                #print(f"{h} line removed score = {self.score}")
                score += 1
            
        if (grid[:self.width]==1).any():
            self.status = "OVER"
            #print("Game Over")
            score = -1
    
        return grid, score
            

In [225]:
game = Tetris(width = 10, height = 20)
game.grid = np.append(np.ones(game.width*game.height), -np.ones(game.width))
game.grid.reshape(game.height+1, game.width)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.

In [226]:
game.check_lines_and_update_score(game.grid)

(array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [227]:
game.score

20

In [228]:
game.grid.reshape(game.height+1, game.width)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.

## Design DQN model

In [229]:
game = Tetris(width = 10, height = 20)
game.start_new_tetromino()

plays = 20

while plays>0:
    game.move(np.random.choice(range(5)))
    print("game")
    game.print_game()
    print("nexts")
    #[ print(g.reshape(21, 10)) for g in game.nextGrids()]
    plays -= 1

game.print_game()

game
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  2.  2.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
nexts
game
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.

In [230]:
activation_fn = tf.nn.leaky_relu

hidden_dimensions = 32
depth = 4

#inputs = tf.keras.layers.Input((game.width*game.height))
inputs = tf.constant(game.grid[:-game.width])

inputs = tf.reshape(inputs,  (-1,game.width, game.height) )
print(tf.shape(inputs))
one_hot_inputs = tf.one_hot(tf.cast(inputs, tf.int32),3)
print(tf.shape(one_hot_inputs))
    
#x = tf.keras.layers.MultiHeadAttention(num_heads=120, key_dim=120, attention_axes=1)(one_hot_inputs,one_hot_inputs)
x = tf.keras.layers.Conv2D(filters=81, kernel_size=4, activation=activation_fn)(one_hot_inputs)
print(tf.shape(x))
x = tf.keras.layers.Conv2D(filters=40, kernel_size=4, activation=activation_fn)(x)
print(tf.shape(x))
x = tf.keras.layers.Conv2D(filters=5, kernel_size=4, activation=activation_fn)(x)
print(tf.shape(x))
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(5, activation=tf.nn.sigmoid)(x)
print(tf.shape(x))

outputs = x

#model = tf.keras.Model(inputs=inputs, outputs=outputs, name="tetris_model")

tf.Tensor([ 1 10 20], shape=(3,), dtype=int32)
tf.Tensor([ 1 10 20  3], shape=(4,), dtype=int32)
tf.Tensor([ 1  7 17 81], shape=(4,), dtype=int32)
tf.Tensor([ 1  4 14 40], shape=(4,), dtype=int32)
tf.Tensor([ 1  1 11  5], shape=(4,), dtype=int32)
tf.Tensor([1 5], shape=(2,), dtype=int32)


In [231]:
def create_Q(width, height):
    
    activation_fn = tf.nn.leaky_relu

    hidden_dimensions = 32
    depth = 4

    inputs = tf.keras.layers.Input((width*height))
    
    x = tf.reshape(inputs,  (-1,game.width, game.height) )

    one_hot_inputs = tf.one_hot(tf.cast(x, tf.int32),3)
    
    x = tf.keras.layers.Conv2D(filters=10, kernel_size=4, activation=activation_fn)(one_hot_inputs)

    x = tf.keras.layers.Conv2D(filters=10, kernel_size=4, activation=activation_fn)(x)
    
    x = tf.keras.layers.Conv2D(filters=10, kernel_size=4, activation=activation_fn)(x)
    
    x = tf.keras.layers.Flatten()(x)
    
    x = tf.keras.layers.Dense(5)(x)

    outputs = x

    model = tf.keras.Model(inputs=inputs, outputs=outputs, name="tetris_model")

    return model


In [232]:
model = create_Q(10,20)

## Testing the tetromino for the rotation

In [233]:
game = Tetris(width = 10, height = 20)

In [234]:
sizes = np.max(np.array(game.theTetrominoes) % game.width, axis=(1,2)) +1
print(sizes)

[3 3 3 2 4]


## Training the AI

In [238]:
model = create_Q(10,20)

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
loss_fn = tf.keras.losses.Huber()

In [ ]:
N = 10000
B = 10
epsilons = np.linspace(1.0, 0.3,N)
gamma = tf.constant(0.9)

for n in range(N):
        
    rewards = []
    next_max_rewards = []
    grids = []
    
    epsilon = epsilons[n]
    
    for m in range(B):
        game = Tetris(width = 10, height = 20)
        game.start_new_tetromino()
        while game.status!="OVER":

            if random.random()>epsilon:
                player = model(game.grid[:-game.width])
                move = tf.argmax(player, axis=1).numpy()[0]
                reward = game.move(move)
            else:
                reward = game.move(np.random.choice(range(5)))

            #print(game.nextGrids())
            next_grids = tf.concat([ g[:-game.width][np.newaxis,:] for g in game.nextGrids()], axis=0)
            next_max_reward = tf.reduce_max(model(next_grids)).numpy()
            next_max_rewards.append( next_max_reward )
            rewards.append(reward)
            grids.append(game.current_game(game.grid, game.current_tetromino, game.current_position, game.current_rotation)[:-game.width])


    training_grids = tf.concat([g[np.newaxis,:] for g in grids], axis=0)
    with tf.GradientTape() as tape:
        y = model(training_grids, training=True)
        y = tf.reduce_max(y, axis=1)
        loss_values = loss_fn(rewards + gamma*next_max_rewards, y)
        

    grads = tape.gradient(loss_values, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
    
    lsv = round(loss_values.numpy(),4)
            
    print(f"Game round {n+1}: epsilon={round(epsilon,2)}, loss={lsv}, score={game.score}, max={max(rewards)}, min={min(rewards)}, length={len(rewards)}")
    print([(x,round(rewards.count(x)/len(rewards),2)) for x in set(rewards)])
        

Game round 1: epsilon=1.0, loss=0.006800000090152025, score=0, max=0, min=-1, length=1040
[(0, 0.99), (-1, 0.01)]
Game round 2: epsilon=1.0, loss=0.005400000140070915, score=0, max=0, min=-1, length=1246
[(0, 0.99), (-1, 0.01)]
Game round 3: epsilon=1.0, loss=0.00559999980032444, score=0, max=0, min=-1, length=1065
[(0, 0.99), (-1, 0.01)]
Game round 4: epsilon=1.0, loss=0.005100000184029341, score=0, max=0, min=-1, length=1118
[(0, 0.99), (-1, 0.01)]
Game round 5: epsilon=1.0, loss=0.004900000058114529, score=0, max=0, min=-1, length=1144
[(0, 0.99), (-1, 0.01)]
Game round 6: epsilon=1.0, loss=0.004800000227987766, score=0, max=0, min=-1, length=1190
[(0, 0.99), (-1, 0.01)]
Game round 7: epsilon=1.0, loss=0.004999999888241291, score=0, max=0, min=-1, length=1124
[(0, 0.99), (-1, 0.01)]
Game round 8: epsilon=1.0, loss=0.004900000058114529, score=0, max=0, min=-1, length=1119
[(0, 0.99), (-1, 0.01)]
Game round 9: epsilon=1.0, loss=0.004800000227987766, score=0, max=0, min=-1, length=1149

Game round 73: epsilon=0.99, loss=0.00430000014603138, score=0, max=0, min=-1, length=1178
[(0, 0.99), (-1, 0.01)]
Game round 74: epsilon=0.99, loss=0.004800000227987766, score=0, max=0, min=-1, length=1037
[(0, 0.99), (-1, 0.01)]
Game round 75: epsilon=0.99, loss=0.004600000102072954, score=0, max=0, min=-1, length=989
[(0, 0.99), (-1, 0.01)]
Game round 76: epsilon=0.99, loss=0.003700000001117587, score=0, max=0, min=-1, length=1176
[(0, 0.99), (-1, 0.01)]
Game round 77: epsilon=0.99, loss=0.00430000014603138, score=0, max=0, min=-1, length=975
[(0, 0.99), (-1, 0.01)]
Game round 78: epsilon=0.99, loss=0.004399999976158142, score=0, max=0, min=-1, length=1001
[(0, 0.99), (-1, 0.01)]
Game round 79: epsilon=0.99, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1100
[(0, 0.99), (-1, 0.01)]
Game round 80: epsilon=0.99, loss=0.004000000189989805, score=0, max=0, min=-1, length=1104
[(0, 0.99), (-1, 0.01)]
Game round 81: epsilon=0.99, loss=0.00279999990016222, score=0, max=0, min=

Game round 144: epsilon=0.99, loss=0.004000000189989805, score=0, max=0, min=-1, length=1038
[(0, 0.99), (-1, 0.01)]
Game round 145: epsilon=0.99, loss=0.0031999999191612005, score=0, max=0, min=-1, length=1073
[(0, 0.99), (-1, 0.01)]
Game round 146: epsilon=0.99, loss=0.003100000089034438, score=0, max=0, min=-1, length=1136
[(0, 0.99), (-1, 0.01)]
Game round 147: epsilon=0.99, loss=0.005499999970197678, score=0, max=0, min=-1, length=1118
[(0, 0.99), (-1, 0.01)]
Game round 148: epsilon=0.99, loss=0.005200000014156103, score=0, max=0, min=-1, length=1147
[(0, 0.99), (-1, 0.01)]
Game round 149: epsilon=0.99, loss=0.0035000001080334187, score=0, max=0, min=-1, length=1112
[(0, 0.99), (-1, 0.01)]
Game round 150: epsilon=0.99, loss=0.002899999963119626, score=0, max=0, min=-1, length=1063
[(0, 0.99), (-1, 0.01)]
Game round 151: epsilon=0.99, loss=0.003700000001117587, score=0, max=0, min=-1, length=1036
[(0, 0.99), (-1, 0.01)]
Game round 152: epsilon=0.99, loss=0.004699999932199717, score

Game round 214: epsilon=0.99, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1154
[(0, 0.99), (-1, 0.01)]
Game round 215: epsilon=0.99, loss=0.002300000051036477, score=0, max=0, min=-1, length=1078
[(0, 0.99), (-1, 0.01)]
Game round 216: epsilon=0.98, loss=0.003100000089034438, score=0, max=0, min=-1, length=973
[(0, 0.99), (-1, 0.01)]
Game round 217: epsilon=0.98, loss=0.0044999998062849045, score=0, max=0, min=-1, length=1128
[(0, 0.99), (-1, 0.01)]
Game round 218: epsilon=0.98, loss=0.005900000222027302, score=0, max=0, min=-1, length=1072
[(0, 0.99), (-1, 0.01)]
Game round 219: epsilon=0.98, loss=0.003800000064074993, score=0, max=0, min=-1, length=1065
[(0, 0.99), (-1, 0.01)]
Game round 220: epsilon=0.98, loss=0.003599999938160181, score=0, max=0, min=-1, length=1138
[(0, 0.99), (-1, 0.01)]
Game round 221: epsilon=0.98, loss=0.0026000000070780516, score=0, max=0, min=-1, length=959
[(0, 0.99), (-1, 0.01)]
Game round 222: epsilon=0.98, loss=0.0038999998942017555, score

Game round 284: epsilon=0.98, loss=0.006899999920278788, score=0, max=0, min=-1, length=916
[(0, 0.99), (-1, 0.01)]
Game round 285: epsilon=0.98, loss=0.003800000064074993, score=0, max=0, min=-1, length=1121
[(0, 0.99), (-1, 0.01)]
Game round 286: epsilon=0.98, loss=0.003700000001117587, score=0, max=0, min=-1, length=1031
[(0, 0.99), (-1, 0.01)]
Game round 287: epsilon=0.98, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1088
[(0, 0.99), (-1, 0.01)]
Game round 288: epsilon=0.98, loss=0.002099999925121665, score=0, max=0, min=-1, length=1178
[(0, 0.99), (-1, 0.01)]
Game round 289: epsilon=0.98, loss=0.003599999938160181, score=0, max=0, min=-1, length=1017
[(0, 0.99), (-1, 0.01)]
Game round 290: epsilon=0.98, loss=0.0032999999821186066, score=0, max=0, min=-1, length=973
[(0, 0.99), (-1, 0.01)]
Game round 291: epsilon=0.98, loss=0.0026000000070780516, score=0, max=0, min=-1, length=966
[(0, 0.99), (-1, 0.01)]
Game round 292: epsilon=0.98, loss=0.002300000051036477, score=0

Game round 354: epsilon=0.98, loss=0.0031999999191612005, score=0, max=0, min=-1, length=1102
[(0, 0.99), (-1, 0.01)]
Game round 355: epsilon=0.98, loss=0.002300000051036477, score=0, max=0, min=-1, length=1044
[(0, 0.99), (-1, 0.01)]
Game round 356: epsilon=0.98, loss=0.00419999985024333, score=0, max=0, min=-1, length=950
[(0, 0.99), (-1, 0.01)]
Game round 357: epsilon=0.98, loss=0.00279999990016222, score=0, max=0, min=-1, length=1058
[(0, 0.99), (-1, 0.01)]
Game round 358: epsilon=0.98, loss=0.002199999988079071, score=0, max=0, min=-1, length=1085
[(0, 0.99), (-1, 0.01)]
Game round 359: epsilon=0.97, loss=0.00279999990016222, score=0, max=0, min=-1, length=1141
[(0, 0.99), (-1, 0.01)]
Game round 360: epsilon=0.97, loss=0.0032999999821186066, score=0, max=0, min=-1, length=1075
[(0, 0.99), (-1, 0.01)]
Game round 361: epsilon=0.97, loss=0.0019000000320374966, score=0, max=0, min=-1, length=1160
[(0, 0.99), (-1, 0.01)]
Game round 362: epsilon=0.97, loss=0.004100000020116568, score=0,

Game round 424: epsilon=0.97, loss=0.004399999976158142, score=0, max=0, min=-1, length=1028
[(0, 0.99), (-1, 0.01)]
Game round 425: epsilon=0.97, loss=0.003000000026077032, score=0, max=0, min=-1, length=1197
[(0, 0.99), (-1, 0.01)]
Game round 426: epsilon=0.97, loss=0.004000000189989805, score=0, max=0, min=-1, length=1085
[(0, 0.99), (-1, 0.01)]
Game round 427: epsilon=0.97, loss=0.004399999976158142, score=0, max=0, min=-1, length=1054
[(0, 0.99), (-1, 0.01)]
Game round 428: epsilon=0.97, loss=0.003599999938160181, score=0, max=0, min=-1, length=1032
[(0, 0.99), (-1, 0.01)]
Game round 429: epsilon=0.97, loss=0.00279999990016222, score=0, max=0, min=-1, length=1000
[(0, 0.99), (-1, 0.01)]
Game round 430: epsilon=0.97, loss=0.004699999932199717, score=0, max=0, min=-1, length=986
[(0, 0.99), (-1, 0.01)]
Game round 431: epsilon=0.97, loss=0.0019000000320374966, score=0, max=0, min=-1, length=1057
[(0, 0.99), (-1, 0.01)]
Game round 432: epsilon=0.97, loss=0.0035000001080334187, score=0

Game round 494: epsilon=0.97, loss=0.0026000000070780516, score=0, max=0, min=-1, length=1153
[(0, 0.99), (-1, 0.01)]
Game round 495: epsilon=0.97, loss=0.0024999999441206455, score=0, max=0, min=-1, length=936
[(0, 0.99), (-1, 0.01)]
Game round 496: epsilon=0.97, loss=0.0017000000225380063, score=0, max=0, min=-1, length=984
[(0, 0.99), (-1, 0.01)]
Game round 497: epsilon=0.97, loss=0.002199999988079071, score=0, max=0, min=-1, length=1175
[(0, 0.99), (-1, 0.01)]
Game round 498: epsilon=0.97, loss=0.004399999976158142, score=0, max=0, min=-1, length=1007
[(0, 0.99), (-1, 0.01)]
Game round 499: epsilon=0.97, loss=0.0031999999191612005, score=0, max=0, min=-1, length=1006
[(0, 0.99), (-1, 0.01)]
Game round 500: epsilon=0.97, loss=0.002899999963119626, score=0, max=0, min=-1, length=1135
[(0, 0.99), (-1, 0.01)]
Game round 501: epsilon=0.96, loss=0.0020000000949949026, score=0, max=0, min=-1, length=1124
[(0, 0.99), (-1, 0.01)]
Game round 502: epsilon=0.96, loss=0.0024999999441206455, sco

Game round 564: epsilon=0.96, loss=0.0024999999441206455, score=0, max=0, min=-1, length=982
[(0, 0.99), (-1, 0.01)]
Game round 565: epsilon=0.96, loss=0.00279999990016222, score=0, max=0, min=-1, length=1192
[(0, 0.99), (-1, 0.01)]
Game round 566: epsilon=0.96, loss=0.004399999976158142, score=0, max=0, min=-1, length=1083
[(0, 0.99), (-1, 0.01)]
Game round 567: epsilon=0.96, loss=0.00570000009611249, score=0, max=0, min=-1, length=1067
[(0, 0.99), (-1, 0.01)]
Game round 568: epsilon=0.96, loss=0.002400000113993883, score=0, max=0, min=-1, length=1005
[(0, 0.99), (-1, 0.01)]
Game round 569: epsilon=0.96, loss=0.003100000089034438, score=0, max=0, min=-1, length=1034
[(0, 0.99), (-1, 0.01)]
Game round 570: epsilon=0.96, loss=0.0024999999441206455, score=0, max=0, min=-1, length=1011
[(0, 0.99), (-1, 0.01)]
Game round 571: epsilon=0.96, loss=0.00430000014603138, score=0, max=0, min=-1, length=1075
[(0, 0.99), (-1, 0.01)]
Game round 572: epsilon=0.96, loss=0.00139999995008111, score=0, m

Game round 634: epsilon=0.96, loss=0.00279999990016222, score=0, max=0, min=-1, length=1057
[(0, 0.99), (-1, 0.01)]
Game round 635: epsilon=0.96, loss=0.0044999998062849045, score=0, max=0, min=-1, length=909
[(0, 0.99), (-1, 0.01)]
Game round 636: epsilon=0.96, loss=0.001500000013038516, score=0, max=0, min=-1, length=1177
[(0, 0.99), (-1, 0.01)]
Game round 637: epsilon=0.96, loss=0.002400000113993883, score=0, max=0, min=-1, length=1113
[(0, 0.99), (-1, 0.01)]
Game round 638: epsilon=0.96, loss=0.00279999990016222, score=0, max=0, min=-1, length=1001
[(0, 0.99), (-1, 0.01)]
Game round 639: epsilon=0.96, loss=0.0032999999821186066, score=0, max=0, min=-1, length=1104
[(0, 0.99), (-1, 0.01)]
Game round 640: epsilon=0.96, loss=0.0020000000949949026, score=0, max=0, min=-1, length=1099
[(0, 0.99), (-1, 0.01)]
Game round 641: epsilon=0.96, loss=0.0015999999595806003, score=0, max=0, min=-1, length=1095
[(0, 0.99), (-1, 0.01)]
Game round 642: epsilon=0.96, loss=0.0038999998942017555, score

Game round 704: epsilon=0.95, loss=0.0024999999441206455, score=0, max=0, min=-1, length=1157
[(0, 0.99), (-1, 0.01)]
Game round 705: epsilon=0.95, loss=0.003000000026077032, score=0, max=0, min=-1, length=1024
[(0, 0.99), (-1, 0.01)]
Game round 706: epsilon=0.95, loss=0.004999999888241291, score=0, max=0, min=-1, length=1066
[(0, 0.99), (-1, 0.01)]
Game round 707: epsilon=0.95, loss=0.0034000000450760126, score=0, max=0, min=-1, length=962
[(0, 0.99), (-1, 0.01)]
Game round 708: epsilon=0.95, loss=0.0026000000070780516, score=0, max=0, min=-1, length=1017
[(0, 0.99), (-1, 0.01)]
Game round 709: epsilon=0.95, loss=0.0017999999690800905, score=0, max=0, min=-1, length=1079
[(0, 0.99), (-1, 0.01)]
Game round 710: epsilon=0.95, loss=0.0027000000700354576, score=0, max=0, min=-1, length=1023
[(0, 0.99), (-1, 0.01)]
Game round 711: epsilon=0.95, loss=0.0024999999441206455, score=0, max=0, min=-1, length=926
[(0, 0.99), (-1, 0.01)]
Game round 712: epsilon=0.95, loss=0.003000000026077032, sco

Game round 774: epsilon=0.95, loss=0.0012000000569969416, score=0, max=0, min=-1, length=1086
[(0, 0.99), (-1, 0.01)]
Game round 775: epsilon=0.95, loss=0.004900000058114529, score=0, max=0, min=-1, length=1132
[(0, 0.99), (-1, 0.01)]
Game round 776: epsilon=0.95, loss=0.004699999932199717, score=0, max=0, min=-1, length=903
[(0, 0.99), (-1, 0.01)]
Game round 777: epsilon=0.95, loss=0.0026000000070780516, score=0, max=0, min=-1, length=1138
[(0, 0.99), (-1, 0.01)]
Game round 778: epsilon=0.95, loss=0.00419999985024333, score=0, max=0, min=-1, length=1158
[(0, 0.99), (-1, 0.01)]
Game round 779: epsilon=0.95, loss=0.0035000001080334187, score=0, max=0, min=-1, length=1060
[(0, 0.99), (-1, 0.01)]
Game round 780: epsilon=0.95, loss=0.0035000001080334187, score=0, max=0, min=-1, length=931
[(0, 0.99), (-1, 0.01)]
Game round 781: epsilon=0.95, loss=0.002899999963119626, score=0, max=0, min=-1, length=1072
[(0, 0.99), (-1, 0.01)]
Game round 782: epsilon=0.95, loss=0.0032999999821186066, score

Game round 844: epsilon=0.94, loss=0.0032999999821186066, score=0, max=0, min=-1, length=1216
[(0, 0.99), (-1, 0.01)]
Game round 845: epsilon=0.94, loss=0.004600000102072954, score=0, max=0, min=-1, length=943
[(0, 0.99), (-1, 0.01)]
Game round 846: epsilon=0.94, loss=0.0044999998062849045, score=0, max=0, min=-1, length=1039
[(0, 0.99), (-1, 0.01)]
Game round 847: epsilon=0.94, loss=0.0027000000700354576, score=0, max=0, min=-1, length=1071
[(0, 0.99), (-1, 0.01)]
Game round 848: epsilon=0.94, loss=0.002099999925121665, score=0, max=0, min=-1, length=1021
[(0, 0.99), (-1, 0.01)]
Game round 849: epsilon=0.94, loss=0.002300000051036477, score=0, max=0, min=-1, length=1052
[(0, 0.99), (-1, 0.01)]
Game round 850: epsilon=0.94, loss=0.0038999998942017555, score=0, max=0, min=-1, length=1070
[(0, 0.99), (-1, 0.01)]
Game round 851: epsilon=0.94, loss=0.002899999963119626, score=0, max=0, min=-1, length=1130
[(0, 0.99), (-1, 0.01)]
Game round 852: epsilon=0.94, loss=0.0019000000320374966, sco

Game round 914: epsilon=0.94, loss=0.0026000000070780516, score=0, max=0, min=-1, length=1160
[(0, 0.99), (-1, 0.01)]
Game round 915: epsilon=0.94, loss=0.002899999963119626, score=0, max=0, min=-1, length=1087
[(0, 0.99), (-1, 0.01)]
Game round 916: epsilon=0.94, loss=0.003100000089034438, score=0, max=0, min=-1, length=1000
[(0, 0.99), (-1, 0.01)]
Game round 917: epsilon=0.94, loss=0.00559999980032444, score=0, max=0, min=-1, length=1091
[(0, 0.99), (-1, 0.01)]
Game round 918: epsilon=0.94, loss=0.003100000089034438, score=0, max=0, min=-1, length=901
[(0, 0.99), (-1, 0.01)]
Game round 919: epsilon=0.94, loss=0.003700000001117587, score=0, max=0, min=-1, length=993
[(0, 0.99), (-1, 0.01)]
Game round 920: epsilon=0.94, loss=0.002300000051036477, score=0, max=0, min=-1, length=1099
[(0, 0.99), (-1, 0.01)]
Game round 921: epsilon=0.94, loss=0.003000000026077032, score=0, max=0, min=-1, length=917
[(0, 0.99), (-1, 0.01)]
Game round 922: epsilon=0.94, loss=0.002899999963119626, score=0, m

Game round 985: epsilon=0.93, loss=0.002400000113993883, score=0, max=0, min=-1, length=1019
[(0, 0.99), (-1, 0.01)]
Game round 986: epsilon=0.93, loss=0.0024999999441206455, score=0, max=0, min=-1, length=952
[(0, 0.99), (-1, 0.01)]
Game round 987: epsilon=0.93, loss=0.00279999990016222, score=0, max=0, min=-1, length=1045
[(0, 0.99), (-1, 0.01)]
Game round 988: epsilon=0.93, loss=0.002099999925121665, score=0, max=0, min=-1, length=1133
[(0, 0.99), (-1, 0.01)]
Game round 989: epsilon=0.93, loss=0.00430000014603138, score=0, max=0, min=-1, length=1109
[(0, 0.99), (-1, 0.01)]
Game round 990: epsilon=0.93, loss=0.004100000020116568, score=0, max=0, min=-1, length=1015
[(0, 0.99), (-1, 0.01)]
Game round 991: epsilon=0.93, loss=0.003800000064074993, score=0, max=0, min=-1, length=919
[(0, 0.99), (-1, 0.01)]
Game round 992: epsilon=0.93, loss=0.00430000014603138, score=0, max=0, min=-1, length=1111
[(0, 0.99), (-1, 0.01)]
Game round 993: epsilon=0.93, loss=0.0024999999441206455, score=0, m

Game round 1055: epsilon=0.93, loss=0.002400000113993883, score=0, max=0, min=-1, length=1166
[(0, 0.99), (-1, 0.01)]
Game round 1056: epsilon=0.93, loss=0.0017000000225380063, score=0, max=0, min=-1, length=1166
[(0, 0.99), (-1, 0.01)]
Game round 1057: epsilon=0.93, loss=0.0015999999595806003, score=0, max=0, min=-1, length=987
[(0, 0.99), (-1, 0.01)]
Game round 1058: epsilon=0.93, loss=0.0020000000949949026, score=0, max=0, min=-1, length=1150
[(0, 0.99), (-1, 0.01)]
Game round 1059: epsilon=0.93, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1013
[(0, 0.99), (-1, 0.01)]
Game round 1060: epsilon=0.93, loss=0.002899999963119626, score=0, max=0, min=-1, length=955
[(0, 0.99), (-1, 0.01)]
Game round 1061: epsilon=0.93, loss=0.0010000000474974513, score=0, max=0, min=-1, length=1138
[(0, 0.99), (-1, 0.01)]
Game round 1062: epsilon=0.93, loss=0.002199999988079071, score=0, max=0, min=-1, length=1001
[(0, 0.99), (-1, 0.01)]
Game round 1063: epsilon=0.93, loss=0.001599999959580

Game round 1125: epsilon=0.92, loss=0.0017999999690800905, score=0, max=0, min=-1, length=1034
[(0, 0.99), (-1, 0.01)]
Game round 1126: epsilon=0.92, loss=0.002199999988079071, score=0, max=0, min=-1, length=1107
[(0, 0.99), (-1, 0.01)]
Game round 1127: epsilon=0.92, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1069
[(0, 0.99), (-1, 0.01)]
Game round 1128: epsilon=0.92, loss=0.00279999990016222, score=0, max=0, min=-1, length=1047
[(0, 0.99), (-1, 0.01)]
Game round 1129: epsilon=0.92, loss=0.0038999998942017555, score=0, max=0, min=-1, length=883
[(0, 0.99), (-1, 0.01)]
Game round 1130: epsilon=0.92, loss=0.00430000014603138, score=0, max=0, min=-1, length=1062
[(0, 0.99), (-1, 0.01)]
Game round 1131: epsilon=0.92, loss=0.003599999938160181, score=0, max=0, min=-1, length=930
[(0, 0.99), (-1, 0.01)]
Game round 1132: epsilon=0.92, loss=0.002199999988079071, score=0, max=0, min=-1, length=1192
[(0, 0.99), (-1, 0.01)]
Game round 1133: epsilon=0.92, loss=0.003599999938160181,

Game round 1195: epsilon=0.92, loss=0.002400000113993883, score=0, max=0, min=-1, length=1057
[(0, 0.99), (-1, 0.01)]
Game round 1196: epsilon=0.92, loss=0.0020000000949949026, score=0, max=0, min=-1, length=1011
[(0, 0.99), (-1, 0.01)]
Game round 1197: epsilon=0.92, loss=0.002199999988079071, score=0, max=0, min=-1, length=1044
[(0, 0.99), (-1, 0.01)]
Game round 1198: epsilon=0.92, loss=0.002099999925121665, score=0, max=0, min=-1, length=1020
[(0, 0.99), (-1, 0.01)]
Game round 1199: epsilon=0.92, loss=0.003100000089034438, score=0, max=0, min=-1, length=962
[(0, 0.99), (-1, 0.01)]
Game round 1200: epsilon=0.92, loss=0.002099999925121665, score=0, max=0, min=-1, length=1010
[(0, 0.99), (-1, 0.01)]
Game round 1201: epsilon=0.92, loss=0.003000000026077032, score=0, max=0, min=-1, length=1032
[(0, 0.99), (-1, 0.01)]
Game round 1202: epsilon=0.92, loss=0.0032999999821186066, score=0, max=0, min=-1, length=1072
[(0, 0.99), (-1, 0.01)]
Game round 1203: epsilon=0.92, loss=0.00219999998807907

Game round 1265: epsilon=0.91, loss=0.0026000000070780516, score=0, max=0, min=-1, length=1033
[(0, 0.99), (-1, 0.01)]
Game round 1266: epsilon=0.91, loss=0.003100000089034438, score=0, max=0, min=-1, length=953
[(0, 0.99), (-1, 0.01)]
Game round 1267: epsilon=0.91, loss=0.0044999998062849045, score=0, max=0, min=-1, length=1056
[(0, 0.99), (-1, 0.01)]
Game round 1268: epsilon=0.91, loss=0.0038999998942017555, score=0, max=0, min=-1, length=1063
[(0, 0.99), (-1, 0.01)]
Game round 1269: epsilon=0.91, loss=0.002199999988079071, score=0, max=0, min=-1, length=1070
[(0, 0.99), (-1, 0.01)]
Game round 1270: epsilon=0.91, loss=0.0017999999690800905, score=0, max=0, min=-1, length=1023
[(0, 0.99), (-1, 0.01)]
Game round 1271: epsilon=0.91, loss=0.0024999999441206455, score=0, max=0, min=-1, length=1149
[(0, 0.99), (-1, 0.01)]
Game round 1272: epsilon=0.91, loss=0.005499999970197678, score=0, max=0, min=-1, length=1049
[(0, 0.99), (-1, 0.01)]
Game round 1273: epsilon=0.91, loss=0.00430000014603

Game round 1335: epsilon=0.91, loss=0.0026000000070780516, score=0, max=0, min=-1, length=1040
[(0, 0.99), (-1, 0.01)]
Game round 1336: epsilon=0.91, loss=0.0031999999191612005, score=0, max=0, min=-1, length=991
[(0, 0.99), (-1, 0.01)]
Game round 1337: epsilon=0.91, loss=0.003800000064074993, score=0, max=0, min=-1, length=948
[(0, 0.99), (-1, 0.01)]
Game round 1338: epsilon=0.91, loss=0.0024999999441206455, score=0, max=0, min=-1, length=1106
[(0, 0.99), (-1, 0.01)]
Game round 1339: epsilon=0.91, loss=0.0034000000450760126, score=0, max=0, min=-1, length=962
[(0, 0.99), (-1, 0.01)]
Game round 1340: epsilon=0.91, loss=0.0026000000070780516, score=0, max=0, min=-1, length=1018
[(0, 0.99), (-1, 0.01)]
Game round 1341: epsilon=0.91, loss=0.002899999963119626, score=0, max=0, min=-1, length=1073
[(0, 0.99), (-1, 0.01)]
Game round 1342: epsilon=0.91, loss=0.00279999990016222, score=0, max=0, min=-1, length=1075
[(0, 0.99), (-1, 0.01)]
Game round 1343: epsilon=0.91, loss=0.00249999994412064

Game round 1405: epsilon=0.9, loss=0.002300000051036477, score=0, max=0, min=-1, length=1135
[(0, 0.99), (-1, 0.01)]
Game round 1406: epsilon=0.9, loss=0.0017999999690800905, score=0, max=0, min=-1, length=1046
[(0, 0.99), (-1, 0.01)]
Game round 1407: epsilon=0.9, loss=0.0017999999690800905, score=0, max=0, min=-1, length=985
[(0, 0.99), (-1, 0.01)]
Game round 1408: epsilon=0.9, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1070
[(0, 0.99), (-1, 0.01)]
Game round 1409: epsilon=0.9, loss=0.002899999963119626, score=0, max=0, min=-1, length=1078
[(0, 0.99), (-1, 0.01)]
Game round 1410: epsilon=0.9, loss=0.0024999999441206455, score=0, max=0, min=-1, length=1011
[(0, 0.99), (-1, 0.01)]
Game round 1411: epsilon=0.9, loss=0.0020000000949949026, score=0, max=0, min=-1, length=989
[(0, 0.99), (-1, 0.01)]
Game round 1412: epsilon=0.9, loss=0.0024999999441206455, score=0, max=0, min=-1, length=1104
[(0, 0.99), (-1, 0.01)]
Game round 1413: epsilon=0.9, loss=0.0019000000320374966, sc

Game round 1476: epsilon=0.9, loss=0.0032999999821186066, score=0, max=0, min=-1, length=1001
[(0, 0.99), (-1, 0.01)]
Game round 1477: epsilon=0.9, loss=0.003599999938160181, score=0, max=0, min=-1, length=1005
[(0, 0.99), (-1, 0.01)]
Game round 1478: epsilon=0.9, loss=0.003599999938160181, score=0, max=0, min=-1, length=1086
[(0, 0.99), (-1, 0.01)]
Game round 1479: epsilon=0.9, loss=0.0027000000700354576, score=0, max=0, min=-1, length=898
[(0, 0.99), (-1, 0.01)]
Game round 1480: epsilon=0.9, loss=0.002899999963119626, score=0, max=0, min=-1, length=1080
[(0, 0.99), (-1, 0.01)]
Game round 1481: epsilon=0.9, loss=0.0026000000070780516, score=0, max=0, min=-1, length=910
[(0, 0.99), (-1, 0.01)]
Game round 1482: epsilon=0.9, loss=0.0017000000225380063, score=0, max=0, min=-1, length=1112
[(0, 0.99), (-1, 0.01)]
Game round 1483: epsilon=0.9, loss=0.002099999925121665, score=0, max=0, min=-1, length=1043
[(0, 0.99), (-1, 0.01)]
Game round 1484: epsilon=0.9, loss=0.003100000089034438, score

Game round 1546: epsilon=0.89, loss=0.0026000000070780516, score=0, max=0, min=-1, length=1088
[(0, 0.99), (-1, 0.01)]
Game round 1547: epsilon=0.89, loss=0.0027000000700354576, score=0, max=0, min=-1, length=1127
[(0, 0.99), (-1, 0.01)]
Game round 1548: epsilon=0.89, loss=0.003000000026077032, score=0, max=0, min=-1, length=979
[(0, 0.99), (-1, 0.01)]
Game round 1549: epsilon=0.89, loss=0.00139999995008111, score=0, max=0, min=-1, length=1053
[(0, 0.99), (-1, 0.01)]
Game round 1550: epsilon=0.89, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1035
[(0, 0.99), (-1, 0.01)]
Game round 1551: epsilon=0.89, loss=0.002400000113993883, score=0, max=0, min=-1, length=925
[(0, 0.99), (-1, 0.01)]
Game round 1552: epsilon=0.89, loss=0.003700000001117587, score=0, max=1, min=-1, length=996
[(0, 0.99), (1, 0.0), (-1, 0.01)]
Game round 1553: epsilon=0.89, loss=0.0044999998062849045, score=0, max=0, min=-1, length=907
[(0, 0.99), (-1, 0.01)]
Game round 1554: epsilon=0.89, loss=0.002499999

Game round 1616: epsilon=0.89, loss=0.002099999925121665, score=0, max=0, min=-1, length=1011
[(0, 0.99), (-1, 0.01)]
Game round 1617: epsilon=0.89, loss=0.0026000000070780516, score=0, max=0, min=-1, length=1024
[(0, 0.99), (-1, 0.01)]
Game round 1618: epsilon=0.89, loss=0.0017999999690800905, score=0, max=0, min=-1, length=1070
[(0, 0.99), (-1, 0.01)]
Game round 1619: epsilon=0.89, loss=0.0032999999821186066, score=0, max=0, min=-1, length=1004
[(0, 0.99), (-1, 0.01)]
Game round 1620: epsilon=0.89, loss=0.002300000051036477, score=0, max=0, min=-1, length=1073
[(0, 0.99), (-1, 0.01)]
Game round 1621: epsilon=0.89, loss=0.003599999938160181, score=0, max=0, min=-1, length=1086
[(0, 0.99), (-1, 0.01)]
Game round 1622: epsilon=0.89, loss=0.002400000113993883, score=0, max=0, min=-1, length=987
[(0, 0.99), (-1, 0.01)]
Game round 1623: epsilon=0.89, loss=0.0038999998942017555, score=0, max=0, min=-1, length=1024
[(0, 0.99), (-1, 0.01)]
Game round 1624: epsilon=0.89, loss=0.005299999844282

Game round 1686: epsilon=0.88, loss=0.0024999999441206455, score=0, max=0, min=-1, length=1058
[(0, 0.99), (-1, 0.01)]
Game round 1687: epsilon=0.88, loss=0.0019000000320374966, score=0, max=0, min=-1, length=952
[(0, 0.99), (-1, 0.01)]
Game round 1688: epsilon=0.88, loss=0.002400000113993883, score=0, max=0, min=-1, length=1077
[(0, 0.99), (-1, 0.01)]
Game round 1689: epsilon=0.88, loss=0.003800000064074993, score=0, max=0, min=-1, length=982
[(0, 0.99), (-1, 0.01)]
Game round 1690: epsilon=0.88, loss=0.002400000113993883, score=0, max=0, min=-1, length=984
[(0, 0.99), (-1, 0.01)]
Game round 1691: epsilon=0.88, loss=0.002300000051036477, score=0, max=0, min=-1, length=998
[(0, 0.99), (-1, 0.01)]
Game round 1692: epsilon=0.88, loss=0.002300000051036477, score=0, max=0, min=-1, length=969
[(0, 0.99), (-1, 0.01)]
Game round 1693: epsilon=0.88, loss=0.0017999999690800905, score=0, max=0, min=-1, length=962
[(0, 0.99), (-1, 0.01)]
Game round 1694: epsilon=0.88, loss=0.004399999976158142, s

Game round 1756: epsilon=0.88, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1000
[(0, 0.99), (-1, 0.01)]
Game round 1757: epsilon=0.88, loss=0.003800000064074993, score=0, max=0, min=-1, length=843
[(0, 0.99), (-1, 0.01)]
Game round 1758: epsilon=0.88, loss=0.004800000227987766, score=0, max=0, min=-1, length=999
[(0, 0.99), (-1, 0.01)]
Game round 1759: epsilon=0.88, loss=0.004000000189989805, score=0, max=0, min=-1, length=760
[(0, 0.99), (-1, 0.01)]
Game round 1760: epsilon=0.88, loss=0.0031999999191612005, score=0, max=0, min=-1, length=931
[(0, 0.99), (-1, 0.01)]
Game round 1761: epsilon=0.88, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1039
[(0, 0.99), (-1, 0.01)]
Game round 1762: epsilon=0.88, loss=0.0017999999690800905, score=0, max=0, min=-1, length=1114
[(0, 0.99), (-1, 0.01)]
Game round 1763: epsilon=0.88, loss=0.0020000000949949026, score=0, max=0, min=-1, length=957
[(0, 0.99), (-1, 0.01)]
Game round 1764: epsilon=0.88, loss=0.002099999925121665

Game round 1826: epsilon=0.87, loss=0.0015999999595806003, score=0, max=0, min=-1, length=1077
[(0, 0.99), (-1, 0.01)]
Game round 1827: epsilon=0.87, loss=0.002099999925121665, score=0, max=0, min=-1, length=921
[(0, 0.99), (-1, 0.01)]
Game round 1828: epsilon=0.87, loss=0.003599999938160181, score=0, max=0, min=-1, length=943
[(0, 0.99), (-1, 0.01)]
Game round 1829: epsilon=0.87, loss=0.002300000051036477, score=0, max=0, min=-1, length=1054
[(0, 0.99), (-1, 0.01)]
Game round 1830: epsilon=0.87, loss=0.0017000000225380063, score=0, max=0, min=-1, length=1088
[(0, 0.99), (-1, 0.01)]
Game round 1831: epsilon=0.87, loss=0.002300000051036477, score=0, max=0, min=-1, length=1186
[(0, 0.99), (-1, 0.01)]
Game round 1832: epsilon=0.87, loss=0.0031999999191612005, score=0, max=0, min=-1, length=943
[(0, 0.99), (-1, 0.01)]
Game round 1833: epsilon=0.87, loss=0.003800000064074993, score=0, max=0, min=-1, length=1041
[(0, 0.99), (-1, 0.01)]
Game round 1834: epsilon=0.87, loss=0.003000000026077032

Game round 1896: epsilon=0.87, loss=0.003700000001117587, score=0, max=0, min=-1, length=938
[(0, 0.99), (-1, 0.01)]
Game round 1897: epsilon=0.87, loss=0.002300000051036477, score=0, max=0, min=-1, length=973
[(0, 0.99), (-1, 0.01)]
Game round 1898: epsilon=0.87, loss=0.0019000000320374966, score=0, max=0, min=-1, length=984
[(0, 0.99), (-1, 0.01)]
Game round 1899: epsilon=0.87, loss=0.0027000000700354576, score=0, max=0, min=-1, length=1046
[(0, 0.99), (-1, 0.01)]
Game round 1900: epsilon=0.87, loss=0.0013000000035390258, score=0, max=0, min=-1, length=1047
[(0, 0.99), (-1, 0.01)]
Game round 1901: epsilon=0.87, loss=0.00279999990016222, score=0, max=0, min=-1, length=993
[(0, 0.99), (-1, 0.01)]
Game round 1902: epsilon=0.87, loss=0.0024999999441206455, score=0, max=0, min=-1, length=913
[(0, 0.99), (-1, 0.01)]
Game round 1903: epsilon=0.87, loss=0.002899999963119626, score=0, max=0, min=-1, length=1084
[(0, 0.99), (-1, 0.01)]
Game round 1904: epsilon=0.87, loss=0.003599999938160181, 

Game round 1966: epsilon=0.86, loss=0.004000000189989805, score=0, max=0, min=-1, length=983
[(0, 0.99), (-1, 0.01)]
Game round 1967: epsilon=0.86, loss=0.0020000000949949026, score=0, max=0, min=-1, length=986
[(0, 0.99), (-1, 0.01)]
Game round 1968: epsilon=0.86, loss=0.004800000227987766, score=0, max=0, min=-1, length=832
[(0, 0.99), (-1, 0.01)]
Game round 1969: epsilon=0.86, loss=0.0026000000070780516, score=0, max=0, min=-1, length=955
[(0, 0.99), (-1, 0.01)]
Game round 1970: epsilon=0.86, loss=0.002199999988079071, score=0, max=0, min=-1, length=931
[(0, 0.99), (-1, 0.01)]
Game round 1971: epsilon=0.86, loss=0.00279999990016222, score=0, max=0, min=-1, length=1081
[(0, 0.99), (-1, 0.01)]
Game round 1972: epsilon=0.86, loss=0.004699999932199717, score=0, max=0, min=-1, length=1049
[(0, 0.99), (-1, 0.01)]
Game round 1973: epsilon=0.86, loss=0.002300000051036477, score=0, max=0, min=-1, length=952
[(0, 0.99), (-1, 0.01)]
Game round 1974: epsilon=0.86, loss=0.002899999963119626, sco

Game round 2036: epsilon=0.86, loss=0.0044999998062849045, score=0, max=0, min=-1, length=1040
[(0, 0.99), (-1, 0.01)]
Game round 2037: epsilon=0.86, loss=0.003599999938160181, score=0, max=0, min=-1, length=906
[(0, 0.99), (-1, 0.01)]
Game round 2038: epsilon=0.86, loss=0.0035000001080334187, score=0, max=0, min=-1, length=1006
[(0, 0.99), (-1, 0.01)]
Game round 2039: epsilon=0.86, loss=0.003100000089034438, score=0, max=0, min=-1, length=942
[(0, 0.99), (-1, 0.01)]
Game round 2040: epsilon=0.86, loss=0.002400000113993883, score=0, max=0, min=-1, length=970
[(0, 0.99), (-1, 0.01)]
Game round 2041: epsilon=0.86, loss=0.0032999999821186066, score=0, max=0, min=-1, length=968
[(0, 0.99), (-1, 0.01)]
Game round 2042: epsilon=0.86, loss=0.0035000001080334187, score=0, max=0, min=-1, length=942
[(0, 0.99), (-1, 0.01)]
Game round 2043: epsilon=0.86, loss=0.00279999990016222, score=0, max=0, min=-1, length=993
[(0, 0.99), (-1, 0.01)]
Game round 2044: epsilon=0.86, loss=0.0035000001080334187, 

Game round 2106: epsilon=0.85, loss=0.002400000113993883, score=0, max=0, min=-1, length=928
[(0, 0.99), (-1, 0.01)]
Game round 2107: epsilon=0.85, loss=0.00279999990016222, score=0, max=0, min=-1, length=1027
[(0, 0.99), (-1, 0.01)]
Game round 2108: epsilon=0.85, loss=0.005799999926239252, score=0, max=0, min=-1, length=926
[(0, 0.99), (-1, 0.01)]
Game round 2109: epsilon=0.85, loss=0.002099999925121665, score=0, max=0, min=-1, length=931
[(0, 0.99), (-1, 0.01)]
Game round 2110: epsilon=0.85, loss=0.003700000001117587, score=0, max=0, min=-1, length=1027
[(0, 0.99), (-1, 0.01)]
Game round 2111: epsilon=0.85, loss=0.0027000000700354576, score=0, max=0, min=-1, length=1071
[(0, 0.99), (-1, 0.01)]
Game round 2112: epsilon=0.85, loss=0.00419999985024333, score=0, max=0, min=-1, length=1002
[(0, 0.99), (-1, 0.01)]
Game round 2113: epsilon=0.85, loss=0.003100000089034438, score=0, max=0, min=-1, length=1038
[(0, 0.99), (-1, 0.01)]
Game round 2114: epsilon=0.85, loss=0.003599999938160181, sc

Game round 2176: epsilon=0.85, loss=0.003800000064074993, score=0, max=0, min=-1, length=943
[(0, 0.99), (-1, 0.01)]
Game round 2177: epsilon=0.85, loss=0.003000000026077032, score=0, max=0, min=-1, length=986
[(0, 0.99), (-1, 0.01)]
Game round 2178: epsilon=0.85, loss=0.0024999999441206455, score=0, max=0, min=-1, length=897
[(0, 0.99), (-1, 0.01)]
Game round 2179: epsilon=0.85, loss=0.0035000001080334187, score=0, max=0, min=-1, length=990
[(0, 0.99), (-1, 0.01)]
Game round 2180: epsilon=0.85, loss=0.003700000001117587, score=0, max=0, min=-1, length=939
[(0, 0.99), (-1, 0.01)]
Game round 2181: epsilon=0.85, loss=0.002099999925121665, score=0, max=0, min=-1, length=982
[(0, 0.99), (-1, 0.01)]
Game round 2182: epsilon=0.85, loss=0.0032999999821186066, score=0, max=0, min=-1, length=949
[(0, 0.99), (-1, 0.01)]
Game round 2183: epsilon=0.85, loss=0.0008999999845400453, score=0, max=0, min=-1, length=917
[(0, 0.99), (-1, 0.01)]
Game round 2184: epsilon=0.85, loss=0.0027000000700354576, s

Game round 2246: epsilon=0.84, loss=0.003000000026077032, score=0, max=0, min=-1, length=855
[(0, 0.99), (-1, 0.01)]
Game round 2247: epsilon=0.84, loss=0.0012000000569969416, score=0, max=0, min=-1, length=951
[(0, 0.99), (-1, 0.01)]
Game round 2248: epsilon=0.84, loss=0.003100000089034438, score=0, max=0, min=-1, length=969
[(0, 0.99), (-1, 0.01)]
Game round 2249: epsilon=0.84, loss=0.005200000014156103, score=0, max=0, min=-1, length=902
[(0, 0.99), (-1, 0.01)]
Game round 2250: epsilon=0.84, loss=0.0038999998942017555, score=0, max=0, min=-1, length=912
[(0, 0.99), (-1, 0.01)]
Game round 2251: epsilon=0.84, loss=0.004399999976158142, score=0, max=0, min=-1, length=870
[(0, 0.99), (-1, 0.01)]
Game round 2252: epsilon=0.84, loss=0.0038999998942017555, score=0, max=0, min=-1, length=994
[(0, 0.99), (-1, 0.01)]
Game round 2253: epsilon=0.84, loss=0.0031999999191612005, score=0, max=0, min=-1, length=1003
[(0, 0.99), (-1, 0.01)]
Game round 2254: epsilon=0.84, loss=0.004600000102072954, s

Game round 2316: epsilon=0.84, loss=0.0024999999441206455, score=0, max=0, min=-1, length=1084
[(0, 0.99), (-1, 0.01)]
Game round 2317: epsilon=0.84, loss=0.003599999938160181, score=0, max=0, min=-1, length=832
[(0, 0.99), (-1, 0.01)]
Game round 2318: epsilon=0.84, loss=0.004600000102072954, score=0, max=0, min=-1, length=918
[(0, 0.99), (-1, 0.01)]
Game round 2319: epsilon=0.84, loss=0.0031999999191612005, score=0, max=0, min=-1, length=1084
[(0, 0.99), (-1, 0.01)]
Game round 2320: epsilon=0.84, loss=0.0019000000320374966, score=0, max=0, min=-1, length=948
[(0, 0.99), (-1, 0.01)]
Game round 2321: epsilon=0.84, loss=0.002899999963119626, score=0, max=0, min=-1, length=918
[(0, 0.99), (-1, 0.01)]
Game round 2322: epsilon=0.84, loss=0.0038999998942017555, score=0, max=0, min=-1, length=925
[(0, 0.99), (-1, 0.01)]
Game round 2323: epsilon=0.84, loss=0.0032999999821186066, score=0, max=0, min=-1, length=949
[(0, 0.99), (-1, 0.01)]
Game round 2324: epsilon=0.84, loss=0.0034000000450760126

Game round 2386: epsilon=0.83, loss=0.004399999976158142, score=0, max=0, min=-1, length=1022
[(0, 0.99), (-1, 0.01)]
Game round 2387: epsilon=0.83, loss=0.00279999990016222, score=0, max=0, min=-1, length=974
[(0, 0.99), (-1, 0.01)]
Game round 2388: epsilon=0.83, loss=0.0038999998942017555, score=0, max=0, min=-1, length=947
[(0, 0.99), (-1, 0.01)]
Game round 2389: epsilon=0.83, loss=0.0017999999690800905, score=0, max=0, min=-1, length=1048
[(0, 0.99), (-1, 0.01)]
Game round 2390: epsilon=0.83, loss=0.0032999999821186066, score=0, max=0, min=-1, length=1050
[(0, 0.99), (-1, 0.01)]
Game round 2391: epsilon=0.83, loss=0.002199999988079071, score=0, max=0, min=-1, length=978
[(0, 0.99), (-1, 0.01)]
Game round 2392: epsilon=0.83, loss=0.0019000000320374966, score=0, max=0, min=-1, length=946
[(0, 0.99), (-1, 0.01)]
Game round 2393: epsilon=0.83, loss=0.002199999988079071, score=0, max=0, min=-1, length=965
[(0, 0.99), (-1, 0.01)]
Game round 2394: epsilon=0.83, loss=0.002099999925121665, 

Game round 2456: epsilon=0.83, loss=0.002899999963119626, score=0, max=0, min=-1, length=986
[(0, 0.99), (-1, 0.01)]
Game round 2457: epsilon=0.83, loss=0.0027000000700354576, score=0, max=0, min=-1, length=937
[(0, 0.99), (-1, 0.01)]
Game round 2458: epsilon=0.83, loss=0.003000000026077032, score=0, max=0, min=-1, length=980
[(0, 0.99), (-1, 0.01)]
Game round 2459: epsilon=0.83, loss=0.00279999990016222, score=0, max=0, min=-1, length=936
[(0, 0.99), (-1, 0.01)]
Game round 2460: epsilon=0.83, loss=0.0020000000949949026, score=0, max=0, min=-1, length=934
[(0, 0.99), (-1, 0.01)]
Game round 2461: epsilon=0.83, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1008
[(0, 0.99), (-1, 0.01)]
Game round 2462: epsilon=0.83, loss=0.0031999999191612005, score=0, max=0, min=-1, length=931
[(0, 0.99), (-1, 0.01)]
Game round 2463: epsilon=0.83, loss=0.003599999938160181, score=0, max=0, min=-1, length=846
[(0, 0.99), (-1, 0.01)]
Game round 2464: epsilon=0.83, loss=0.0032999999821186066, s

Game round 2526: epsilon=0.82, loss=0.0026000000070780516, score=0, max=0, min=-1, length=905
[(0, 0.99), (-1, 0.01)]
Game round 2527: epsilon=0.82, loss=0.0015999999595806003, score=0, max=0, min=-1, length=995
[(0, 0.99), (-1, 0.01)]
Game round 2528: epsilon=0.82, loss=0.0027000000700354576, score=0, max=0, min=-1, length=924
[(0, 0.99), (-1, 0.01)]
Game round 2529: epsilon=0.82, loss=0.0017999999690800905, score=0, max=0, min=-1, length=946
[(0, 0.99), (-1, 0.01)]
Game round 2530: epsilon=0.82, loss=0.0026000000070780516, score=0, max=0, min=-1, length=937
[(0, 0.99), (-1, 0.01)]
Game round 2531: epsilon=0.82, loss=0.002199999988079071, score=0, max=0, min=-1, length=971
[(0, 0.99), (-1, 0.01)]
Game round 2532: epsilon=0.82, loss=0.00419999985024333, score=0, max=0, min=-1, length=1001
[(0, 0.99), (-1, 0.01)]
Game round 2533: epsilon=0.82, loss=0.002199999988079071, score=0, max=0, min=-1, length=862
[(0, 0.99), (-1, 0.01)]
Game round 2534: epsilon=0.82, loss=0.007199999876320362, s

Game round 2596: epsilon=0.82, loss=0.004600000102072954, score=0, max=0, min=-1, length=977
[(0, 0.99), (-1, 0.01)]
Game round 2597: epsilon=0.82, loss=0.0027000000700354576, score=0, max=0, min=-1, length=987
[(0, 0.99), (-1, 0.01)]
Game round 2598: epsilon=0.82, loss=0.0017999999690800905, score=0, max=0, min=-1, length=917
[(0, 0.99), (-1, 0.01)]
Game round 2599: epsilon=0.82, loss=0.001500000013038516, score=0, max=0, min=-1, length=1038
[(0, 0.99), (-1, 0.01)]
Game round 2600: epsilon=0.82, loss=0.002199999988079071, score=0, max=0, min=-1, length=947
[(0, 0.99), (-1, 0.01)]
Game round 2601: epsilon=0.82, loss=0.002400000113993883, score=0, max=0, min=-1, length=808
[(0, 0.99), (-1, 0.01)]
Game round 2602: epsilon=0.82, loss=0.0012000000569969416, score=0, max=0, min=-1, length=877
[(0, 0.99), (-1, 0.01)]
Game round 2603: epsilon=0.82, loss=0.0031999999191612005, score=0, max=0, min=-1, length=856
[(0, 0.99), (-1, 0.01)]
Game round 2604: epsilon=0.82, loss=0.0017000000225380063, 

Game round 2666: epsilon=0.81, loss=0.0044999998062849045, score=0, max=0, min=-1, length=988
[(0, 0.99), (-1, 0.01)]
Game round 2667: epsilon=0.81, loss=0.005400000140070915, score=0, max=0, min=-1, length=814
[(0, 0.99), (-1, 0.01)]
Game round 2668: epsilon=0.81, loss=0.004000000189989805, score=0, max=0, min=-1, length=814
[(0, 0.99), (-1, 0.01)]
Game round 2669: epsilon=0.81, loss=0.002099999925121665, score=0, max=0, min=-1, length=946
[(0, 0.99), (-1, 0.01)]
Game round 2670: epsilon=0.81, loss=0.002199999988079071, score=0, max=0, min=-1, length=1023
[(0, 0.99), (-1, 0.01)]
Game round 2671: epsilon=0.81, loss=0.0031999999191612005, score=0, max=0, min=-1, length=1022
[(0, 0.99), (-1, 0.01)]
Game round 2672: epsilon=0.81, loss=0.0044999998062849045, score=0, max=0, min=-1, length=877
[(0, 0.99), (-1, 0.01)]
Game round 2673: epsilon=0.81, loss=0.004699999932199717, score=0, max=0, min=-1, length=878
[(0, 0.99), (-1, 0.01)]
Game round 2674: epsilon=0.81, loss=0.002400000113993883, s

Game round 2736: epsilon=0.81, loss=0.003700000001117587, score=0, max=0, min=-1, length=1017
[(0, 0.99), (-1, 0.01)]
Game round 2737: epsilon=0.81, loss=0.0032999999821186066, score=0, max=0, min=-1, length=963
[(0, 0.99), (-1, 0.01)]
Game round 2738: epsilon=0.81, loss=0.0035000001080334187, score=0, max=0, min=-1, length=883
[(0, 0.99), (-1, 0.01)]
Game round 2739: epsilon=0.81, loss=0.004100000020116568, score=0, max=0, min=-1, length=944
[(0, 0.99), (-1, 0.01)]
Game round 2740: epsilon=0.81, loss=0.003000000026077032, score=0, max=0, min=-1, length=901
[(0, 0.99), (-1, 0.01)]
Game round 2741: epsilon=0.81, loss=0.003800000064074993, score=0, max=0, min=-1, length=959
[(0, 0.99), (-1, 0.01)]
Game round 2742: epsilon=0.81, loss=0.003000000026077032, score=0, max=0, min=-1, length=861
[(0, 0.99), (-1, 0.01)]
Game round 2743: epsilon=0.81, loss=0.0034000000450760126, score=0, max=0, min=-1, length=911
[(0, 0.99), (-1, 0.01)]
Game round 2744: epsilon=0.81, loss=0.005200000014156103, sc

Game round 2806: epsilon=0.8, loss=0.003000000026077032, score=0, max=0, min=-1, length=839
[(0, 0.99), (-1, 0.01)]
Game round 2807: epsilon=0.8, loss=0.0027000000700354576, score=0, max=0, min=-1, length=880
[(0, 0.99), (-1, 0.01)]
Game round 2808: epsilon=0.8, loss=0.0032999999821186066, score=0, max=0, min=-1, length=1008
[(0, 0.99), (-1, 0.01)]
Game round 2809: epsilon=0.8, loss=0.003000000026077032, score=0, max=0, min=-1, length=932
[(0, 0.99), (-1, 0.01)]
Game round 2810: epsilon=0.8, loss=0.003599999938160181, score=0, max=0, min=-1, length=824
[(0, 0.99), (-1, 0.01)]
Game round 2811: epsilon=0.8, loss=0.0031999999191612005, score=0, max=0, min=-1, length=920
[(0, 0.99), (-1, 0.01)]
Game round 2812: epsilon=0.8, loss=0.005400000140070915, score=0, max=0, min=-1, length=839
[(0, 0.99), (-1, 0.01)]
Game round 2813: epsilon=0.8, loss=0.0026000000070780516, score=0, max=0, min=-1, length=1017
[(0, 0.99), (-1, 0.01)]
Game round 2814: epsilon=0.8, loss=0.003800000064074993, score=0, 

Game round 2877: epsilon=0.8, loss=0.004999999888241291, score=0, max=0, min=-1, length=947
[(0, 0.99), (-1, 0.01)]
Game round 2878: epsilon=0.8, loss=0.00419999985024333, score=0, max=0, min=-1, length=807
[(0, 0.99), (-1, 0.01)]
Game round 2879: epsilon=0.8, loss=0.0052999998442828655, score=0, max=0, min=-1, length=913
[(0, 0.99), (-1, 0.01)]
Game round 2880: epsilon=0.8, loss=0.004100000020116568, score=0, max=0, min=-1, length=931
[(0, 0.99), (-1, 0.01)]
Game round 2881: epsilon=0.8, loss=0.0044999998062849045, score=0, max=0, min=-1, length=948
[(0, 0.99), (-1, 0.01)]
Game round 2882: epsilon=0.8, loss=0.003700000001117587, score=0, max=0, min=-1, length=892
[(0, 0.99), (-1, 0.01)]
Game round 2883: epsilon=0.8, loss=0.0024999999441206455, score=0, max=0, min=-1, length=1022
[(0, 0.99), (-1, 0.01)]
Game round 2884: epsilon=0.8, loss=0.0027000000700354576, score=0, max=0, min=-1, length=869
[(0, 0.99), (-1, 0.01)]
Game round 2885: epsilon=0.8, loss=0.004699999932199717, score=0, ma

Game round 2948: epsilon=0.79, loss=0.003100000089034438, score=0, max=0, min=-1, length=983
[(0, 0.99), (-1, 0.01)]
Game round 2949: epsilon=0.79, loss=0.003800000064074993, score=0, max=0, min=-1, length=911
[(0, 0.99), (-1, 0.01)]
Game round 2950: epsilon=0.79, loss=0.0038999998942017555, score=0, max=0, min=-1, length=979
[(0, 0.99), (-1, 0.01)]
Game round 2951: epsilon=0.79, loss=0.0038999998942017555, score=0, max=0, min=-1, length=891
[(0, 0.99), (-1, 0.01)]
Game round 2952: epsilon=0.79, loss=0.0035000001080334187, score=0, max=0, min=-1, length=857
[(0, 0.99), (-1, 0.01)]
Game round 2953: epsilon=0.79, loss=0.0038999998942017555, score=0, max=0, min=-1, length=915
[(0, 0.99), (-1, 0.01)]
Game round 2954: epsilon=0.79, loss=0.0024999999441206455, score=0, max=0, min=-1, length=1082
[(0, 0.99), (-1, 0.01)]
Game round 2955: epsilon=0.79, loss=0.0038999998942017555, score=0, max=0, min=-1, length=916
[(0, 0.99), (-1, 0.01)]
Game round 2956: epsilon=0.79, loss=0.0026000000070780516

Game round 3018: epsilon=0.79, loss=0.003000000026077032, score=0, max=0, min=-1, length=996
[(0, 0.99), (-1, 0.01)]
Game round 3019: epsilon=0.79, loss=0.004100000020116568, score=0, max=0, min=-1, length=979
[(0, 0.99), (-1, 0.01)]
Game round 3020: epsilon=0.79, loss=0.00430000014603138, score=0, max=0, min=-1, length=920
[(0, 0.99), (-1, 0.01)]
Game round 3021: epsilon=0.79, loss=0.002300000051036477, score=0, max=0, min=-1, length=923
[(0, 0.99), (-1, 0.01)]
Game round 3022: epsilon=0.79, loss=0.002199999988079071, score=0, max=0, min=-1, length=940
[(0, 0.99), (-1, 0.01)]
Game round 3023: epsilon=0.79, loss=0.002400000113993883, score=0, max=0, min=-1, length=934
[(0, 0.99), (-1, 0.01)]
Game round 3024: epsilon=0.79, loss=0.0031999999191612005, score=0, max=0, min=-1, length=797
[(0, 0.99), (-1, 0.01)]
Game round 3025: epsilon=0.79, loss=0.0017000000225380063, score=0, max=0, min=-1, length=1031
[(0, 0.99), (-1, 0.01)]
Game round 3026: epsilon=0.79, loss=0.00559999980032444, score

Game round 3088: epsilon=0.78, loss=0.0026000000070780516, score=0, max=0, min=-1, length=991
[(0, 0.99), (-1, 0.01)]
Game round 3089: epsilon=0.78, loss=0.002400000113993883, score=0, max=0, min=-1, length=949
[(0, 0.99), (-1, 0.01)]
Game round 3090: epsilon=0.78, loss=0.0031999999191612005, score=0, max=0, min=-1, length=870
[(0, 0.99), (-1, 0.01)]
Game round 3091: epsilon=0.78, loss=0.0034000000450760126, score=0, max=0, min=-1, length=898
[(0, 0.99), (-1, 0.01)]
Game round 3092: epsilon=0.78, loss=0.0032999999821186066, score=0, max=0, min=-1, length=838
[(0, 0.99), (-1, 0.01)]
Game round 3093: epsilon=0.78, loss=0.0020000000949949026, score=0, max=0, min=-1, length=924
[(0, 0.99), (-1, 0.01)]
Game round 3094: epsilon=0.78, loss=0.0017999999690800905, score=0, max=0, min=-1, length=928
[(0, 0.99), (-1, 0.01)]
Game round 3095: epsilon=0.78, loss=0.00559999980032444, score=0, max=0, min=-1, length=982
[(0, 0.99), (-1, 0.01)]
Game round 3096: epsilon=0.78, loss=0.002199999988079071, s

Game round 3158: epsilon=0.78, loss=0.002899999963119626, score=0, max=0, min=-1, length=851
[(0, 0.99), (-1, 0.01)]
Game round 3159: epsilon=0.78, loss=0.00279999990016222, score=0, max=0, min=-1, length=1018
[(0, 0.99), (-1, 0.01)]
Game round 3160: epsilon=0.78, loss=0.003599999938160181, score=0, max=0, min=-1, length=915
[(0, 0.99), (-1, 0.01)]
Game round 3161: epsilon=0.78, loss=0.002199999988079071, score=0, max=0, min=-1, length=1007
[(0, 0.99), (-1, 0.01)]
Game round 3162: epsilon=0.78, loss=0.002899999963119626, score=0, max=0, min=-1, length=914
[(0, 0.99), (-1, 0.01)]
Game round 3163: epsilon=0.78, loss=0.0019000000320374966, score=0, max=0, min=-1, length=866
[(0, 0.99), (-1, 0.01)]
Game round 3164: epsilon=0.78, loss=0.002899999963119626, score=0, max=0, min=-1, length=937
[(0, 0.99), (-1, 0.01)]
Game round 3165: epsilon=0.78, loss=0.002300000051036477, score=0, max=0, min=-1, length=924
[(0, 0.99), (-1, 0.01)]
Game round 3166: epsilon=0.78, loss=0.003599999938160181, scor

Game round 3228: epsilon=0.77, loss=0.003599999938160181, score=0, max=0, min=-1, length=784
[(0, 0.99), (-1, 0.01)]
Game round 3229: epsilon=0.77, loss=0.0017000000225380063, score=0, max=0, min=-1, length=890
[(0, 0.99), (-1, 0.01)]
Game round 3230: epsilon=0.77, loss=0.00430000014603138, score=0, max=0, min=-1, length=838
[(0, 0.99), (-1, 0.01)]
Game round 3231: epsilon=0.77, loss=0.0017000000225380063, score=0, max=0, min=-1, length=1025
[(0, 0.99), (-1, 0.01)]
Game round 3232: epsilon=0.77, loss=0.003100000089034438, score=0, max=0, min=-1, length=872
[(0, 0.99), (-1, 0.01)]
Game round 3233: epsilon=0.77, loss=0.002199999988079071, score=0, max=0, min=-1, length=787
[(0, 0.99), (-1, 0.01)]
Game round 3234: epsilon=0.77, loss=0.003000000026077032, score=0, max=0, min=-1, length=881
[(0, 0.99), (-1, 0.01)]
Game round 3235: epsilon=0.77, loss=0.002300000051036477, score=0, max=0, min=-1, length=892
[(0, 0.99), (-1, 0.01)]
Game round 3236: epsilon=0.77, loss=0.0034000000450760126, sco

Game round 3298: epsilon=0.77, loss=0.003599999938160181, score=0, max=0, min=-1, length=840
[(0, 0.99), (-1, 0.01)]
Game round 3299: epsilon=0.77, loss=0.0015999999595806003, score=0, max=0, min=-1, length=905
[(0, 0.99), (-1, 0.01)]
Game round 3300: epsilon=0.77, loss=0.004600000102072954, score=0, max=0, min=-1, length=768
[(0, 0.99), (-1, 0.01)]
Game round 3301: epsilon=0.77, loss=0.0035000001080334187, score=0, max=0, min=-1, length=899
[(0, 0.99), (-1, 0.01)]
Game round 3302: epsilon=0.77, loss=0.0027000000700354576, score=0, max=0, min=-1, length=899
[(0, 0.99), (-1, 0.01)]
Game round 3303: epsilon=0.77, loss=0.0035000001080334187, score=0, max=0, min=-1, length=1001
[(0, 0.99), (-1, 0.01)]
Game round 3304: epsilon=0.77, loss=0.0035000001080334187, score=0, max=0, min=-1, length=940
[(0, 0.99), (-1, 0.01)]
Game round 3305: epsilon=0.77, loss=0.004000000189989805, score=0, max=0, min=-1, length=888
[(0, 0.99), (-1, 0.01)]
Game round 3306: epsilon=0.77, loss=0.002199999988079071, 

Game round 3368: epsilon=0.76, loss=0.005799999926239252, score=0, max=0, min=-1, length=935
[(0, 0.99), (-1, 0.01)]
Game round 3369: epsilon=0.76, loss=0.00279999990016222, score=0, max=0, min=-1, length=949
[(0, 0.99), (-1, 0.01)]
Game round 3370: epsilon=0.76, loss=0.0031999999191612005, score=0, max=0, min=-1, length=898
[(0, 0.99), (-1, 0.01)]
Game round 3371: epsilon=0.76, loss=0.002300000051036477, score=0, max=0, min=-1, length=1045
[(0, 0.99), (-1, 0.01)]
Game round 3372: epsilon=0.76, loss=0.002099999925121665, score=0, max=0, min=-1, length=825
[(0, 0.99), (-1, 0.01)]
Game round 3373: epsilon=0.76, loss=0.0024999999441206455, score=0, max=0, min=-1, length=924
[(0, 0.99), (-1, 0.01)]
Game round 3374: epsilon=0.76, loss=0.002199999988079071, score=0, max=0, min=-1, length=904
[(0, 0.99), (-1, 0.01)]
Game round 3375: epsilon=0.76, loss=0.0038999998942017555, score=0, max=0, min=-1, length=881
[(0, 0.99), (-1, 0.01)]
Game round 3376: epsilon=0.76, loss=0.0019000000320374966, sc

Game round 3438: epsilon=0.76, loss=0.0038999998942017555, score=0, max=0, min=-1, length=875
[(0, 0.99), (-1, 0.01)]
Game round 3439: epsilon=0.76, loss=0.004399999976158142, score=0, max=0, min=-1, length=948
[(0, 0.99), (-1, 0.01)]
Game round 3440: epsilon=0.76, loss=0.003599999938160181, score=0, max=0, min=-1, length=908
[(0, 0.99), (-1, 0.01)]
Game round 3441: epsilon=0.76, loss=0.0035000001080334187, score=0, max=0, min=-1, length=930
[(0, 0.99), (-1, 0.01)]
Game round 3442: epsilon=0.76, loss=0.0038999998942017555, score=0, max=0, min=-1, length=823
[(0, 0.99), (-1, 0.01)]
Game round 3443: epsilon=0.76, loss=0.004699999932199717, score=0, max=0, min=-1, length=971
[(0, 0.99), (-1, 0.01)]
Game round 3444: epsilon=0.76, loss=0.006899999920278788, score=0, max=0, min=-1, length=801
[(0, 0.99), (-1, 0.01)]
Game round 3445: epsilon=0.76, loss=0.004600000102072954, score=0, max=0, min=-1, length=932
[(0, 0.99), (-1, 0.01)]
Game round 3446: epsilon=0.76, loss=0.004100000020116568, sco

Game round 3508: epsilon=0.75, loss=0.004900000058114529, score=0, max=0, min=-1, length=791
[(0, 0.99), (-1, 0.01)]
Game round 3509: epsilon=0.75, loss=0.0020000000949949026, score=0, max=0, min=-1, length=862
[(0, 0.99), (-1, 0.01)]
Game round 3510: epsilon=0.75, loss=0.0017999999690800905, score=0, max=0, min=-1, length=869
[(0, 0.99), (-1, 0.01)]
Game round 3511: epsilon=0.75, loss=0.003800000064074993, score=0, max=0, min=-1, length=799
[(0, 0.99), (-1, 0.01)]
Game round 3512: epsilon=0.75, loss=0.0052999998442828655, score=0, max=0, min=-1, length=875
[(0, 0.99), (-1, 0.01)]
Game round 3513: epsilon=0.75, loss=0.003599999938160181, score=0, max=0, min=-1, length=880
[(0, 0.99), (-1, 0.01)]
Game round 3514: epsilon=0.75, loss=0.002400000113993883, score=0, max=0, min=-1, length=992
[(0, 0.99), (-1, 0.01)]
Game round 3515: epsilon=0.75, loss=0.0024999999441206455, score=0, max=0, min=-1, length=909
[(0, 0.99), (-1, 0.01)]
Game round 3516: epsilon=0.75, loss=0.003700000001117587, sc

Game round 3578: epsilon=0.75, loss=0.002400000113993883, score=0, max=0, min=-1, length=962
[(0, 0.99), (-1, 0.01)]
Game round 3579: epsilon=0.75, loss=0.002099999925121665, score=0, max=0, min=-1, length=839
[(0, 0.99), (-1, 0.01)]
Game round 3580: epsilon=0.75, loss=0.004399999976158142, score=0, max=0, min=-1, length=862
[(0, 0.99), (-1, 0.01)]
Game round 3581: epsilon=0.75, loss=0.003100000089034438, score=0, max=0, min=-1, length=817
[(0, 0.99), (-1, 0.01)]
Game round 3582: epsilon=0.75, loss=0.002300000051036477, score=0, max=0, min=-1, length=912
[(0, 0.99), (-1, 0.01)]
Game round 3583: epsilon=0.75, loss=0.002300000051036477, score=0, max=0, min=-1, length=888
[(0, 0.99), (-1, 0.01)]
Game round 3584: epsilon=0.75, loss=0.004100000020116568, score=0, max=0, min=-1, length=864
[(0, 0.99), (-1, 0.01)]
Game round 3585: epsilon=0.75, loss=0.002300000051036477, score=0, max=0, min=-1, length=858
[(0, 0.99), (-1, 0.01)]
Game round 3586: epsilon=0.75, loss=0.00419999985024333, score=0

Game round 3648: epsilon=0.74, loss=0.0012000000569969416, score=0, max=0, min=-1, length=882
[(0, 0.99), (-1, 0.01)]
Game round 3649: epsilon=0.74, loss=0.004900000058114529, score=0, max=0, min=-1, length=818
[(0, 0.99), (-1, 0.01)]
Game round 3650: epsilon=0.74, loss=0.0035000001080334187, score=0, max=0, min=-1, length=1009
[(0, 0.99), (-1, 0.01)]
Game round 3651: epsilon=0.74, loss=0.002099999925121665, score=0, max=0, min=-1, length=763
[(0, 0.99), (-1, 0.01)]
Game round 3652: epsilon=0.74, loss=0.0020000000949949026, score=0, max=0, min=-1, length=914
[(0, 0.99), (-1, 0.01)]
Game round 3653: epsilon=0.74, loss=0.00139999995008111, score=0, max=0, min=-1, length=922
[(0, 0.99), (-1, 0.01)]
Game round 3654: epsilon=0.74, loss=0.0031999999191612005, score=0, max=0, min=-1, length=877
[(0, 0.99), (-1, 0.01)]
Game round 3655: epsilon=0.74, loss=0.0017000000225380063, score=0, max=0, min=-1, length=906
[(0, 0.99), (-1, 0.01)]
Game round 3656: epsilon=0.74, loss=0.00430000014603138, sc

Game round 3718: epsilon=0.74, loss=0.003000000026077032, score=0, max=0, min=-1, length=885
[(0, 0.99), (-1, 0.01)]
Game round 3719: epsilon=0.74, loss=0.004800000227987766, score=0, max=0, min=-1, length=758
[(0, 0.99), (-1, 0.01)]
Game round 3720: epsilon=0.74, loss=0.0044999998062849045, score=0, max=0, min=-1, length=701
[(0, 0.99), (-1, 0.01)]
Game round 3721: epsilon=0.74, loss=0.0038999998942017555, score=0, max=0, min=-1, length=883
[(0, 0.99), (-1, 0.01)]
Game round 3722: epsilon=0.74, loss=0.0026000000070780516, score=0, max=0, min=-1, length=871
[(0, 0.99), (-1, 0.01)]
Game round 3723: epsilon=0.74, loss=0.00419999985024333, score=0, max=0, min=-1, length=857
[(0, 0.99), (-1, 0.01)]
Game round 3724: epsilon=0.74, loss=0.004600000102072954, score=0, max=0, min=-1, length=847
[(0, 0.99), (-1, 0.01)]
Game round 3725: epsilon=0.74, loss=0.0031999999191612005, score=0, max=0, min=-1, length=875
[(0, 0.99), (-1, 0.01)]
Game round 3726: epsilon=0.74, loss=0.005900000222027302, sco

Game round 3788: epsilon=0.73, loss=0.0031999999191612005, score=0, max=0, min=-1, length=872
[(0, 0.99), (-1, 0.01)]
Game round 3789: epsilon=0.73, loss=0.004800000227987766, score=0, max=0, min=-1, length=838
[(0, 0.99), (-1, 0.01)]
Game round 3790: epsilon=0.73, loss=0.0035000001080334187, score=0, max=0, min=-1, length=837
[(0, 0.99), (-1, 0.01)]
Game round 3791: epsilon=0.73, loss=0.003100000089034438, score=0, max=0, min=-1, length=819
[(0, 0.99), (-1, 0.01)]
Game round 3792: epsilon=0.73, loss=0.00430000014603138, score=0, max=0, min=-1, length=979
[(0, 0.99), (-1, 0.01)]
Game round 3793: epsilon=0.73, loss=0.005100000184029341, score=0, max=0, min=-1, length=831
[(0, 0.99), (-1, 0.01)]
Game round 3794: epsilon=0.73, loss=0.002300000051036477, score=0, max=0, min=-1, length=809
[(0, 0.99), (-1, 0.01)]
Game round 3795: epsilon=0.73, loss=0.0032999999821186066, score=0, max=0, min=-1, length=779
[(0, 0.99), (-1, 0.01)]
Game round 3796: epsilon=0.73, loss=0.0020000000949949026, sco

Game round 3858: epsilon=0.73, loss=0.003100000089034438, score=0, max=0, min=-1, length=954
[(0, 0.99), (-1, 0.01)]
Game round 3859: epsilon=0.73, loss=0.004100000020116568, score=0, max=0, min=-1, length=846
[(0, 0.99), (-1, 0.01)]
Game round 3860: epsilon=0.73, loss=0.004100000020116568, score=0, max=0, min=-1, length=833
[(0, 0.99), (-1, 0.01)]
Game round 3861: epsilon=0.73, loss=0.0027000000700354576, score=0, max=0, min=-1, length=875
[(0, 0.99), (-1, 0.01)]
Game round 3862: epsilon=0.73, loss=0.00139999995008111, score=0, max=0, min=-1, length=881
[(0, 0.99), (-1, 0.01)]
Game round 3863: epsilon=0.73, loss=0.003800000064074993, score=0, max=0, min=-1, length=884
[(0, 0.99), (-1, 0.01)]
Game round 3864: epsilon=0.73, loss=0.00279999990016222, score=0, max=0, min=-1, length=881
[(0, 0.99), (-1, 0.01)]
Game round 3865: epsilon=0.73, loss=0.003100000089034438, score=0, max=0, min=-1, length=823
[(0, 0.99), (-1, 0.01)]
Game round 3866: epsilon=0.73, loss=0.0035000001080334187, score=

Game round 3928: epsilon=0.73, loss=0.003000000026077032, score=0, max=0, min=-1, length=893
[(0, 0.99), (-1, 0.01)]
Game round 3929: epsilon=0.73, loss=0.002400000113993883, score=0, max=0, min=-1, length=919
[(0, 0.99), (-1, 0.01)]
Game round 3930: epsilon=0.72, loss=0.0020000000949949026, score=0, max=0, min=-1, length=874
[(0, 0.99), (-1, 0.01)]
Game round 3931: epsilon=0.72, loss=0.002400000113993883, score=0, max=0, min=-1, length=985
[(0, 0.99), (-1, 0.01)]
Game round 3932: epsilon=0.72, loss=0.002099999925121665, score=0, max=0, min=-1, length=850
[(0, 0.99), (-1, 0.01)]
Game round 3933: epsilon=0.72, loss=0.0034000000450760126, score=0, max=0, min=-1, length=860
[(0, 0.99), (-1, 0.01)]
Game round 3934: epsilon=0.72, loss=0.0031999999191612005, score=0, max=0, min=-1, length=865
[(0, 0.99), (-1, 0.01)]
Game round 3935: epsilon=0.72, loss=0.0027000000700354576, score=0, max=0, min=-1, length=972
[(0, 0.99), (-1, 0.01)]
Game round 3936: epsilon=0.72, loss=0.0024999999441206455, s

Game round 3998: epsilon=0.72, loss=0.0017000000225380063, score=0, max=0, min=-1, length=823
[(0, 0.99), (-1, 0.01)]
Game round 3999: epsilon=0.72, loss=0.004100000020116568, score=0, max=0, min=-1, length=898
[(0, 0.99), (-1, 0.01)]
Game round 4000: epsilon=0.72, loss=0.0031999999191612005, score=0, max=0, min=-1, length=924
[(0, 0.99), (-1, 0.01)]
Game round 4001: epsilon=0.72, loss=0.002300000051036477, score=0, max=0, min=-1, length=861
[(0, 0.99), (-1, 0.01)]
Game round 4002: epsilon=0.72, loss=0.004900000058114529, score=0, max=0, min=-1, length=861
[(0, 0.99), (-1, 0.01)]
Game round 4003: epsilon=0.72, loss=0.0010999999940395355, score=0, max=0, min=-1, length=969
[(0, 0.99), (-1, 0.01)]
Game round 4004: epsilon=0.72, loss=0.00279999990016222, score=0, max=0, min=-1, length=866
[(0, 0.99), (-1, 0.01)]
Game round 4005: epsilon=0.72, loss=0.005400000140070915, score=0, max=0, min=-1, length=852
[(0, 0.99), (-1, 0.01)]
Game round 4006: epsilon=0.72, loss=0.003000000026077032, scor

Game round 4068: epsilon=0.72, loss=0.0044999998062849045, score=0, max=0, min=-1, length=848
[(0, 0.99), (-1, 0.01)]
Game round 4069: epsilon=0.72, loss=0.004000000189989805, score=0, max=0, min=-1, length=828
[(0, 0.99), (-1, 0.01)]
Game round 4070: epsilon=0.72, loss=0.003700000001117587, score=0, max=0, min=-1, length=887
[(0, 0.99), (-1, 0.01)]
Game round 4071: epsilon=0.72, loss=0.0019000000320374966, score=0, max=0, min=-1, length=884
[(0, 0.99), (-1, 0.01)]
Game round 4072: epsilon=0.72, loss=0.003000000026077032, score=0, max=0, min=-1, length=859
[(0, 0.99), (-1, 0.01)]
Game round 4073: epsilon=0.71, loss=0.003599999938160181, score=0, max=0, min=-1, length=783
[(0, 0.99), (-1, 0.01)]
Game round 4074: epsilon=0.71, loss=0.0017999999690800905, score=0, max=0, min=-1, length=896
[(0, 0.99), (-1, 0.01)]
Game round 4075: epsilon=0.71, loss=0.001500000013038516, score=0, max=0, min=-1, length=786
[(0, 0.99), (-1, 0.01)]
Game round 4076: epsilon=0.71, loss=0.0017000000225380063, sc

Game round 4138: epsilon=0.71, loss=0.0035000001080334187, score=0, max=0, min=-1, length=856
[(0, 0.99), (-1, 0.01)]
Game round 4139: epsilon=0.71, loss=0.0034000000450760126, score=0, max=0, min=-1, length=1017
[(0, 0.99), (-1, 0.01)]
Game round 4140: epsilon=0.71, loss=0.0032999999821186066, score=0, max=0, min=-1, length=849
[(0, 0.99), (-1, 0.01)]
Game round 4141: epsilon=0.71, loss=0.0015999999595806003, score=0, max=0, min=-1, length=848
[(0, 0.99), (-1, 0.01)]
Game round 4142: epsilon=0.71, loss=0.0038999998942017555, score=0, max=0, min=-1, length=879
[(0, 0.99), (-1, 0.01)]
Game round 4143: epsilon=0.71, loss=0.0034000000450760126, score=0, max=0, min=-1, length=812
[(0, 0.99), (-1, 0.01)]
Game round 4144: epsilon=0.71, loss=0.0034000000450760126, score=0, max=0, min=-1, length=824
[(0, 0.99), (-1, 0.01)]
Game round 4145: epsilon=0.71, loss=0.00279999990016222, score=0, max=0, min=-1, length=874
[(0, 0.99), (-1, 0.01)]
Game round 4146: epsilon=0.71, loss=0.00279999990016222, 

Game round 4208: epsilon=0.71, loss=0.0031999999191612005, score=0, max=0, min=-1, length=809
[(0, 0.99), (-1, 0.01)]
Game round 4209: epsilon=0.71, loss=0.002300000051036477, score=0, max=0, min=-1, length=954
[(0, 0.99), (-1, 0.01)]
Game round 4210: epsilon=0.71, loss=0.00419999985024333, score=0, max=0, min=-1, length=892
[(0, 0.99), (-1, 0.01)]
Game round 4211: epsilon=0.71, loss=0.0031999999191612005, score=0, max=0, min=-1, length=862
[(0, 0.99), (-1, 0.01)]
Game round 4212: epsilon=0.71, loss=0.002199999988079071, score=0, max=0, min=-1, length=1013
[(0, 0.99), (-1, 0.01)]
Game round 4213: epsilon=0.71, loss=0.004100000020116568, score=0, max=0, min=-1, length=799
[(0, 0.99), (-1, 0.01)]
Game round 4214: epsilon=0.71, loss=0.004800000227987766, score=0, max=0, min=-1, length=813
[(0, 0.99), (-1, 0.01)]
Game round 4215: epsilon=0.7, loss=0.0024999999441206455, score=0, max=0, min=-1, length=965
[(0, 0.99), (-1, 0.01)]
Game round 4216: epsilon=0.7, loss=0.004399999976158142, score

Game round 4279: epsilon=0.7, loss=0.0044999998062849045, score=0, max=0, min=-1, length=910
[(0, 0.99), (-1, 0.01)]
Game round 4280: epsilon=0.7, loss=0.003800000064074993, score=0, max=0, min=-1, length=863
[(0, 0.99), (-1, 0.01)]
Game round 4281: epsilon=0.7, loss=0.002199999988079071, score=0, max=0, min=-1, length=887
[(0, 0.99), (-1, 0.01)]
Game round 4282: epsilon=0.7, loss=0.00419999985024333, score=0, max=0, min=-1, length=969
[(0, 0.99), (-1, 0.01)]
Game round 4283: epsilon=0.7, loss=0.00139999995008111, score=0, max=0, min=-1, length=896
[(0, 0.99), (-1, 0.01)]
Game round 4284: epsilon=0.7, loss=0.002099999925121665, score=0, max=0, min=-1, length=963
[(0, 0.99), (-1, 0.01)]
Game round 4285: epsilon=0.7, loss=0.0026000000070780516, score=0, max=0, min=-1, length=831
[(0, 0.99), (-1, 0.01)]
Game round 4286: epsilon=0.7, loss=0.00419999985024333, score=0, max=0, min=-1, length=773
[(0, 0.99), (-1, 0.01)]
Game round 4287: epsilon=0.7, loss=0.0034000000450760126, score=0, max=0,

In [ ]:
game = Tetris(width = 10, height = 20)
game.start_new_tetromino()

plays = 20

while plays>0:
    player = model(game.grid[:-game.width])
    move = tf.argmax(player, axis=1).numpy()[0]
    game.move(move)
    #game.move(np.random.choice(range(5)))
    print("game")
    game.print_game()
    print(model(game.current_game(game.grid, game.current_tetromino, game.current_position, game.current_rotation)[:-game.width]))
    
    print("nexts")
    #[ print(g.reshape(21, 10)) for g in game.nextGrids()]
    plays -= 1

game.print_game()